{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"y"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/deepar\/vector3\/y"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/deepar\/vector3\/y"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/Vector3\/y","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Y value."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"y"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"}],"title":"y","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@SA@Vector3@FI@y","modules":[{"name":"DeepAR"}],"navigatorTitle":[{"kind":"identifier","text":"y"}]},"hierarchy":{"paths":[["doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/Vector3"]]},"seeAlsoSections":[{"title":"Components","identifiers":["doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/Vector3\/x","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/Vector3\/z"],"generated":true}],"references":{"doc://ai.deepar.DeepAR/documentation/DeepAR":{"role":"collection","title":"DeepAR","abstract":[{"type":"text","text":"Build rich Augmented Reality experiences for iPhone, iPad and Mac."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR","kind":"symbol","type":"topic","url":"\/documentation\/deepar"},"doc://ai.deepar.DeepAR/documentation/DeepAR/Vector3/z":{"role":"symbol","title":"z","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"z"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"}],"abstract":[{"type":"text","text":"Z value."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/Vector3\/z","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"z"}],"url":"\/documentation\/deepar\/vector3\/z"},"doc://ai.deepar.DeepAR/documentation/DeepAR/Vector3":{"role":"symbol","title":"Vector3","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Vector3"}],"abstract":[{"type":"text","text":"A three-dimensional float vector."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/Vector3","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Vector3"}],"url":"\/documentation\/deepar\/vector3"},"doc://ai.deepar.DeepAR/documentation/DeepAR/Vector3/y":{"role":"symbol","title":"y","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"y"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"}],"abstract":[{"type":"text","text":"Y value."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/Vector3\/y","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"y"}],"url":"\/documentation\/deepar\/vector3\/y"},"doc://ai.deepar.DeepAR/documentation/DeepAR/Vector3/x":{"role":"symbol","title":"x","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"x"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"}],"abstract":[{"type":"text","text":"X value."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/Vector3\/x","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"x"}],"url":"\/documentation\/deepar\/vector3\/x"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"y"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"y"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"Components","identifiers":["doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/Vector3\/x","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/Vector3\/z"],"generated":true}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"typeIdentifier","text":"float","preciseIdentifier":"c:f"},{"kind":"text","text":" "},{"kind":"identifier","text":"y"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1Vector3~1z\/title","value":"z"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1Vector3~1z\/fragments","value":[{"kind":"identifier","text":"z"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1Vector3\/title","value":"Vector3"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1Vector3~1y\/title","value":"y"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1Vector3~1y\/fragments","value":[{"kind":"identifier","text":"y"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1Vector3~1x\/title","value":"x"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1Vector3~1x\/fragments","value":[{"kind":"identifier","text":"x"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}