{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"z"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/deepar\/vector4\/z"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/deepar\/vector4\/z"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/Vector4\/z","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Z value."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"z"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"}],"title":"z","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@SA@Vector4@FI@z","modules":[{"name":"DeepAR"}],"navigatorTitle":[{"kind":"identifier","text":"z"}]},"hierarchy":{"paths":[["doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/Vector4"]]},"seeAlsoSections":[{"title":"Components","identifiers":["doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/Vector4\/x","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/Vector4\/y","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/Vector4\/w"],"generated":true}],"references":{"doc://ai.deepar.DeepAR/documentation/DeepAR/Vector4":{"role":"symbol","title":"Vector4","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Vector4"}],"abstract":[{"type":"text","text":"A four-dimensional float vector."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/Vector4","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Vector4"}],"url":"\/documentation\/deepar\/vector4"},"doc://ai.deepar.DeepAR/documentation/DeepAR/Vector4/x":{"role":"symbol","title":"x","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"x"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"}],"abstract":[{"type":"text","text":"X value."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/Vector4\/x","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"x"}],"url":"\/documentation\/deepar\/vector4\/x"},"doc://ai.deepar.DeepAR/documentation/DeepAR":{"role":"collection","title":"DeepAR","abstract":[{"type":"text","text":"Build rich Augmented Reality experiences for iPhone, iPad and Mac."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR","kind":"symbol","type":"topic","url":"\/documentation\/deepar"},"doc://ai.deepar.DeepAR/documentation/DeepAR/Vector4/w":{"role":"symbol","title":"w","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"w"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"}],"abstract":[{"type":"text","text":"W value."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/Vector4\/w","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"w"}],"url":"\/documentation\/deepar\/vector4\/w"},"doc://ai.deepar.DeepAR/documentation/DeepAR/Vector4/y":{"role":"symbol","title":"y","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"y"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"}],"abstract":[{"type":"text","text":"Y value."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/Vector4\/y","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"y"}],"url":"\/documentation\/deepar\/vector4\/y"},"doc://ai.deepar.DeepAR/documentation/DeepAR/Vector4/z":{"role":"symbol","title":"z","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"z"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"}],"abstract":[{"type":"text","text":"Z value."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/Vector4\/z","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"z"}],"url":"\/documentation\/deepar\/vector4\/z"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"z"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"z"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"Components","identifiers":["doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/Vector4\/x","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/Vector4\/y","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/Vector4\/w"],"generated":true}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"typeIdentifier","text":"float","preciseIdentifier":"c:f"},{"kind":"text","text":" "},{"kind":"identifier","text":"z"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1Vector4\/title","value":"Vector4"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1Vector4~1x\/title","value":"x"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1Vector4~1x\/fragments","value":[{"kind":"identifier","text":"x"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1Vector4~1w\/title","value":"w"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1Vector4~1w\/fragments","value":[{"kind":"identifier","text":"w"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1Vector4~1y\/title","value":"y"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1Vector4~1y\/fragments","value":[{"kind":"identifier","text":"y"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1Vector4~1z\/title","value":"z"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1Vector4~1z\/fragments","value":[{"kind":"identifier","text":"z"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}