{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ARErrorType"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/deepar\/arerrortype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/deepar\/arerrortype"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/ai.deepar.DeepAR\/SQ","doc:\/\/ai.deepar.DeepAR\/SH","doc:\/\/ai.deepar.DeepAR\/SY","doc:\/\/ai.deepar.DeepAR\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/ARErrorType","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"DeepAR error types."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ARErrorType"}],"title":"ARErrorType","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@E@ARErrorType","modules":[{"name":"DeepAR"}],"navigatorTitle":[{"kind":"identifier","text":"ARErrorType"}]},"hierarchy":{"paths":[["doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/ARErrorType\/DEEPAR_ERROR_TYPE_DEBUG","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/ARErrorType\/DEEPAR_ERROR_TYPE_INFO","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/ARErrorType\/DEEPAR_ERROR_TYPE_WARNING","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/ARErrorType\/DEEPAR_ERROR_TYPE_ERROR"]},{"title":"Initializers","identifiers":["doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/ARErrorType\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/ARErrorType\/Equatable-Implementations","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/ARErrorType\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://ai.deepar.DeepAR/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/ai.deepar.DeepAR\/SH"},"doc://ai.deepar.DeepAR/documentation/DeepAR/ARErrorType":{"role":"symbol","title":"ARErrorType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ARErrorType"}],"abstract":[{"type":"text","text":"DeepAR error types."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/ARErrorType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ARErrorType"}],"url":"\/documentation\/deepar\/arerrortype"},"doc://ai.deepar.DeepAR/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/ai.deepar.DeepAR\/s8SendableP"},"doc://ai.deepar.DeepAR/documentation/DeepAR":{"role":"collection","title":"DeepAR","abstract":[{"type":"text","text":"Build rich Augmented Reality experiences for iPhone, iPad and Mac."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR","kind":"symbol","type":"topic","url":"\/documentation\/deepar"},"doc://ai.deepar.DeepAR/documentation/DeepAR/ARErrorType/DEEPAR_ERROR_TYPE_DEBUG":{"role":"symbol","title":"ARErrorType.DEEPAR_ERROR_TYPE_DEBUG","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"DEEPAR_ERROR_TYPE_DEBUG"}],"abstract":[{"type":"text","text":"DeepAR debug type."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/ARErrorType\/DEEPAR_ERROR_TYPE_DEBUG","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DEEPAR_ERROR_TYPE_DEBUG"}],"url":"\/documentation\/deepar\/arerrortype\/deepar_error_type_debug"},"doc://ai.deepar.DeepAR/documentation/DeepAR/ARErrorType/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/ARErrorType\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/deepar\/arerrortype\/rawrepresentable-implementations"},"doc://ai.deepar.DeepAR/documentation/DeepAR/ARErrorType/DEEPAR_ERROR_TYPE_INFO":{"role":"symbol","title":"ARErrorType.DEEPAR_ERROR_TYPE_INFO","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"DEEPAR_ERROR_TYPE_INFO"}],"abstract":[{"type":"text","text":"DeepAR info type."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/ARErrorType\/DEEPAR_ERROR_TYPE_INFO","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DEEPAR_ERROR_TYPE_INFO"}],"url":"\/documentation\/deepar\/arerrortype\/deepar_error_type_info"},"doc://ai.deepar.DeepAR/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/ai.deepar.DeepAR\/SQ"},"doc://ai.deepar.DeepAR/documentation/DeepAR/ARErrorType/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/ARErrorType\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/deepar\/arerrortype\/init(rawvalue:)"},"doc://ai.deepar.DeepAR/documentation/DeepAR/ARErrorType/DEEPAR_ERROR_TYPE_WARNING":{"role":"symbol","title":"ARErrorType.DEEPAR_ERROR_TYPE_WARNING","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"DEEPAR_ERROR_TYPE_WARNING"}],"abstract":[{"type":"text","text":"DeepAR warning type."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/ARErrorType\/DEEPAR_ERROR_TYPE_WARNING","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DEEPAR_ERROR_TYPE_WARNING"}],"url":"\/documentation\/deepar\/arerrortype\/deepar_error_type_warning"},"doc://ai.deepar.DeepAR/documentation/DeepAR/ARErrorType/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/ARErrorType\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/deepar\/arerrortype\/equatable-implementations"},"doc://ai.deepar.DeepAR/documentation/DeepAR/ARErrorType/DEEPAR_ERROR_TYPE_ERROR":{"role":"symbol","title":"ARErrorType.DEEPAR_ERROR_TYPE_ERROR","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"DEEPAR_ERROR_TYPE_ERROR"}],"abstract":[{"type":"text","text":"DeepAR error type."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/ARErrorType\/DEEPAR_ERROR_TYPE_ERROR","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DEEPAR_ERROR_TYPE_ERROR"}],"url":"\/documentation\/deepar\/arerrortype\/deepar_error_type_error"},"doc://ai.deepar.DeepAR/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/ai.deepar.DeepAR\/SY"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"ARErrorType"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ARErrorType"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"ARErrorType"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/ARErrorType\/DEEPAR_ERROR_TYPE_DEBUG","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/ARErrorType\/DEEPAR_ERROR_TYPE_INFO","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/ARErrorType\/DEEPAR_ERROR_TYPE_WARNING","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/ARErrorType\/DEEPAR_ERROR_TYPE_ERROR"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ARErrorType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1ARErrorType\/title","value":"ARErrorType"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1ARErrorType\/fragments","value":[{"kind":"identifier","text":"ARErrorType"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1ARErrorType~1DEEPAR_ERROR_TYPE_DEBUG\/title","value":"DEEPAR_ERROR_TYPE_DEBUG"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1ARErrorType~1DEEPAR_ERROR_TYPE_DEBUG\/fragments","value":[{"kind":"identifier","text":"DEEPAR_ERROR_TYPE_DEBUG"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1ARErrorType~1DEEPAR_ERROR_TYPE_INFO\/title","value":"DEEPAR_ERROR_TYPE_INFO"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1ARErrorType~1DEEPAR_ERROR_TYPE_INFO\/fragments","value":[{"kind":"identifier","text":"DEEPAR_ERROR_TYPE_INFO"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1ARErrorType~1DEEPAR_ERROR_TYPE_WARNING\/title","value":"DEEPAR_ERROR_TYPE_WARNING"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1ARErrorType~1DEEPAR_ERROR_TYPE_WARNING\/fragments","value":[{"kind":"identifier","text":"DEEPAR_ERROR_TYPE_WARNING"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1ARErrorType~1DEEPAR_ERROR_TYPE_ERROR\/title","value":"DEEPAR_ERROR_TYPE_ERROR"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1ARErrorType~1DEEPAR_ERROR_TYPE_ERROR\/fragments","value":[{"kind":"identifier","text":"DEEPAR_ERROR_TYPE_ERROR"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}