{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CameraController"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Example of usage:"}]},{"type":"paragraph","inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"ObjC"}]}]},{"type":"codeListing","syntax":"objc","code":["self.cameraController = [[CameraController alloc]","                         initWithDeepAR:self.deepAR];","[self.cameraController startCamera];"]},{"type":"paragraph","inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"Swift"}]}]},{"type":"codeListing","syntax":"swift","code":["cameraController = CameraController(deepAR:self.deepAR)","cameraController.startCamera()"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/deepar\/cameracontroller"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/deepar\/cameracontroller"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/ai.deepar.DeepAR\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/ai.deepar.DeepAR\/objc(pl)NSObject","doc:\/\/ai.deepar.DeepAR\/s7CVarArgP","doc:\/\/ai.deepar.DeepAR\/s28CustomDebugStringConvertibleP","doc:\/\/ai.deepar.DeepAR\/s23CustomStringConvertibleP","doc:\/\/ai.deepar.DeepAR\/SQ","doc:\/\/ai.deepar.DeepAR\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/CameraController","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Helper class that wraps "},{"type":"reference","isActive":true,"identifier":"https:\/\/developer.apple.com\/documentation\/avfoundation"},{"type":"text","text":" "},{"type":"text","text":"to handle camera-related logic like starting camera preview, choosing resolution, front or back camera, and video orientation for DeepAR."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CameraController"}],"title":"CameraController","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)CameraController","modules":[{"name":"DeepAR"}],"navigatorTitle":[{"kind":"identifier","text":"CameraController"}]},"hierarchy":{"paths":[["doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/CameraController\/init()","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/CameraController\/init(deepAR:)"]},{"title":"Camera","identifiers":["doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/CameraController\/startCamera()","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/CameraController\/startCamera(withAudio:)","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/CameraController\/stopCamera()"]},{"title":"Audio","identifiers":["doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/CameraController\/startAudio()","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/CameraController\/stopAudio()"]},{"title":"Check permissions","identifiers":["doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/CameraController\/checkCameraPermission()","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/CameraController\/checkMicrophonePermission()"]},{"title":"Options","identifiers":["doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/CameraController\/position","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/CameraController\/preset","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/CameraController\/videoOrientation"]},{"title":"Instance Properties","identifiers":["doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/CameraController\/deepAR"]}],"references":{"doc://ai.deepar.DeepAR/documentation/DeepAR/CameraController/startAudio()":{"role":"symbol","title":"startAudio()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startAudio"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Starts capturing audio samples."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/CameraController\/startAudio()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"startAudio"}],"url":"\/documentation\/deepar\/cameracontroller\/startaudio()"},"doc://ai.deepar.DeepAR/documentation/DeepAR/DeepAR":{"role":"symbol","title":"DeepAR","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DeepAR"}],"abstract":[{"type":"text","text":"Main class for interacting with DeepAR engine."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DeepAR"}],"url":"\/documentation\/deepar\/deepar"},"doc://ai.deepar.DeepAR/documentation/DeepAR/CameraController/init()":{"role":"symbol","title":"init()","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"!()"}],"abstract":[{"type":"text","text":"Initializes a new "},{"type":"codeVoice","code":"CameraController"},{"type":"text","text":" instance."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/CameraController\/init()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/deepar\/cameracontroller\/init()"},"doc://ai.deepar.DeepAR/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/ai.deepar.DeepAR\/s23CustomStringConvertibleP"},"doc://ai.deepar.DeepAR/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/ai.deepar.DeepAR\/s7CVarArgP"},"doc://ai.deepar.DeepAR/documentation/DeepAR/CameraController/init(deepAR:)":{"role":"symbol","title":"init(deepAR:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"!("},{"kind":"externalParam","text":"deepAR"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DeepAR","preciseIdentifier":"c:objc(cs)DeepAR"},{"kind":"text","text":"!)"}],"abstract":[{"type":"text","text":"Initializes a new "},{"type":"codeVoice","code":"CameraController"},{"type":"text","text":" instance."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/CameraController\/init(deepAR:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithDeepAR:"}],"url":"\/documentation\/deepar\/cameracontroller\/init(deepar:)"},"doc://ai.deepar.DeepAR/documentation/DeepAR/CameraController/stopCamera()":{"role":"symbol","title":"stopCamera()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"stopCamera"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Stops camera preview."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/CameraController\/stopCamera()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"stopCamera"}],"url":"\/documentation\/deepar\/cameracontroller\/stopcamera()"},"doc://ai.deepar.DeepAR/documentation/DeepAR/CameraController/startCamera(withAudio:)":{"role":"symbol","title":"startCamera(withAudio:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startCamera"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withAudio"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Starts camera preview. Allows to start microphone as well."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/CameraController\/startCamera(withAudio:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"startCameraWithAudio:"}],"url":"\/documentation\/deepar\/cameracontroller\/startcamera(withaudio:)"},"doc://ai.deepar.DeepAR/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/ai.deepar.DeepAR\/SQ"},"doc://ai.deepar.DeepAR/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/ai.deepar.DeepAR\/SH"},"doc://ai.deepar.DeepAR/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/ai.deepar.DeepAR\/s28CustomDebugStringConvertibleP"},"doc://ai.deepar.DeepAR/documentation/DeepAR/CameraController":{"role":"symbol","title":"CameraController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CameraController"}],"abstract":[{"type":"text","text":"Helper class that wraps "},{"type":"reference","isActive":true,"identifier":"https:\/\/developer.apple.com\/documentation\/avfoundation"},{"type":"text","text":" "},{"type":"text","text":"to handle camera-related logic like starting camera preview, choosing resolution, front or back camera, and video orientation for DeepAR."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/CameraController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CameraController"}],"url":"\/documentation\/deepar\/cameracontroller"},"https://developer.apple.com/documentation/avfoundation":{"title":"AVFoundation","titleInlineContent":[{"type":"text","text":"AVFoundation"}],"type":"link","identifier":"https:\/\/developer.apple.com\/documentation\/avfoundation","url":"https:\/\/developer.apple.com\/documentation\/avfoundation"},"doc://ai.deepar.DeepAR/documentation/DeepAR/CameraController/stopAudio()":{"role":"symbol","title":"stopAudio()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"stopAudio"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Stops capturing audio samples."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/CameraController\/stopAudio()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"stopAudio"}],"url":"\/documentation\/deepar\/cameracontroller\/stopaudio()"},"doc://ai.deepar.DeepAR/documentation/DeepAR/CameraController/position":{"role":"symbol","title":"position","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"position"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AVCaptureDevice","preciseIdentifier":"c:objc(cs)AVCaptureDevice"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Position","preciseIdentifier":"c:@E@AVCaptureDevicePosition"}],"abstract":[{"type":"text","text":"The currently selected camera."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/CameraController\/position","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"position"}],"url":"\/documentation\/deepar\/cameracontroller\/position"},"doc://ai.deepar.DeepAR/documentation/DeepAR/CameraController/checkMicrophonePermission()":{"role":"symbol","title":"checkMicrophonePermission()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"checkMicrophonePermission"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Checks microphone permissions."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/CameraController\/checkMicrophonePermission()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"checkMicrophonePermission"}],"url":"\/documentation\/deepar\/cameracontroller\/checkmicrophonepermission()"},"doc://ai.deepar.DeepAR/documentation/DeepAR/CameraController/checkCameraPermission()":{"role":"symbol","title":"checkCameraPermission()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"checkCameraPermission"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Checks camera permissions."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/CameraController\/checkCameraPermission()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"checkCameraPermission"}],"url":"\/documentation\/deepar\/cameracontroller\/checkcamerapermission()"},"doc://ai.deepar.DeepAR/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/ai.deepar.DeepAR\/objc(pl)NSObject"},"doc://ai.deepar.DeepAR/documentation/DeepAR/CameraController/deepAR":{"role":"symbol","title":"deepAR","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"deepAR"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DeepAR","preciseIdentifier":"c:objc(cs)DeepAR"},{"kind":"text","text":"!"}],"abstract":[{"type":"text","text":"The "},{"type":"reference","isActive":true,"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR"},{"type":"text","text":" instance."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/CameraController\/deepAR","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"deepAR"}],"url":"\/documentation\/deepar\/cameracontroller\/deepar"},"doc://ai.deepar.DeepAR/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/ai.deepar.DeepAR\/objc(cs)NSObject"},"doc://ai.deepar.DeepAR/documentation/DeepAR/CameraController/videoOrientation":{"role":"symbol","title":"videoOrientation","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"videoOrientation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AVCaptureVideoOrientation","preciseIdentifier":"c:@E@AVCaptureVideoOrientation"}],"abstract":[{"type":"text","text":"Represents currently used video orientation."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/CameraController\/videoOrientation","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"videoOrientation"}],"url":"\/documentation\/deepar\/cameracontroller\/videoorientation"},"doc://ai.deepar.DeepAR/documentation/DeepAR":{"role":"collection","title":"DeepAR","abstract":[{"type":"text","text":"Build rich Augmented Reality experiences for iPhone, iPad and Mac."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR","kind":"symbol","type":"topic","url":"\/documentation\/deepar"},"doc://ai.deepar.DeepAR/documentation/DeepAR/CameraController/startCamera()":{"role":"symbol","title":"startCamera()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startCamera"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Starts camera preview."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/CameraController\/startCamera()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"startCamera"}],"url":"\/documentation\/deepar\/cameracontroller\/startcamera()"},"doc://ai.deepar.DeepAR/documentation/DeepAR/CameraController/preset":{"role":"symbol","title":"preset","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"preset"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AVCaptureSession","preciseIdentifier":"c:objc(cs)AVCaptureSession"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Preset","preciseIdentifier":"c:@T@AVCaptureSessionPreset"},{"kind":"text","text":"!"}],"abstract":[{"type":"text","text":"Represents camera resolution currently used."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/CameraController\/preset","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"preset"}],"url":"\/documentation\/deepar\/cameracontroller\/preset"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"CameraController"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"CameraController"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"CameraController"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Initializers","identifiers":["doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/CameraController\/init()","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/CameraController\/init(deepAR:)"]},{"title":"Camera","identifiers":["doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/CameraController\/startCamera()","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/CameraController\/startCamera(withAudio:)","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/CameraController\/stopCamera()"]},{"title":"Audio","identifiers":["doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/CameraController\/startAudio()","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/CameraController\/stopAudio()"]},{"title":"Check permissions","identifiers":["doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/CameraController\/checkCameraPermission()","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/CameraController\/checkMicrophonePermission()"]},{"title":"Options","identifiers":["doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/CameraController\/position","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/CameraController\/preset","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/CameraController\/videoOrientation"]},{"title":"Instance Properties","identifiers":["doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/CameraController\/deepAR"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/ai.deepar.DeepAR\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"CameraController"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1CameraController~1startAudio()\/title","value":"startAudio"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1CameraController~1startAudio()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"startAudio"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR\/title","value":"DeepAR"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR\/fragments","value":[{"kind":"identifier","text":"DeepAR"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1CameraController~1init()\/title","value":"init"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1CameraController~1init()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1CameraController~1init(deepAR:)\/title","value":"initWithDeepAR:"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1CameraController~1init(deepAR:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithDeepAR:"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1CameraController~1stopCamera()\/title","value":"stopCamera"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1CameraController~1stopCamera()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"stopCamera"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1CameraController~1startCamera(withAudio:)\/title","value":"startCameraWithAudio:"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1CameraController~1startCamera(withAudio:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"startCameraWithAudio:"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1CameraController\/title","value":"CameraController"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1CameraController\/fragments","value":[{"kind":"identifier","text":"CameraController"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1CameraController~1stopAudio()\/title","value":"stopAudio"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1CameraController~1stopAudio()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"stopAudio"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1CameraController~1position\/title","value":"position"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1CameraController~1position\/fragments","value":[{"kind":"identifier","text":"position"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1CameraController~1checkMicrophonePermission()\/title","value":"checkMicrophonePermission"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1CameraController~1checkMicrophonePermission()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"checkMicrophonePermission"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1CameraController~1checkCameraPermission()\/title","value":"checkCameraPermission"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1CameraController~1checkCameraPermission()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"checkCameraPermission"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1CameraController~1deepAR\/title","value":"deepAR"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1CameraController~1deepAR\/fragments","value":[{"kind":"identifier","text":"deepAR"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1CameraController~1videoOrientation\/title","value":"videoOrientation"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1CameraController~1videoOrientation\/fragments","value":[{"kind":"identifier","text":"videoOrientation"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1CameraController~1startCamera()\/title","value":"startCamera"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1CameraController~1startCamera()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"startCamera"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1CameraController~1preset\/title","value":"preset"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1CameraController~1preset\/fragments","value":[{"kind":"identifier","text":"preset"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}