{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"DeepARDelegate"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObjectProtocol","preciseIdentifier":"c:objc(pl)NSObject"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"It is set on "},{"type":"reference","isActive":true,"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/delegate"}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/deepar\/deepardelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/deepar\/deepardelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/ai.deepar.DeepAR\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}],"identifier":{"url":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepARDelegate","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"A delegate that is used to notify events from DeepAR to the consumer of the DeepAR SDK."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"DeepARDelegate"}],"title":"DeepARDelegate","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"c:objc(pl)DeepARDelegate","modules":[{"name":"DeepAR"}],"navigatorTitle":[{"kind":"identifier","text":"DeepARDelegate"}]},"hierarchy":{"paths":[["doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR"]]},"topicSections":[{"title":"DeepAR state","identifiers":["doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepARDelegate\/didInitialize()","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepARDelegate\/didFinishShutdown()"]},{"title":"Image and video recording","identifiers":["doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepARDelegate\/didTakeScreenshot(_:)","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepARDelegate\/didStartVideoRecording()","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepARDelegate\/didFinishVideoRecording(_:)","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepARDelegate\/didFinishPreparingForVideoRecording()","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepARDelegate\/recordingFailedWithError(_:)"]},{"title":"Effects","identifiers":["doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepARDelegate\/didSwitchEffect(_:)","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepARDelegate\/animationTransitioned(toState:)"]},{"title":"Face data","identifiers":["doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepARDelegate\/faceVisiblityDidChange(_:)","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepARDelegate\/faceTracked(_:)","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepARDelegate\/number(ofFacesVisibleChanged:)"]},{"title":"Offscreen capture","identifiers":["doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepARDelegate\/frameAvailable(_:)"]},{"title":"Errors","identifiers":["doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepARDelegate\/onError(withCode:error:)"]},{"title":"Deprecated","identifiers":["doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepARDelegate\/imageVisibilityChanged(_:imageVisible:)"]}],"references":{"doc://ai.deepar.DeepAR/documentation/DeepAR/DeepARDelegate":{"role":"symbol","title":"DeepARDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"DeepARDelegate"}],"abstract":[{"type":"text","text":"A delegate that is used to notify events from DeepAR to the consumer of the DeepAR SDK."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepARDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DeepARDelegate"}],"url":"\/documentation\/deepar\/deepardelegate"},"doc://ai.deepar.DeepAR/documentation/DeepAR/DeepARDelegate/frameAvailable(_:)":{"navigatorTitle":[{"kind":"identifier","text":"frameAvailable:"}],"role":"symbol","title":"frameAvailable(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"frameAvailable"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CMSampleBuffer","preciseIdentifier":"c:@T@CMSampleBufferRef"},{"kind":"text","text":"!)"}],"abstract":[{"type":"text","text":"Called when a new processed frame is available."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepARDelegate\/frameAvailable(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/deepar\/deepardelegate\/frameavailable(_:)"},"doc://ai.deepar.DeepAR/objc(pl)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/ai.deepar.DeepAR\/objc(pl)NSObject"},"doc://ai.deepar.DeepAR/documentation/DeepAR/DeepARDelegate/didTakeScreenshot(_:)":{"navigatorTitle":[{"kind":"identifier","text":"didTakeScreenshot:"}],"role":"symbol","title":"didTakeScreenshot(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didTakeScreenshot"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":"!)"}],"abstract":[{"type":"text","text":"Called when DeepAR has finished taking a screenshot."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepARDelegate\/didTakeScreenshot(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/deepar\/deepardelegate\/didtakescreenshot(_:)"},"doc://ai.deepar.DeepAR/documentation/DeepAR/DeepARDelegate/didFinishShutdown()":{"navigatorTitle":[{"kind":"identifier","text":"didFinishShutdown"}],"role":"symbol","title":"didFinishShutdown()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didFinishShutdown"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"DeepAR has successfully shut down after the method shutdown call."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepARDelegate\/didFinishShutdown()","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/deepar\/deepardelegate\/didfinishshutdown()"},"doc://ai.deepar.DeepAR/documentation/DeepAR/DeepARDelegate/didFinishPreparingForVideoRecording()":{"navigatorTitle":[{"kind":"identifier","text":"didFinishPreparingForVideoRecording"}],"role":"symbol","title":"didFinishPreparingForVideoRecording()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didFinishPreparingForVideoRecording"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Called when the video recording preparation is finished."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepARDelegate\/didFinishPreparingForVideoRecording()","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/deepar\/deepardelegate\/didfinishpreparingforvideorecording()"},"doc://ai.deepar.DeepAR/documentation/DeepAR/DeepARDelegate/animationTransitioned(toState:)":{"role":"symbol","title":"animationTransitioned(toState:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"animationTransitioned"},{"kind":"text","text":"("},{"kind":"externalParam","text":"toState"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!)"}],"abstract":[{"type":"text","text":"Called when the conditions have been met for the animation to transition to the next state (e.g. mouth open, emotion detected etc.)."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepARDelegate\/animationTransitioned(toState:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"animationTransitionedToState:"}],"url":"\/documentation\/deepar\/deepardelegate\/animationtransitioned(tostate:)"},"doc://ai.deepar.DeepAR/documentation/DeepAR/DeepARDelegate/number(ofFacesVisibleChanged:)":{"navigatorTitle":[{"kind":"identifier","text":"numberOfFacesVisibleChanged:"}],"role":"symbol","title":"number(ofFacesVisibleChanged:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"number"},{"kind":"text","text":"("},{"kind":"externalParam","text":"ofFacesVisibleChanged"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Whenever a face is detected or lost from the scene this method is called."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepARDelegate\/number(ofFacesVisibleChanged:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/deepar\/deepardelegate\/number(offacesvisiblechanged:)"},"doc://ai.deepar.DeepAR/documentation/DeepAR/DeepARDelegate/didFinishVideoRecording(_:)":{"role":"symbol","title":"didFinishVideoRecording(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didFinishVideoRecording"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!)"}],"abstract":[{"type":"text","text":"Called when the video recording is finished."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepARDelegate\/didFinishVideoRecording(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"didFinishVideoRecording:"}],"url":"\/documentation\/deepar\/deepardelegate\/didfinishvideorecording(_:)"},"doc://ai.deepar.DeepAR/documentation/DeepAR/DeepARDelegate/imageVisibilityChanged(_:imageVisible:)":{"role":"symbol","title":"imageVisibilityChanged(_:imageVisible:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageVisibilityChanged"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"imageVisible"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Called when the tracked image changes visibility."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepARDelegate\/imageVisibilityChanged(_:imageVisible:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"imageVisibilityChanged:imageVisible:"}],"url":"\/documentation\/deepar\/deepardelegate\/imagevisibilitychanged(_:imagevisible:)"},"doc://ai.deepar.DeepAR/documentation/DeepAR":{"role":"collection","title":"DeepAR","abstract":[{"type":"text","text":"Build rich Augmented Reality experiences for iPhone, iPad and Mac."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR","kind":"symbol","type":"topic","url":"\/documentation\/deepar"},"doc://ai.deepar.DeepAR/documentation/DeepAR/DeepARDelegate/didSwitchEffect(_:)":{"navigatorTitle":[{"kind":"identifier","text":"didSwitchEffect:"}],"role":"symbol","title":"didSwitchEffect(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didSwitchEffect"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!)"}],"abstract":[{"type":"text","text":"Called when the effect is fully switched (loaded) and ready for preview."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepARDelegate\/didSwitchEffect(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/deepar\/deepardelegate\/didswitcheffect(_:)"},"doc://ai.deepar.DeepAR/documentation/DeepAR/DeepARDelegate/didInitialize()":{"role":"symbol","title":"didInitialize()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didInitialize"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Called when the DeepAR engine initialization is complete."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepARDelegate\/didInitialize()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"didInitialize"}],"url":"\/documentation\/deepar\/deepardelegate\/didinitialize()"},"doc://ai.deepar.DeepAR/documentation/DeepAR/DeepARDelegate/didStartVideoRecording()":{"navigatorTitle":[{"kind":"identifier","text":"didStartVideoRecording"}],"role":"symbol","title":"didStartVideoRecording()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didStartVideoRecording"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Called when DeepAR has started video recording."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepARDelegate\/didStartVideoRecording()","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/deepar\/deepardelegate\/didstartvideorecording()"},"doc://ai.deepar.DeepAR/documentation/DeepAR/DeepARDelegate/onError(withCode:error:)":{"navigatorTitle":[{"kind":"identifier","text":"onErrorWithCode:error:"}],"role":"symbol","title":"onError(withCode:error:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onError"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ARErrorType","preciseIdentifier":"c:@E@ARErrorType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!)"}],"abstract":[{"type":"text","text":"Called when an error has occurred within DeepAR SDK."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepARDelegate\/onError(withCode:error:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/deepar\/deepardelegate\/onerror(withcode:error:)"},"doc://ai.deepar.DeepAR/documentation/DeepAR/DeepARDelegate/faceTracked(_:)":{"navigatorTitle":[{"kind":"identifier","text":"faceTracked:"}],"role":"symbol","title":"faceTracked(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"faceTracked"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MultiFaceData","preciseIdentifier":"c:@SA@MultiFaceData"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Called on each frame where at least one face data is detected."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepARDelegate\/faceTracked(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/deepar\/deepardelegate\/facetracked(_:)"},"doc://ai.deepar.DeepAR/documentation/DeepAR/DeepAR/delegate":{"role":"symbol","title":"delegate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DeepARDelegate","preciseIdentifier":"c:objc(pl)DeepARDelegate"},{"kind":"text","text":"!"}],"abstract":[{"type":"text","text":"The object which implements "},{"type":"reference","isActive":true,"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepARDelegate"},{"type":"text","text":" protocol to listen for async events coming from DeepAR."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/delegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"delegate"}],"url":"\/documentation\/deepar\/deepar\/delegate"},"doc://ai.deepar.DeepAR/documentation/DeepAR/DeepARDelegate/faceVisiblityDidChange(_:)":{"navigatorTitle":[{"kind":"identifier","text":"faceVisiblityDidChange:"}],"role":"symbol","title":"faceVisiblityDidChange(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"faceVisiblityDidChange"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Called when DeepAR detects a new face or loses a face that has been tracked."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepARDelegate\/faceVisiblityDidChange(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/deepar\/deepardelegate\/facevisiblitydidchange(_:)"},"doc://ai.deepar.DeepAR/documentation/DeepAR/DeepARDelegate/recordingFailedWithError(_:)":{"navigatorTitle":[{"kind":"identifier","text":"recordingFailedWithError:"}],"role":"symbol","title":"recordingFailedWithError(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"recordingFailedWithError"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"!)"}],"abstract":[{"type":"text","text":"Called when an error has occurred during video recording."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepARDelegate\/recordingFailedWithError(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/deepar\/deepardelegate\/recordingfailedwitherror(_:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"DeepARDelegate"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DeepARDelegate"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"DeepARDelegate"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"DeepAR state","identifiers":["doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepARDelegate\/didInitialize()","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepARDelegate\/didFinishShutdown()"]},{"title":"Image and video recording","identifiers":["doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepARDelegate\/didTakeScreenshot(_:)","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepARDelegate\/didStartVideoRecording()","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepARDelegate\/didFinishVideoRecording(_:)","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepARDelegate\/didFinishPreparingForVideoRecording()","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepARDelegate\/recordingFailedWithError(_:)"]},{"title":"Effects","identifiers":["doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepARDelegate\/didSwitchEffect(_:)","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepARDelegate\/animationTransitioned(toState:)"]},{"title":"Face data","identifiers":["doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepARDelegate\/faceVisiblityDidChange(_:)","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepARDelegate\/faceTracked(_:)","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepARDelegate\/number(ofFacesVisibleChanged:)"]},{"title":"Offscreen capture","identifiers":["doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepARDelegate\/frameAvailable(_:)"]},{"title":"Errors","identifiers":["doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepARDelegate\/onError(withCode:error:)"]},{"title":"Deprecated","identifiers":["doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepARDelegate\/imageVisibilityChanged(_:imageVisible:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/ai.deepar.DeepAR\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"DeepARDelegate"},{"kind":"text","text":"<"},{"kind":"keyword","text":"NSObject"},{"kind":"text","text":">"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepARDelegate\/title","value":"DeepARDelegate"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepARDelegate\/fragments","value":[{"kind":"identifier","text":"DeepARDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepARDelegate~1frameAvailable(_:)\/title","value":"frameAvailable:"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepARDelegate~1frameAvailable(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"frameAvailable:"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepARDelegate~1didTakeScreenshot(_:)\/title","value":"didTakeScreenshot:"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepARDelegate~1didTakeScreenshot(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didTakeScreenshot:"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepARDelegate~1didFinishShutdown()\/title","value":"didFinishShutdown"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepARDelegate~1didFinishShutdown()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didFinishShutdown"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepARDelegate~1didFinishPreparingForVideoRecording()\/title","value":"didFinishPreparingForVideoRecording"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepARDelegate~1didFinishPreparingForVideoRecording()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didFinishPreparingForVideoRecording"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepARDelegate~1animationTransitioned(toState:)\/title","value":"animationTransitionedToState:"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepARDelegate~1animationTransitioned(toState:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"animationTransitionedToState:"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepARDelegate~1number(ofFacesVisibleChanged:)\/title","value":"numberOfFacesVisibleChanged:"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepARDelegate~1number(ofFacesVisibleChanged:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"numberOfFacesVisibleChanged:"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepARDelegate~1didFinishVideoRecording(_:)\/title","value":"didFinishVideoRecording:"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepARDelegate~1didFinishVideoRecording(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didFinishVideoRecording:"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepARDelegate~1imageVisibilityChanged(_:imageVisible:)\/title","value":"imageVisibilityChanged:imageVisible:"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepARDelegate~1imageVisibilityChanged(_:imageVisible:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"imageVisibilityChanged:imageVisible:"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepARDelegate~1didSwitchEffect(_:)\/title","value":"didSwitchEffect:"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepARDelegate~1didSwitchEffect(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didSwitchEffect:"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepARDelegate~1didInitialize()\/title","value":"didInitialize"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepARDelegate~1didInitialize()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didInitialize"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepARDelegate~1didStartVideoRecording()\/title","value":"didStartVideoRecording"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepARDelegate~1didStartVideoRecording()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didStartVideoRecording"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepARDelegate~1onError(withCode:error:)\/title","value":"onErrorWithCode:error:"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepARDelegate~1onError(withCode:error:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onErrorWithCode:error:"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepARDelegate~1faceTracked(_:)\/title","value":"faceTracked:"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepARDelegate~1faceTracked(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"faceTracked:"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR~1delegate\/title","value":"delegate"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR~1delegate\/fragments","value":[{"kind":"identifier","text":"delegate"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepARDelegate~1faceVisiblityDidChange(_:)\/title","value":"faceVisiblityDidChange:"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepARDelegate~1faceVisiblityDidChange(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"faceVisiblityDidChange:"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepARDelegate~1recordingFailedWithError(_:)\/title","value":"recordingFailedWithError:"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepARDelegate~1recordingFailedWithError(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"recordingFailedWithError:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}