{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceTrackingInitParameters"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Pass to "},{"type":"reference","isActive":true,"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/setFaceTrackingInitParameters(_:)"},{"type":"text","text":"."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/deepar\/facetrackinginitparameters"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/deepar\/facetrackinginitparameters"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/ai.deepar.DeepAR\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/FaceTrackingInitParameters","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Properties related to face tracking initialization."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceTrackingInitParameters"}],"title":"FaceTrackingInitParameters","roleHeading":"Structure","role":"symbol","symbolKind":"struct","externalID":"c:@SA@FaceTrackingInitParameters","modules":[{"name":"DeepAR"}],"navigatorTitle":[{"kind":"identifier","text":"FaceTrackingInitParameters"}]},"hierarchy":{"paths":[["doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/FaceTrackingInitParameters\/init()","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/FaceTrackingInitParameters\/init(initializeEngineWithFaceTracking:initializeFaceTrackingSynchronously:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/FaceTrackingInitParameters\/initializeEngineWithFaceTracking","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/FaceTrackingInitParameters\/initializeFaceTrackingSynchronously"]}],"references":{"doc://ai.deepar.DeepAR/documentation/DeepAR/FaceTrackingInitParameters/init()":{"role":"symbol","title":"init()","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/FaceTrackingInitParameters\/init()","kind":"symbol","type":"topic","url":"\/documentation\/deepar\/facetrackinginitparameters\/init()"},"doc://ai.deepar.DeepAR/documentation/DeepAR/FaceTrackingInitParameters/init(initializeEngineWithFaceTracking:initializeFaceTrackingSynchronously:)":{"role":"symbol","title":"init(initializeEngineWithFaceTracking:initializeFaceTrackingSynchronously:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"initializeEngineWithFaceTracking"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"initializeFaceTrackingSynchronously"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/FaceTrackingInitParameters\/init(initializeEngineWithFaceTracking:initializeFaceTrackingSynchronously:)","kind":"symbol","type":"topic","url":"\/documentation\/deepar\/facetrackinginitparameters\/init(initializeenginewithfacetracking:initializefacetrackingsynchronously:)"},"doc://ai.deepar.DeepAR/documentation/DeepAR":{"role":"collection","title":"DeepAR","abstract":[{"type":"text","text":"Build rich Augmented Reality experiences for iPhone, iPad and Mac."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR","kind":"symbol","type":"topic","url":"\/documentation\/deepar"},"doc://ai.deepar.DeepAR/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/ai.deepar.DeepAR\/s8SendableP"},"doc://ai.deepar.DeepAR/documentation/DeepAR/FaceTrackingInitParameters/initializeEngineWithFaceTracking":{"role":"symbol","title":"initializeEngineWithFaceTracking","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"initializeEngineWithFaceTracking"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Engine will initialize face tracking as soon as possible if true."},{"type":"text","text":" "},{"type":"text","text":"Else it will initialize when face tracking when it is needed. Eg. when loading effect that uses face tracking."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/FaceTrackingInitParameters\/initializeEngineWithFaceTracking","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initializeEngineWithFaceTracking"}],"url":"\/documentation\/deepar\/facetrackinginitparameters\/initializeenginewithfacetracking"},"doc://ai.deepar.DeepAR/documentation/DeepAR/DeepAR/setFaceTrackingInitParameters(_:)":{"role":"symbol","title":"setFaceTrackingInitParameters(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setFaceTrackingInitParameters"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"FaceTrackingInitParameters","preciseIdentifier":"c:@SA@FaceTrackingInitParameters"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Set parameters that will determine how the face tracking is initialized."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/setFaceTrackingInitParameters(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setFaceTrackingInitParameters:"}],"url":"\/documentation\/deepar\/deepar\/setfacetrackinginitparameters(_:)"},"doc://ai.deepar.DeepAR/documentation/DeepAR/FaceTrackingInitParameters":{"role":"symbol","title":"FaceTrackingInitParameters","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceTrackingInitParameters"}],"abstract":[{"type":"text","text":"Properties related to face tracking initialization."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/FaceTrackingInitParameters","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FaceTrackingInitParameters"}],"url":"\/documentation\/deepar\/facetrackinginitparameters"},"doc://ai.deepar.DeepAR/documentation/DeepAR/FaceTrackingInitParameters/initializeFaceTrackingSynchronously":{"role":"symbol","title":"initializeFaceTrackingSynchronously","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"initializeFaceTrackingSynchronously"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"If true, face tracking will be initialized synchronously and will be blocking DeepAR rendering."},{"type":"text","text":" "},{"type":"text","text":"Else it will initialize in background thread and not block rendering."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/FaceTrackingInitParameters\/initializeFaceTrackingSynchronously","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initializeFaceTrackingSynchronously"}],"url":"\/documentation\/deepar\/facetrackinginitparameters\/initializefacetrackingsynchronously"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Structure"},{"op":"replace","path":"\/metadata\/title","value":"FaceTrackingInitParameters"},{"op":"replace","path":"\/metadata\/symbolKind","value":"struct"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"FaceTrackingInitParameters"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/FaceTrackingInitParameters\/initializeEngineWithFaceTracking","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/FaceTrackingInitParameters\/initializeFaceTrackingSynchronously"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"typedef"},{"kind":"text","text":" "},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceTrackingInitParameters"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1FaceTrackingInitParameters~1initializeEngineWithFaceTracking\/title","value":"initializeEngineWithFaceTracking"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1FaceTrackingInitParameters~1initializeEngineWithFaceTracking\/fragments","value":[{"kind":"identifier","text":"initializeEngineWithFaceTracking"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR~1setFaceTrackingInitParameters(_:)\/title","value":"setFaceTrackingInitParameters:"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR~1setFaceTrackingInitParameters(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setFaceTrackingInitParameters:"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1FaceTrackingInitParameters\/title","value":"FaceTrackingInitParameters"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1FaceTrackingInitParameters~1initializeFaceTrackingSynchronously\/title","value":"initializeFaceTrackingSynchronously"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1FaceTrackingInitParameters~1initializeFaceTrackingSynchronously\/fragments","value":[{"kind":"identifier","text":"initializeFaceTrackingSynchronously"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}