{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"MultiFaceData"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/deepar\/multifacedata"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/deepar\/multifacedata"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/ai.deepar.DeepAR\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/MultiFaceData","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Structure containing face data for up to 4 detected faces."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"MultiFaceData"}],"title":"MultiFaceData","roleHeading":"Structure","role":"symbol","symbolKind":"struct","externalID":"c:@SA@MultiFaceData","modules":[{"name":"DeepAR"}],"navigatorTitle":[{"kind":"identifier","text":"MultiFaceData"}]},"hierarchy":{"paths":[["doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/MultiFaceData\/init()","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/MultiFaceData\/init(faceData:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/MultiFaceData\/faceData"]}],"references":{"doc://ai.deepar.DeepAR/documentation/DeepAR":{"role":"collection","title":"DeepAR","abstract":[{"type":"text","text":"Build rich Augmented Reality experiences for iPhone, iPad and Mac."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR","kind":"symbol","type":"topic","url":"\/documentation\/deepar"},"doc://ai.deepar.DeepAR/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/ai.deepar.DeepAR\/s8SendableP"},"doc://ai.deepar.DeepAR/documentation/DeepAR/MultiFaceData/faceData":{"role":"symbol","title":"faceData","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"faceData"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"FaceData","preciseIdentifier":"c:@SA@FaceData"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"FaceData","preciseIdentifier":"c:@SA@FaceData"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"FaceData","preciseIdentifier":"c:@SA@FaceData"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"FaceData","preciseIdentifier":"c:@SA@FaceData"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Array of face data for up to 4 detected faces."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/MultiFaceData\/faceData","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"faceData"}],"url":"\/documentation\/deepar\/multifacedata\/facedata"},"doc://ai.deepar.DeepAR/documentation/DeepAR/MultiFaceData/init()":{"role":"symbol","title":"init()","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/MultiFaceData\/init()","kind":"symbol","type":"topic","url":"\/documentation\/deepar\/multifacedata\/init()"},"doc://ai.deepar.DeepAR/documentation/DeepAR/MultiFaceData":{"role":"symbol","title":"MultiFaceData","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"MultiFaceData"}],"abstract":[{"type":"text","text":"Structure containing face data for up to 4 detected faces."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/MultiFaceData","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MultiFaceData"}],"url":"\/documentation\/deepar\/multifacedata"},"doc://ai.deepar.DeepAR/documentation/DeepAR/MultiFaceData/init(faceData:)":{"role":"symbol","title":"init(faceData:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"faceData"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"FaceData","preciseIdentifier":"c:@SA@FaceData"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"FaceData","preciseIdentifier":"c:@SA@FaceData"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"FaceData","preciseIdentifier":"c:@SA@FaceData"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"FaceData","preciseIdentifier":"c:@SA@FaceData"},{"kind":"text","text":"))"}],"abstract":[],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/MultiFaceData\/init(faceData:)","kind":"symbol","type":"topic","url":"\/documentation\/deepar\/multifacedata\/init(facedata:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Structure"},{"op":"replace","path":"\/metadata\/title","value":"MultiFaceData"},{"op":"replace","path":"\/metadata\/symbolKind","value":"struct"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"MultiFaceData"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/MultiFaceData\/faceData"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"typedef"},{"kind":"text","text":" "},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"MultiFaceData"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1MultiFaceData~1faceData\/title","value":"faceData"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1MultiFaceData~1faceData\/fragments","value":[{"kind":"identifier","text":"faceData"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1MultiFaceData\/title","value":"MultiFaceData"}],"traits":[{"interfaceLanguage":"occ"}]}]}