{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"OutputFormat"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/deepar\/outputformat"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/deepar\/outputformat"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/ai.deepar.DeepAR\/SQ","doc:\/\/ai.deepar.DeepAR\/SH","doc:\/\/ai.deepar.DeepAR\/SY","doc:\/\/ai.deepar.DeepAR\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/OutputFormat","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Output color format."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"OutputFormat"}],"title":"OutputFormat","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@E@OutputFormat","modules":[{"name":"DeepAR"}],"navigatorTitle":[{"kind":"identifier","text":"OutputFormat"}]},"hierarchy":{"paths":[["doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/OutputFormat\/Undefined","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/OutputFormat\/RGBA","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/OutputFormat\/BGRA","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/OutputFormat\/ARGB","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/OutputFormat\/ABGR","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/OutputFormat\/COUNT"]},{"title":"Initializers","identifiers":["doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/OutputFormat\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/OutputFormat\/Equatable-Implementations","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/OutputFormat\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://ai.deepar.DeepAR/documentation/DeepAR/OutputFormat/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/OutputFormat\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/deepar\/outputformat\/init(rawvalue:)"},"doc://ai.deepar.DeepAR/documentation/DeepAR":{"role":"collection","title":"DeepAR","abstract":[{"type":"text","text":"Build rich Augmented Reality experiences for iPhone, iPad and Mac."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR","kind":"symbol","type":"topic","url":"\/documentation\/deepar"},"doc://ai.deepar.DeepAR/documentation/DeepAR/OutputFormat/Undefined":{"role":"symbol","title":"OutputFormat.Undefined","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"Undefined"}],"abstract":[{"type":"text","text":"Undefined format."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/OutputFormat\/Undefined","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Undefined"}],"url":"\/documentation\/deepar\/outputformat\/undefined"},"doc://ai.deepar.DeepAR/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/ai.deepar.DeepAR\/SH"},"doc://ai.deepar.DeepAR/documentation/DeepAR/OutputFormat/ABGR":{"role":"symbol","title":"OutputFormat.ABGR","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"ABGR"}],"abstract":[{"type":"text","text":"Alpha, blue, green and red format."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/OutputFormat\/ABGR","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ABGR"}],"url":"\/documentation\/deepar\/outputformat\/abgr"},"doc://ai.deepar.DeepAR/documentation/DeepAR/OutputFormat/COUNT":{"role":"symbol","title":"OutputFormat.COUNT","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"COUNT"}],"abstract":[{"type":"text","text":"Number of formats."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/OutputFormat\/COUNT","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"COUNT"}],"url":"\/documentation\/deepar\/outputformat\/count"},"doc://ai.deepar.DeepAR/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/ai.deepar.DeepAR\/SY"},"doc://ai.deepar.DeepAR/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/ai.deepar.DeepAR\/s8SendableP"},"doc://ai.deepar.DeepAR/documentation/DeepAR/OutputFormat/BGRA":{"role":"symbol","title":"OutputFormat.BGRA","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"BGRA"}],"abstract":[{"type":"text","text":"Blue, green, red and alpha format."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/OutputFormat\/BGRA","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BGRA"}],"url":"\/documentation\/deepar\/outputformat\/bgra"},"doc://ai.deepar.DeepAR/documentation/DeepAR/OutputFormat":{"role":"symbol","title":"OutputFormat","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"OutputFormat"}],"abstract":[{"type":"text","text":"Output color format."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/OutputFormat","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OutputFormat"}],"url":"\/documentation\/deepar\/outputformat"},"doc://ai.deepar.DeepAR/documentation/DeepAR/OutputFormat/ARGB":{"role":"symbol","title":"OutputFormat.ARGB","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"ARGB"}],"abstract":[{"type":"text","text":"Alpha, red, green and blue format."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/OutputFormat\/ARGB","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ARGB"}],"url":"\/documentation\/deepar\/outputformat\/argb"},"doc://ai.deepar.DeepAR/documentation/DeepAR/OutputFormat/RGBA":{"role":"symbol","title":"OutputFormat.RGBA","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"RGBA"}],"abstract":[{"type":"text","text":"Red, green, blue and alpha format."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/OutputFormat\/RGBA","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RGBA"}],"url":"\/documentation\/deepar\/outputformat\/rgba"},"doc://ai.deepar.DeepAR/documentation/DeepAR/OutputFormat/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/OutputFormat\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/deepar\/outputformat\/equatable-implementations"},"doc://ai.deepar.DeepAR/documentation/DeepAR/OutputFormat/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/OutputFormat\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/deepar\/outputformat\/rawrepresentable-implementations"},"doc://ai.deepar.DeepAR/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/ai.deepar.DeepAR\/SQ"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"OutputFormat"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"OutputFormat"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"OutputFormat"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/OutputFormat\/Undefined","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/OutputFormat\/RGBA","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/OutputFormat\/BGRA","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/OutputFormat\/ARGB","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/OutputFormat\/ABGR","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/OutputFormat\/COUNT"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"OutputFormat"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1OutputFormat~1Undefined\/title","value":"Undefined"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1OutputFormat~1Undefined\/fragments","value":[{"kind":"identifier","text":"Undefined"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1OutputFormat~1ABGR\/title","value":"ABGR"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1OutputFormat~1ABGR\/fragments","value":[{"kind":"identifier","text":"ABGR"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1OutputFormat~1COUNT\/title","value":"COUNT"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1OutputFormat~1COUNT\/fragments","value":[{"kind":"identifier","text":"COUNT"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1OutputFormat~1BGRA\/title","value":"BGRA"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1OutputFormat~1BGRA\/fragments","value":[{"kind":"identifier","text":"BGRA"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1OutputFormat\/title","value":"OutputFormat"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1OutputFormat\/fragments","value":[{"kind":"identifier","text":"OutputFormat"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1OutputFormat~1ARGB\/title","value":"ARGB"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1OutputFormat~1ARGB\/fragments","value":[{"kind":"identifier","text":"ARGB"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1OutputFormat~1RGBA\/title","value":"RGBA"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1OutputFormat~1RGBA\/fragments","value":[{"kind":"identifier","text":"RGBA"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}