{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ToneMapping"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/deepar\/tonemapping"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/deepar\/tonemapping"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/ai.deepar.DeepAR\/SQ","doc:\/\/ai.deepar.DeepAR\/SH","doc:\/\/ai.deepar.DeepAR\/SY","doc:\/\/ai.deepar.DeepAR\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/ToneMapping","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Possible types for tone mapping"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ToneMapping"}],"title":"ToneMapping","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@E@ToneMapping","modules":[{"name":"DeepAR"}],"navigatorTitle":[{"kind":"identifier","text":"ToneMapping"}]},"hierarchy":{"paths":[["doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/ToneMapping\/ACES","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/ToneMapping\/AGX","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/ToneMapping\/CINEON","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/ToneMapping\/LINEAR","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/ToneMapping\/NEUTRAL","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/ToneMapping\/REINHARD"]},{"title":"Initializers","identifiers":["doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/ToneMapping\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/ToneMapping\/Equatable-Implementations","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/ToneMapping\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://ai.deepar.DeepAR/documentation/DeepAR/ToneMapping/NEUTRAL":{"role":"symbol","title":"ToneMapping.NEUTRAL","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"NEUTRAL"}],"abstract":[],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/ToneMapping\/NEUTRAL","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NEUTRAL"}],"url":"\/documentation\/deepar\/tonemapping\/neutral"},"doc://ai.deepar.DeepAR/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/ai.deepar.DeepAR\/SH"},"doc://ai.deepar.DeepAR/documentation/DeepAR/ToneMapping/AGX":{"role":"symbol","title":"ToneMapping.AGX","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"AGX"}],"abstract":[],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/ToneMapping\/AGX","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AGX"}],"url":"\/documentation\/deepar\/tonemapping\/agx"},"doc://ai.deepar.DeepAR/documentation/DeepAR/ToneMapping/CINEON":{"role":"symbol","title":"ToneMapping.CINEON","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"CINEON"}],"abstract":[],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/ToneMapping\/CINEON","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CINEON"}],"url":"\/documentation\/deepar\/tonemapping\/cineon"},"doc://ai.deepar.DeepAR/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/ai.deepar.DeepAR\/SQ"},"doc://ai.deepar.DeepAR/documentation/DeepAR/ToneMapping":{"role":"symbol","title":"ToneMapping","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ToneMapping"}],"abstract":[{"type":"text","text":"Possible types for tone mapping"}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/ToneMapping","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ToneMapping"}],"url":"\/documentation\/deepar\/tonemapping"},"doc://ai.deepar.DeepAR/documentation/DeepAR/ToneMapping/REINHARD":{"role":"symbol","title":"ToneMapping.REINHARD","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"REINHARD"}],"abstract":[],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/ToneMapping\/REINHARD","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"REINHARD"}],"url":"\/documentation\/deepar\/tonemapping\/reinhard"},"doc://ai.deepar.DeepAR/documentation/DeepAR/ToneMapping/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/ToneMapping\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/deepar\/tonemapping\/rawrepresentable-implementations"},"doc://ai.deepar.DeepAR/documentation/DeepAR/ToneMapping/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/ToneMapping\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/deepar\/tonemapping\/init(rawvalue:)"},"doc://ai.deepar.DeepAR/documentation/DeepAR/ToneMapping/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/ToneMapping\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/deepar\/tonemapping\/equatable-implementations"},"doc://ai.deepar.DeepAR/documentation/DeepAR":{"role":"collection","title":"DeepAR","abstract":[{"type":"text","text":"Build rich Augmented Reality experiences for iPhone, iPad and Mac."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR","kind":"symbol","type":"topic","url":"\/documentation\/deepar"},"doc://ai.deepar.DeepAR/documentation/DeepAR/ToneMapping/LINEAR":{"role":"symbol","title":"ToneMapping.LINEAR","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"LINEAR"}],"abstract":[],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/ToneMapping\/LINEAR","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LINEAR"}],"url":"\/documentation\/deepar\/tonemapping\/linear"},"doc://ai.deepar.DeepAR/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/ai.deepar.DeepAR\/SY"},"doc://ai.deepar.DeepAR/documentation/DeepAR/ToneMapping/ACES":{"role":"symbol","title":"ToneMapping.ACES","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"ACES"}],"abstract":[],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/ToneMapping\/ACES","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ACES"}],"url":"\/documentation\/deepar\/tonemapping\/aces"},"doc://ai.deepar.DeepAR/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/ai.deepar.DeepAR\/s8SendableP"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"ToneMapping"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ToneMapping"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"ToneMapping"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/ToneMapping\/ACES","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/ToneMapping\/AGX","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/ToneMapping\/CINEON","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/ToneMapping\/LINEAR","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/ToneMapping\/NEUTRAL","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/ToneMapping\/REINHARD"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ToneMapping"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1ToneMapping~1NEUTRAL\/title","value":"NEUTRAL"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1ToneMapping~1NEUTRAL\/fragments","value":[{"kind":"identifier","text":"NEUTRAL"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1ToneMapping~1AGX\/title","value":"AGX"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1ToneMapping~1AGX\/fragments","value":[{"kind":"identifier","text":"AGX"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1ToneMapping~1CINEON\/title","value":"CINEON"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1ToneMapping~1CINEON\/fragments","value":[{"kind":"identifier","text":"CINEON"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1ToneMapping\/title","value":"ToneMapping"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1ToneMapping\/fragments","value":[{"kind":"identifier","text":"ToneMapping"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1ToneMapping~1REINHARD\/title","value":"REINHARD"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1ToneMapping~1REINHARD\/fragments","value":[{"kind":"identifier","text":"REINHARD"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1ToneMapping~1LINEAR\/title","value":"LINEAR"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1ToneMapping~1LINEAR\/fragments","value":[{"kind":"identifier","text":"LINEAR"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1ToneMapping~1ACES\/title","value":"ACES"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1ToneMapping~1ACES\/fragments","value":[{"kind":"identifier","text":"ACES"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}