{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"TouchInfo"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/deepar\/touchinfo"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/deepar\/touchinfo"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/ai.deepar.DeepAR\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/TouchInfo","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Contains information about the current location and status of the started touch."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"TouchInfo"}],"title":"TouchInfo","roleHeading":"Structure","role":"symbol","symbolKind":"struct","externalID":"c:@SA@TouchInfo","modules":[{"name":"DeepAR"}],"navigatorTitle":[{"kind":"identifier","text":"TouchInfo"}]},"hierarchy":{"paths":[["doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/TouchInfo\/x","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/TouchInfo\/y","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/TouchInfo\/type"]},{"title":"Initializers","identifiers":["doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/TouchInfo\/init()","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/TouchInfo\/init(x:y:type:)"]}],"references":{"doc://ai.deepar.DeepAR/documentation/DeepAR/TouchInfo/x":{"role":"symbol","title":"x","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"x"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[{"type":"text","text":"Value of the x coordinate of the current touch location."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/TouchInfo\/x","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"x"}],"url":"\/documentation\/deepar\/touchinfo\/x"},"doc://ai.deepar.DeepAR/documentation/DeepAR/TouchInfo/y":{"role":"symbol","title":"y","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"y"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[{"type":"text","text":"Value of the y coordinate of the current touch location."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/TouchInfo\/y","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"y"}],"url":"\/documentation\/deepar\/touchinfo\/y"},"doc://ai.deepar.DeepAR/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/ai.deepar.DeepAR\/s8SendableP"},"doc://ai.deepar.DeepAR/documentation/DeepAR/TouchInfo":{"role":"symbol","title":"TouchInfo","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"TouchInfo"}],"abstract":[{"type":"text","text":"Contains information about the current location and status of the started touch."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/TouchInfo","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TouchInfo"}],"url":"\/documentation\/deepar\/touchinfo"},"doc://ai.deepar.DeepAR/documentation/DeepAR/TouchInfo/type":{"role":"symbol","title":"type","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TouchType","preciseIdentifier":"c:@E@TouchType"}],"abstract":[{"type":"text","text":"The status, i.e., touch type, of the touch."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/TouchInfo\/type","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"type"}],"url":"\/documentation\/deepar\/touchinfo\/type"},"doc://ai.deepar.DeepAR/documentation/DeepAR/TouchInfo/init()":{"role":"symbol","title":"init()","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/TouchInfo\/init()","kind":"symbol","type":"topic","url":"\/documentation\/deepar\/touchinfo\/init()"},"doc://ai.deepar.DeepAR/documentation/DeepAR/TouchInfo/init(x:y:type:)":{"role":"symbol","title":"init(x:y:type:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"x"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"y"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TouchType","preciseIdentifier":"c:@E@TouchType"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/TouchInfo\/init(x:y:type:)","kind":"symbol","type":"topic","url":"\/documentation\/deepar\/touchinfo\/init(x:y:type:)"},"doc://ai.deepar.DeepAR/documentation/DeepAR":{"role":"collection","title":"DeepAR","abstract":[{"type":"text","text":"Build rich Augmented Reality experiences for iPhone, iPad and Mac."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR","kind":"symbol","type":"topic","url":"\/documentation\/deepar"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Structure"},{"op":"replace","path":"\/metadata\/title","value":"TouchInfo"},{"op":"replace","path":"\/metadata\/symbolKind","value":"struct"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"TouchInfo"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/TouchInfo\/x","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/TouchInfo\/y","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/TouchInfo\/type"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"typedef"},{"kind":"text","text":" "},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"TouchInfo"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1TouchInfo~1x\/title","value":"x"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1TouchInfo~1x\/fragments","value":[{"kind":"identifier","text":"x"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1TouchInfo~1y\/title","value":"y"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1TouchInfo~1y\/fragments","value":[{"kind":"identifier","text":"y"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1TouchInfo\/title","value":"TouchInfo"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1TouchInfo~1type\/title","value":"type"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1TouchInfo~1type\/fragments","value":[{"kind":"identifier","text":"type"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}