{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"VarType"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/deepar\/vartype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/deepar\/vartype"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/ai.deepar.DeepAR\/SQ","doc:\/\/ai.deepar.DeepAR\/SH","doc:\/\/ai.deepar.DeepAR\/SY","doc:\/\/ai.deepar.DeepAR\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/VarType","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Possible variable types."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"VarType"}],"title":"VarType","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@E@VarType","modules":[{"name":"DeepAR"}],"navigatorTitle":[{"kind":"identifier","text":"VarType"}]},"hierarchy":{"paths":[["doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/VarType\/BOOLEAN","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/VarType\/INT","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/VarType\/DOUBLE","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/VarType\/STRING"]},{"title":"Initializers","identifiers":["doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/VarType\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/VarType\/Equatable-Implementations","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/VarType\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://ai.deepar.DeepAR/documentation/DeepAR/VarType/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/VarType\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/deepar\/vartype\/equatable-implementations"},"doc://ai.deepar.DeepAR/documentation/DeepAR":{"role":"collection","title":"DeepAR","abstract":[{"type":"text","text":"Build rich Augmented Reality experiences for iPhone, iPad and Mac."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR","kind":"symbol","type":"topic","url":"\/documentation\/deepar"},"doc://ai.deepar.DeepAR/documentation/DeepAR/VarType/STRING":{"role":"symbol","title":"VarType.STRING","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"STRING"}],"abstract":[{"type":"text","text":"String variable type."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/VarType\/STRING","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STRING"}],"url":"\/documentation\/deepar\/vartype\/string"},"doc://ai.deepar.DeepAR/documentation/DeepAR/VarType/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/VarType\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/deepar\/vartype\/rawrepresentable-implementations"},"doc://ai.deepar.DeepAR/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/ai.deepar.DeepAR\/SH"},"doc://ai.deepar.DeepAR/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/ai.deepar.DeepAR\/s8SendableP"},"doc://ai.deepar.DeepAR/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/ai.deepar.DeepAR\/SY"},"doc://ai.deepar.DeepAR/documentation/DeepAR/VarType/DOUBLE":{"role":"symbol","title":"VarType.DOUBLE","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOUBLE"}],"abstract":[{"type":"text","text":"Double variable type."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/VarType\/DOUBLE","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DOUBLE"}],"url":"\/documentation\/deepar\/vartype\/double"},"doc://ai.deepar.DeepAR/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/ai.deepar.DeepAR\/SQ"},"doc://ai.deepar.DeepAR/documentation/DeepAR/VarType/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/VarType\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/deepar\/vartype\/init(rawvalue:)"},"doc://ai.deepar.DeepAR/documentation/DeepAR/VarType/INT":{"role":"symbol","title":"VarType.INT","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"INT"}],"abstract":[{"type":"text","text":"Integer variable type."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/VarType\/INT","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"INT"}],"url":"\/documentation\/deepar\/vartype\/int"},"doc://ai.deepar.DeepAR/documentation/DeepAR/VarType":{"role":"symbol","title":"VarType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"VarType"}],"abstract":[{"type":"text","text":"Possible variable types."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/VarType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"VarType"}],"url":"\/documentation\/deepar\/vartype"},"doc://ai.deepar.DeepAR/documentation/DeepAR/VarType/BOOLEAN":{"role":"symbol","title":"VarType.BOOLEAN","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"BOOLEAN"}],"abstract":[{"type":"text","text":"Bool variable type."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/VarType\/BOOLEAN","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BOOLEAN"}],"url":"\/documentation\/deepar\/vartype\/boolean"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"VarType"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"VarType"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"VarType"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/VarType\/BOOLEAN","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/VarType\/INT","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/VarType\/DOUBLE","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/VarType\/STRING"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"VarType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1VarType~1STRING\/title","value":"STRING"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1VarType~1STRING\/fragments","value":[{"kind":"identifier","text":"STRING"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1VarType~1DOUBLE\/title","value":"DOUBLE"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1VarType~1DOUBLE\/fragments","value":[{"kind":"identifier","text":"DOUBLE"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1VarType~1INT\/title","value":"INT"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1VarType~1INT\/fragments","value":[{"kind":"identifier","text":"INT"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1VarType\/title","value":"VarType"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1VarType\/fragments","value":[{"kind":"identifier","text":"VarType"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1VarType~1BOOLEAN\/title","value":"BOOLEAN"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1VarType~1BOOLEAN\/fragments","value":[{"kind":"identifier","text":"BOOLEAN"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}