{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Vector3"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/deepar\/vector3"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/deepar\/vector3"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/ai.deepar.DeepAR\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/Vector3","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"A three-dimensional float vector."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Vector3"}],"title":"Vector3","roleHeading":"Structure","role":"symbol","symbolKind":"struct","externalID":"c:@SA@Vector3","modules":[{"name":"DeepAR"}],"navigatorTitle":[{"kind":"identifier","text":"Vector3"}]},"hierarchy":{"paths":[["doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR"]]},"topicSections":[{"title":"Components","identifiers":["doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/Vector3\/x","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/Vector3\/y","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/Vector3\/z"]},{"title":"Initializers","identifiers":["doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/Vector3\/init()","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/Vector3\/init(x:y:z:)"]}],"references":{"doc://ai.deepar.DeepAR/documentation/DeepAR/Vector3/y":{"role":"symbol","title":"y","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"y"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"}],"abstract":[{"type":"text","text":"Y value."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/Vector3\/y","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"y"}],"url":"\/documentation\/deepar\/vector3\/y"},"doc://ai.deepar.DeepAR/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/ai.deepar.DeepAR\/s8SendableP"},"doc://ai.deepar.DeepAR/documentation/DeepAR/Vector3/z":{"role":"symbol","title":"z","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"z"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"}],"abstract":[{"type":"text","text":"Z value."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/Vector3\/z","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"z"}],"url":"\/documentation\/deepar\/vector3\/z"},"doc://ai.deepar.DeepAR/documentation/DeepAR/Vector3/x":{"role":"symbol","title":"x","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"x"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"}],"abstract":[{"type":"text","text":"X value."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/Vector3\/x","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"x"}],"url":"\/documentation\/deepar\/vector3\/x"},"doc://ai.deepar.DeepAR/documentation/DeepAR/Vector3":{"role":"symbol","title":"Vector3","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Vector3"}],"abstract":[{"type":"text","text":"A three-dimensional float vector."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/Vector3","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Vector3"}],"url":"\/documentation\/deepar\/vector3"},"doc://ai.deepar.DeepAR/documentation/DeepAR":{"role":"collection","title":"DeepAR","abstract":[{"type":"text","text":"Build rich Augmented Reality experiences for iPhone, iPad and Mac."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR","kind":"symbol","type":"topic","url":"\/documentation\/deepar"},"doc://ai.deepar.DeepAR/documentation/DeepAR/Vector3/init(x:y:z:)":{"role":"symbol","title":"init(x:y:z:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"x"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"},{"kind":"text","text":", "},{"kind":"externalParam","text":"y"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"},{"kind":"text","text":", "},{"kind":"externalParam","text":"z"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/Vector3\/init(x:y:z:)","kind":"symbol","type":"topic","url":"\/documentation\/deepar\/vector3\/init(x:y:z:)"},"doc://ai.deepar.DeepAR/documentation/DeepAR/Vector3/init()":{"role":"symbol","title":"init()","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/Vector3\/init()","kind":"symbol","type":"topic","url":"\/documentation\/deepar\/vector3\/init()"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Structure"},{"op":"replace","path":"\/metadata\/title","value":"Vector3"},{"op":"replace","path":"\/metadata\/symbolKind","value":"struct"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"Vector3"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Components","identifiers":["doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/Vector3\/x","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/Vector3\/y","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/Vector3\/z"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"typedef"},{"kind":"text","text":" "},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Vector3"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1Vector3~1y\/title","value":"y"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1Vector3~1y\/fragments","value":[{"kind":"identifier","text":"y"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1Vector3~1z\/title","value":"z"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1Vector3~1z\/fragments","value":[{"kind":"identifier","text":"z"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1Vector3~1x\/title","value":"x"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1Vector3~1x\/fragments","value":[{"kind":"identifier","text":"x"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1Vector3\/title","value":"Vector3"}],"traits":[{"interfaceLanguage":"occ"}]}]}