{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"faceData"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/FaceData","preciseIdentifier":"c:@SA@FaceData","text":"FaceData"},{"kind":"text","text":", "},{"kind":"typeIdentifier","identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/FaceData","preciseIdentifier":"c:@SA@FaceData","text":"FaceData"},{"kind":"text","text":", "},{"kind":"typeIdentifier","identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/FaceData","preciseIdentifier":"c:@SA@FaceData","text":"FaceData"},{"kind":"text","text":", "},{"kind":"typeIdentifier","identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/FaceData","preciseIdentifier":"c:@SA@FaceData","text":"FaceData"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/deepar\/multifacedata\/facedata"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/deepar\/multifacedata\/facedata"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/MultiFaceData\/faceData","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Array of face data for up to 4 detected faces."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"faceData"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"FaceData","preciseIdentifier":"c:@SA@FaceData"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"FaceData","preciseIdentifier":"c:@SA@FaceData"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"FaceData","preciseIdentifier":"c:@SA@FaceData"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"FaceData","preciseIdentifier":"c:@SA@FaceData"},{"kind":"text","text":")"}],"title":"faceData","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@SA@MultiFaceData@FI@faceData","modules":[{"name":"DeepAR"}],"navigatorTitle":[{"kind":"identifier","text":"faceData"}]},"hierarchy":{"paths":[["doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/MultiFaceData"]]},"references":{"doc://ai.deepar.DeepAR/documentation/DeepAR":{"role":"collection","title":"DeepAR","abstract":[{"type":"text","text":"Build rich Augmented Reality experiences for iPhone, iPad and Mac."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR","kind":"symbol","type":"topic","url":"\/documentation\/deepar"},"doc://ai.deepar.DeepAR/documentation/DeepAR/FaceData":{"role":"symbol","title":"FaceData","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceData"}],"abstract":[{"type":"text","text":"Represents data structure containing all the information available about the detected face."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/FaceData","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FaceData"}],"url":"\/documentation\/deepar\/facedata"},"doc://ai.deepar.DeepAR/documentation/DeepAR/MultiFaceData":{"role":"symbol","title":"MultiFaceData","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"MultiFaceData"}],"abstract":[{"type":"text","text":"Structure containing face data for up to 4 detected faces."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/MultiFaceData","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MultiFaceData"}],"url":"\/documentation\/deepar\/multifacedata"},"doc://ai.deepar.DeepAR/documentation/DeepAR/MultiFaceData/faceData":{"role":"symbol","title":"faceData","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"faceData"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"FaceData","preciseIdentifier":"c:@SA@FaceData"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"FaceData","preciseIdentifier":"c:@SA@FaceData"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"FaceData","preciseIdentifier":"c:@SA@FaceData"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"FaceData","preciseIdentifier":"c:@SA@FaceData"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Array of face data for up to 4 detected faces."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/MultiFaceData\/faceData","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"faceData"}],"url":"\/documentation\/deepar\/multifacedata\/facedata"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"faceData"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"faceData"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"typeIdentifier","identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/FaceData","preciseIdentifier":"c:@SA@FaceData","text":"FaceData"},{"kind":"text","text":" "},{"kind":"identifier","text":"faceData"},{"kind":"text","text":"["},{"kind":"number","text":"4"},{"kind":"text","text":"]"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1FaceData\/title","value":"FaceData"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1MultiFaceData\/title","value":"MultiFaceData"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1MultiFaceData~1faceData\/title","value":"faceData"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1MultiFaceData~1faceData\/fragments","value":[{"kind":"identifier","text":"faceData"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}