{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didInitialize"},{"kind":"text","text":"()"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/deepar\/deepardelegate\/didinitialize()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/deepar\/deepardelegate\/didinitialize()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepARDelegate\/didInitialize()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Called when the DeepAR engine initialization is complete."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didInitialize"},{"kind":"text","text":"()"}],"title":"didInitialize()","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(pl)DeepARDelegate(im)didInitialize","modules":[{"name":"DeepAR"}],"navigatorTitle":[{"kind":"identifier","text":"didInitialize"}]},"hierarchy":{"paths":[["doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepARDelegate"]]},"seeAlsoSections":[{"title":"DeepAR state","identifiers":["doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepARDelegate\/didFinishShutdown()"],"generated":true}],"references":{"doc://ai.deepar.DeepAR/documentation/DeepAR/DeepARDelegate":{"role":"symbol","title":"DeepARDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"DeepARDelegate"}],"abstract":[{"type":"text","text":"A delegate that is used to notify events from DeepAR to the consumer of the DeepAR SDK."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepARDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DeepARDelegate"}],"url":"\/documentation\/deepar\/deepardelegate"},"doc://ai.deepar.DeepAR/documentation/DeepAR/DeepARDelegate/didFinishShutdown()":{"navigatorTitle":[{"kind":"identifier","text":"didFinishShutdown"}],"role":"symbol","title":"didFinishShutdown()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didFinishShutdown"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"DeepAR has successfully shut down after the method shutdown call."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepARDelegate\/didFinishShutdown()","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/deepar\/deepardelegate\/didfinishshutdown()"},"doc://ai.deepar.DeepAR/documentation/DeepAR":{"role":"collection","title":"DeepAR","abstract":[{"type":"text","text":"Build rich Augmented Reality experiences for iPhone, iPad and Mac."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR","kind":"symbol","type":"topic","url":"\/documentation\/deepar"},"doc://ai.deepar.DeepAR/documentation/DeepAR/DeepARDelegate/didInitialize()":{"role":"symbol","title":"didInitialize()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didInitialize"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Called when the DeepAR engine initialization is complete."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepARDelegate\/didInitialize()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"didInitialize"}],"url":"\/documentation\/deepar\/deepardelegate\/didinitialize()"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"didInitialize"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didInitialize"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"DeepAR state","identifiers":["doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepARDelegate\/didFinishShutdown()"],"generated":true}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"didInitialize"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepARDelegate\/title","value":"DeepARDelegate"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepARDelegate\/fragments","value":[{"kind":"identifier","text":"DeepARDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepARDelegate~1didFinishShutdown()\/title","value":"didFinishShutdown"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepARDelegate~1didFinishShutdown()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didFinishShutdown"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepARDelegate~1didInitialize()\/title","value":"didInitialize"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepARDelegate~1didInitialize()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didInitialize"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}