{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didStartVideoRecording"},{"kind":"text","text":"()"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Called after the call to "},{"type":"reference","isActive":true,"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/startVideoRecording(withOutputWidth:outputHeight:)"},{"type":"text","text":" and other "},{"type":"codeVoice","code":"startVideoRecording"},{"type":"text","text":" methods."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/deepar\/deepardelegate\/didstartvideorecording()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/deepar\/deepardelegate\/didstartvideorecording()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepARDelegate\/didStartVideoRecording()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Called when DeepAR has started video recording."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"didStartVideoRecording"}],"role":"symbol","title":"didStartVideoRecording()","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didStartVideoRecording"},{"kind":"text","text":"()"}],"symbolKind":"method","externalID":"c:objc(pl)DeepARDelegate(im)didStartVideoRecording","required":true,"modules":[{"name":"DeepAR"}]},"hierarchy":{"paths":[["doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepARDelegate"]]},"seeAlsoSections":[{"title":"Image and video recording","identifiers":["doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepARDelegate\/didTakeScreenshot(_:)","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepARDelegate\/didFinishVideoRecording(_:)","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepARDelegate\/didFinishPreparingForVideoRecording()","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepARDelegate\/recordingFailedWithError(_:)"],"generated":true}],"references":{"doc://ai.deepar.DeepAR/documentation/DeepAR/DeepARDelegate/didStartVideoRecording()":{"navigatorTitle":[{"kind":"identifier","text":"didStartVideoRecording"}],"role":"symbol","title":"didStartVideoRecording()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didStartVideoRecording"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Called when DeepAR has started video recording."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepARDelegate\/didStartVideoRecording()","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/deepar\/deepardelegate\/didstartvideorecording()"},"doc://ai.deepar.DeepAR/documentation/DeepAR":{"role":"collection","title":"DeepAR","abstract":[{"type":"text","text":"Build rich Augmented Reality experiences for iPhone, iPad and Mac."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR","kind":"symbol","type":"topic","url":"\/documentation\/deepar"},"doc://ai.deepar.DeepAR/documentation/DeepAR/DeepARDelegate":{"role":"symbol","title":"DeepARDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"DeepARDelegate"}],"abstract":[{"type":"text","text":"A delegate that is used to notify events from DeepAR to the consumer of the DeepAR SDK."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepARDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DeepARDelegate"}],"url":"\/documentation\/deepar\/deepardelegate"},"doc://ai.deepar.DeepAR/documentation/DeepAR/DeepARDelegate/didFinishPreparingForVideoRecording()":{"navigatorTitle":[{"kind":"identifier","text":"didFinishPreparingForVideoRecording"}],"role":"symbol","title":"didFinishPreparingForVideoRecording()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didFinishPreparingForVideoRecording"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Called when the video recording preparation is finished."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepARDelegate\/didFinishPreparingForVideoRecording()","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/deepar\/deepardelegate\/didfinishpreparingforvideorecording()"},"doc://ai.deepar.DeepAR/documentation/DeepAR/DeepAR/startVideoRecording(withOutputWidth:outputHeight:)":{"role":"symbol","title":"startVideoRecording(withOutputWidth:outputHeight:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startVideoRecording"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withOutputWidth"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"outputHeight"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Starts video recording of the AR preview with the given resolution."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/startVideoRecording(withOutputWidth:outputHeight:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"startVideoRecordingWithOutputWidth:outputHeight:"}],"url":"\/documentation\/deepar\/deepar\/startvideorecording(withoutputwidth:outputheight:)"},"doc://ai.deepar.DeepAR/documentation/DeepAR/DeepARDelegate/didTakeScreenshot(_:)":{"navigatorTitle":[{"kind":"identifier","text":"didTakeScreenshot:"}],"role":"symbol","title":"didTakeScreenshot(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didTakeScreenshot"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":"!)"}],"abstract":[{"type":"text","text":"Called when DeepAR has finished taking a screenshot."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepARDelegate\/didTakeScreenshot(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/deepar\/deepardelegate\/didtakescreenshot(_:)"},"doc://ai.deepar.DeepAR/documentation/DeepAR/DeepARDelegate/recordingFailedWithError(_:)":{"navigatorTitle":[{"kind":"identifier","text":"recordingFailedWithError:"}],"role":"symbol","title":"recordingFailedWithError(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"recordingFailedWithError"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"!)"}],"abstract":[{"type":"text","text":"Called when an error has occurred during video recording."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepARDelegate\/recordingFailedWithError(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/deepar\/deepardelegate\/recordingfailedwitherror(_:)"},"doc://ai.deepar.DeepAR/documentation/DeepAR/DeepARDelegate/didFinishVideoRecording(_:)":{"role":"symbol","title":"didFinishVideoRecording(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didFinishVideoRecording"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!)"}],"abstract":[{"type":"text","text":"Called when the video recording is finished."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepARDelegate\/didFinishVideoRecording(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"didFinishVideoRecording:"}],"url":"\/documentation\/deepar\/deepardelegate\/didfinishvideorecording(_:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"didStartVideoRecording"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didStartVideoRecording"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"Image and video recording","identifiers":["doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepARDelegate\/didTakeScreenshot(_:)","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepARDelegate\/didFinishVideoRecording(_:)","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepARDelegate\/didFinishPreparingForVideoRecording()","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepARDelegate\/recordingFailedWithError(_:)"],"generated":true}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"didStartVideoRecording"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepARDelegate~1didStartVideoRecording()\/title","value":"didStartVideoRecording"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepARDelegate~1didStartVideoRecording()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didStartVideoRecording"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepARDelegate\/title","value":"DeepARDelegate"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepARDelegate\/fragments","value":[{"kind":"identifier","text":"DeepARDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepARDelegate~1didFinishPreparingForVideoRecording()\/title","value":"didFinishPreparingForVideoRecording"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepARDelegate~1didFinishPreparingForVideoRecording()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didFinishPreparingForVideoRecording"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR~1startVideoRecording(withOutputWidth:outputHeight:)\/title","value":"startVideoRecordingWithOutputWidth:outputHeight:"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR~1startVideoRecording(withOutputWidth:outputHeight:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"startVideoRecordingWithOutputWidth:outputHeight:"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepARDelegate~1didTakeScreenshot(_:)\/title","value":"didTakeScreenshot:"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepARDelegate~1didTakeScreenshot(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didTakeScreenshot:"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepARDelegate~1recordingFailedWithError(_:)\/title","value":"recordingFailedWithError:"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepARDelegate~1recordingFailedWithError(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"recordingFailedWithError:"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepARDelegate~1didFinishVideoRecording(_:)\/title","value":"didFinishVideoRecording:"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepARDelegate~1didFinishVideoRecording(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didFinishVideoRecording:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}