{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didSwitchEffect"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"slot"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!)"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"slot","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The slot name of the loaded effect."}]}]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"This delegate is called after call to "},{"type":"reference","isActive":true,"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/switchEffect(withSlot:path:)"},{"type":"text","text":" and other "},{"type":"codeVoice","code":"switchEffect"},{"type":"text","text":" methods."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/deepar\/deepardelegate\/didswitcheffect(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/deepar\/deepardelegate\/didswitcheffect(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepARDelegate\/didSwitchEffect(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Called when the effect is fully switched (loaded) and ready for preview."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"didSwitchEffect:"}],"role":"symbol","title":"didSwitchEffect(_:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didSwitchEffect"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!)"}],"symbolKind":"method","externalID":"c:objc(pl)DeepARDelegate(im)didSwitchEffect:","required":true,"modules":[{"name":"DeepAR"}]},"hierarchy":{"paths":[["doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepARDelegate"]]},"seeAlsoSections":[{"title":"Effects","identifiers":["doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepARDelegate\/animationTransitioned(toState:)"],"generated":true}],"references":{"doc://ai.deepar.DeepAR/documentation/DeepAR":{"role":"collection","title":"DeepAR","abstract":[{"type":"text","text":"Build rich Augmented Reality experiences for iPhone, iPad and Mac."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR","kind":"symbol","type":"topic","url":"\/documentation\/deepar"},"doc://ai.deepar.DeepAR/documentation/DeepAR/DeepARDelegate/didSwitchEffect(_:)":{"navigatorTitle":[{"kind":"identifier","text":"didSwitchEffect:"}],"role":"symbol","title":"didSwitchEffect(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didSwitchEffect"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!)"}],"abstract":[{"type":"text","text":"Called when the effect is fully switched (loaded) and ready for preview."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepARDelegate\/didSwitchEffect(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/deepar\/deepardelegate\/didswitcheffect(_:)"},"doc://ai.deepar.DeepAR/documentation/DeepAR/DeepARDelegate":{"role":"symbol","title":"DeepARDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"DeepARDelegate"}],"abstract":[{"type":"text","text":"A delegate that is used to notify events from DeepAR to the consumer of the DeepAR SDK."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepARDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DeepARDelegate"}],"url":"\/documentation\/deepar\/deepardelegate"},"doc://ai.deepar.DeepAR/documentation/DeepAR/DeepARDelegate/animationTransitioned(toState:)":{"role":"symbol","title":"animationTransitioned(toState:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"animationTransitioned"},{"kind":"text","text":"("},{"kind":"externalParam","text":"toState"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!)"}],"abstract":[{"type":"text","text":"Called when the conditions have been met for the animation to transition to the next state (e.g. mouth open, emotion detected etc.)."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepARDelegate\/animationTransitioned(toState:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"animationTransitionedToState:"}],"url":"\/documentation\/deepar\/deepardelegate\/animationtransitioned(tostate:)"},"doc://ai.deepar.DeepAR/documentation/DeepAR/DeepAR/switchEffect(withSlot:path:)":{"role":"symbol","title":"switchEffect(withSlot:path:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"switchEffect"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withSlot"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"path"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!)"}],"abstract":[{"type":"text","text":"Load a DeepAR effect file for AR preview."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/switchEffect(withSlot:path:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"switchEffectWithSlot:path:"}],"url":"\/documentation\/deepar\/deepar\/switcheffect(withslot:path:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"didSwitchEffect:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didSwitchEffect:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"Effects","identifiers":["doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepARDelegate\/animationTransitioned(toState:)"],"generated":true}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"didSwitchEffect:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"slot"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepARDelegate~1didSwitchEffect(_:)\/title","value":"didSwitchEffect:"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepARDelegate~1didSwitchEffect(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didSwitchEffect:"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepARDelegate\/title","value":"DeepARDelegate"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepARDelegate\/fragments","value":[{"kind":"identifier","text":"DeepARDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepARDelegate~1animationTransitioned(toState:)\/title","value":"animationTransitionedToState:"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepARDelegate~1animationTransitioned(toState:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"animationTransitionedToState:"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR~1switchEffect(withSlot:path:)\/title","value":"switchEffectWithSlot:path:"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR~1switchEffect(withSlot:path:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"switchEffectWithSlot:path:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}