{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"faceVisiblityDidChange"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"faceVisible"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"faceVisible","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"True if face is visible in the scene, false otherwise.."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/deepar\/deepardelegate\/facevisiblitydidchange(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/deepar\/deepardelegate\/facevisiblitydidchange(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepARDelegate\/faceVisiblityDidChange(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Called when DeepAR detects a new face or loses a face that has been tracked."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"faceVisiblityDidChange:"}],"role":"symbol","title":"faceVisiblityDidChange(_:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"faceVisiblityDidChange"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"c:objc(pl)DeepARDelegate(im)faceVisiblityDidChange:","required":true,"modules":[{"name":"DeepAR"}]},"hierarchy":{"paths":[["doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepARDelegate"]]},"seeAlsoSections":[{"title":"Face data","identifiers":["doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepARDelegate\/faceTracked(_:)","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepARDelegate\/number(ofFacesVisibleChanged:)"],"generated":true}],"references":{"doc://ai.deepar.DeepAR/documentation/DeepAR":{"role":"collection","title":"DeepAR","abstract":[{"type":"text","text":"Build rich Augmented Reality experiences for iPhone, iPad and Mac."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR","kind":"symbol","type":"topic","url":"\/documentation\/deepar"},"doc://ai.deepar.DeepAR/documentation/DeepAR/DeepARDelegate/number(ofFacesVisibleChanged:)":{"navigatorTitle":[{"kind":"identifier","text":"numberOfFacesVisibleChanged:"}],"role":"symbol","title":"number(ofFacesVisibleChanged:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"number"},{"kind":"text","text":"("},{"kind":"externalParam","text":"ofFacesVisibleChanged"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Whenever a face is detected or lost from the scene this method is called."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepARDelegate\/number(ofFacesVisibleChanged:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/deepar\/deepardelegate\/number(offacesvisiblechanged:)"},"doc://ai.deepar.DeepAR/documentation/DeepAR/DeepARDelegate":{"role":"symbol","title":"DeepARDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"DeepARDelegate"}],"abstract":[{"type":"text","text":"A delegate that is used to notify events from DeepAR to the consumer of the DeepAR SDK."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepARDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DeepARDelegate"}],"url":"\/documentation\/deepar\/deepardelegate"},"doc://ai.deepar.DeepAR/documentation/DeepAR/DeepARDelegate/faceTracked(_:)":{"navigatorTitle":[{"kind":"identifier","text":"faceTracked:"}],"role":"symbol","title":"faceTracked(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"faceTracked"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MultiFaceData","preciseIdentifier":"c:@SA@MultiFaceData"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Called on each frame where at least one face data is detected."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepARDelegate\/faceTracked(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/deepar\/deepardelegate\/facetracked(_:)"},"doc://ai.deepar.DeepAR/documentation/DeepAR/DeepARDelegate/faceVisiblityDidChange(_:)":{"navigatorTitle":[{"kind":"identifier","text":"faceVisiblityDidChange:"}],"role":"symbol","title":"faceVisiblityDidChange(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"faceVisiblityDidChange"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Called when DeepAR detects a new face or loses a face that has been tracked."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepARDelegate\/faceVisiblityDidChange(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/deepar\/deepardelegate\/facevisiblitydidchange(_:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"faceVisiblityDidChange:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"faceVisiblityDidChange:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"Face data","identifiers":["doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepARDelegate\/faceTracked(_:)","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepARDelegate\/number(ofFacesVisibleChanged:)"],"generated":true}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"faceVisiblityDidChange:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":")"},{"kind":"internalParam","text":"faceVisible"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepARDelegate~1number(ofFacesVisibleChanged:)\/title","value":"numberOfFacesVisibleChanged:"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepARDelegate~1number(ofFacesVisibleChanged:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"numberOfFacesVisibleChanged:"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepARDelegate\/title","value":"DeepARDelegate"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepARDelegate\/fragments","value":[{"kind":"identifier","text":"DeepARDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepARDelegate~1faceTracked(_:)\/title","value":"faceTracked:"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepARDelegate~1faceTracked(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"faceTracked:"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepARDelegate~1faceVisiblityDidChange(_:)\/title","value":"faceVisiblityDidChange:"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepARDelegate~1faceVisiblityDidChange(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"faceVisiblityDidChange:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}