{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onError"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withCode"},{"kind":"text","text":" "},{"kind":"internalParam","text":"code"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/ARErrorType","preciseIdentifier":"c:@E@ARErrorType","text":"ARErrorType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!)"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"code","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Error type."}]}]},{"name":"error","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Error message."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/deepar\/deepardelegate\/onerror(withcode:error:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/deepar\/deepardelegate\/onerror(withcode:error:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepARDelegate\/onError(withCode:error:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Called when an error has occurred within DeepAR SDK."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"onErrorWithCode:error:"}],"role":"symbol","title":"onError(withCode:error:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onError"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ARErrorType","preciseIdentifier":"c:@E@ARErrorType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!)"}],"symbolKind":"method","externalID":"c:objc(pl)DeepARDelegate(im)onErrorWithCode:error:","required":true,"modules":[{"name":"DeepAR"}]},"hierarchy":{"paths":[["doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepARDelegate"]]},"references":{"doc://ai.deepar.DeepAR/documentation/DeepAR":{"role":"collection","title":"DeepAR","abstract":[{"type":"text","text":"Build rich Augmented Reality experiences for iPhone, iPad and Mac."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR","kind":"symbol","type":"topic","url":"\/documentation\/deepar"},"doc://ai.deepar.DeepAR/documentation/DeepAR/DeepARDelegate":{"role":"symbol","title":"DeepARDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"DeepARDelegate"}],"abstract":[{"type":"text","text":"A delegate that is used to notify events from DeepAR to the consumer of the DeepAR SDK."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepARDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DeepARDelegate"}],"url":"\/documentation\/deepar\/deepardelegate"},"doc://ai.deepar.DeepAR/documentation/DeepAR/ARErrorType":{"role":"symbol","title":"ARErrorType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ARErrorType"}],"abstract":[{"type":"text","text":"DeepAR error types."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/ARErrorType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ARErrorType"}],"url":"\/documentation\/deepar\/arerrortype"},"doc://ai.deepar.DeepAR/documentation/DeepAR/DeepARDelegate/onError(withCode:error:)":{"navigatorTitle":[{"kind":"identifier","text":"onErrorWithCode:error:"}],"role":"symbol","title":"onError(withCode:error:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onError"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ARErrorType","preciseIdentifier":"c:@E@ARErrorType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!)"}],"abstract":[{"type":"text","text":"Called when an error has occurred within DeepAR SDK."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepARDelegate\/onError(withCode:error:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/deepar\/deepardelegate\/onerror(withcode:error:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"onErrorWithCode:error:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onErrorWithCode:error:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"onErrorWithCode:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/ARErrorType","preciseIdentifier":"c:@E@ARErrorType","text":"ARErrorType"},{"kind":"text","text":")"},{"kind":"internalParam","text":"code"},{"kind":"text","text":" "},{"kind":"identifier","text":"error:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"error"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepARDelegate\/title","value":"DeepARDelegate"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepARDelegate\/fragments","value":[{"kind":"identifier","text":"DeepARDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1ARErrorType\/title","value":"ARErrorType"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1ARErrorType\/fragments","value":[{"kind":"identifier","text":"ARErrorType"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepARDelegate~1onError(withCode:error:)\/title","value":"onErrorWithCode:error:"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepARDelegate~1onError(withCode:error:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onErrorWithCode:error:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}