{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"x"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"y"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/TouchType","preciseIdentifier":"c:@E@TouchType","text":"TouchType"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/deepar\/touchinfo\/init(x:y:type:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/TouchInfo\/init(x:y:type:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"x"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"y"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TouchType","preciseIdentifier":"c:@E@TouchType"},{"kind":"text","text":")"}],"title":"init(x:y:type:)","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"s:So9TouchInfoa1x1y4typeAB14CoreFoundation7CGFloatV_AHSo0A4TypeVtcfc","modules":[{"name":"DeepAR"}]},"hierarchy":{"paths":[["doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/TouchInfo"]]},"references":{"doc://ai.deepar.DeepAR/documentation/DeepAR":{"role":"collection","title":"DeepAR","abstract":[{"type":"text","text":"Build rich Augmented Reality experiences for iPhone, iPad and Mac."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR","kind":"symbol","type":"topic","url":"\/documentation\/deepar"},"doc://ai.deepar.DeepAR/documentation/DeepAR/TouchInfo/init(x:y:type:)":{"role":"symbol","title":"init(x:y:type:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"x"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"y"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TouchType","preciseIdentifier":"c:@E@TouchType"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/TouchInfo\/init(x:y:type:)","kind":"symbol","type":"topic","url":"\/documentation\/deepar\/touchinfo\/init(x:y:type:)"},"doc://ai.deepar.DeepAR/documentation/DeepAR/TouchInfo":{"role":"symbol","title":"TouchInfo","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"TouchInfo"}],"abstract":[{"type":"text","text":"Contains information about the current location and status of the started touch."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/TouchInfo","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TouchInfo"}],"url":"\/documentation\/deepar\/touchinfo"},"doc://ai.deepar.DeepAR/documentation/DeepAR/TouchType":{"role":"symbol","title":"TouchType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"TouchType"}],"abstract":[{"type":"text","text":"Possible types of an occurred touch."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/TouchType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TouchType"}],"url":"\/documentation\/deepar\/touchtype"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1TouchInfo\/title","value":"TouchInfo"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1TouchType\/title","value":"TouchType"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1TouchType\/fragments","value":[{"kind":"identifier","text":"TouchType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}