{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/TouchType","preciseIdentifier":"c:@E@TouchType","text":"TouchType"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/deepar\/touchinfo\/type"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/deepar\/touchinfo\/type"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/TouchInfo\/type","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The status, i.e., touch type, of the touch."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TouchType","preciseIdentifier":"c:@E@TouchType"}],"title":"type","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@SA@TouchInfo@FI@type","modules":[{"name":"DeepAR"}],"navigatorTitle":[{"kind":"identifier","text":"type"}]},"hierarchy":{"paths":[["doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/TouchInfo"]]},"seeAlsoSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/TouchInfo\/x","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/TouchInfo\/y"],"generated":true}],"references":{"doc://ai.deepar.DeepAR/documentation/DeepAR":{"role":"collection","title":"DeepAR","abstract":[{"type":"text","text":"Build rich Augmented Reality experiences for iPhone, iPad and Mac."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR","kind":"symbol","type":"topic","url":"\/documentation\/deepar"},"doc://ai.deepar.DeepAR/documentation/DeepAR/TouchInfo/type":{"role":"symbol","title":"type","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TouchType","preciseIdentifier":"c:@E@TouchType"}],"abstract":[{"type":"text","text":"The status, i.e., touch type, of the touch."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/TouchInfo\/type","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"type"}],"url":"\/documentation\/deepar\/touchinfo\/type"},"doc://ai.deepar.DeepAR/documentation/DeepAR/TouchInfo/x":{"role":"symbol","title":"x","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"x"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[{"type":"text","text":"Value of the x coordinate of the current touch location."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/TouchInfo\/x","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"x"}],"url":"\/documentation\/deepar\/touchinfo\/x"},"doc://ai.deepar.DeepAR/documentation/DeepAR/TouchInfo/y":{"role":"symbol","title":"y","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"y"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[{"type":"text","text":"Value of the y coordinate of the current touch location."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/TouchInfo\/y","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"y"}],"url":"\/documentation\/deepar\/touchinfo\/y"},"doc://ai.deepar.DeepAR/documentation/DeepAR/TouchType":{"role":"symbol","title":"TouchType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"TouchType"}],"abstract":[{"type":"text","text":"Possible types of an occurred touch."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/TouchType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TouchType"}],"url":"\/documentation\/deepar\/touchtype"},"doc://ai.deepar.DeepAR/documentation/DeepAR/TouchInfo":{"role":"symbol","title":"TouchInfo","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"TouchInfo"}],"abstract":[{"type":"text","text":"Contains information about the current location and status of the started touch."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/TouchInfo","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TouchInfo"}],"url":"\/documentation\/deepar\/touchinfo"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"type"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"type"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/TouchInfo\/x","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/TouchInfo\/y"],"generated":true}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"typeIdentifier","identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/TouchType","preciseIdentifier":"c:@E@TouchType","text":"TouchType"},{"kind":"text","text":" "},{"kind":"identifier","text":"type"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1TouchInfo~1type\/title","value":"type"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1TouchInfo~1type\/fragments","value":[{"kind":"identifier","text":"type"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1TouchInfo~1x\/title","value":"x"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1TouchInfo~1x\/fragments","value":[{"kind":"identifier","text":"x"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1TouchInfo~1y\/title","value":"y"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1TouchInfo~1y\/fragments","value":[{"kind":"identifier","text":"y"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1TouchType\/title","value":"TouchType"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1TouchType\/fragments","value":[{"kind":"identifier","text":"TouchType"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1TouchInfo\/title","value":"TouchInfo"}],"traits":[{"interfaceLanguage":"occ"}]}]}