{"primaryContentSections":[{"kind":"content","content":[{"anchor":"DeepAR-Apple-Framework-v530","level":4,"type":"heading","text":"DeepAR Apple Framework v5.3.0"},{"anchor":"Overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"DeepAR is an augmented reality SDK used to integrate advanced,"},{"type":"text","text":" "},{"type":"text","text":"Snapchat-like face lenses in iOS, Android and Web apps."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"DeepAR iOS framework supports:"}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Face filters and masks."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Glasses virtual try on."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Background replacement."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Background blur."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"AR mini-games."}]}]}]},{"anchor":"Documentation","level":2,"type":"heading","text":"Documentation"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Visit official DeepAR docs for iOS SDK "},{"type":"reference","isActive":true,"identifier":"https:\/\/docs.deepar.ai\/category\/deepar-sdk-for-ios"},{"type":"text","text":"."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"See the official example "},{"type":"reference","isActive":true,"identifier":"https:\/\/github.com\/DeepARSDK\/quickstart-ios-swift"},{"type":"text","text":"."}]}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/deepar"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/deepar"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Build rich Augmented Reality experiences for iPhone, iPad and Mac."}],"kind":"symbol","metadata":{"roleHeading":"Framework","externalID":"DeepAR","title":"DeepAR","symbolKind":"module","role":"collection","modules":[{"name":"DeepAR"}]},"hierarchy":{"paths":[[]]},"topicSections":[{"title":"Classes","identifiers":["doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/CameraController","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR"]},{"title":"Protocols","identifiers":["doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepARDelegate"]},{"title":"Structures","identifiers":["doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/FaceData","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/FaceTrackingInitParameters","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/MultiFaceData","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/RecordingConfig","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/TouchInfo","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/Vector3","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/Vector4"]},{"title":"Enumerations","identifiers":["doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/ARErrorType","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/OutputFormat","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/TouchType","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/VarType"]}],"references":{"doc://ai.deepar.DeepAR/documentation/DeepAR":{"role":"collection","title":"DeepAR","abstract":[{"type":"text","text":"Build rich Augmented Reality experiences for iPhone, iPad and Mac."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR","kind":"symbol","type":"topic","url":"\/documentation\/deepar"},"doc://ai.deepar.DeepAR/documentation/DeepAR/FaceData":{"role":"symbol","title":"FaceData","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceData"}],"abstract":[{"type":"text","text":"Represents data structure containing all the information available about the detected face."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/FaceData","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FaceData"}],"url":"\/documentation\/deepar\/facedata"},"doc://ai.deepar.DeepAR/documentation/DeepAR/DeepAR":{"role":"symbol","title":"DeepAR","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DeepAR"}],"abstract":[{"type":"text","text":"Main class for interacting with DeepAR engine."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DeepAR"}],"url":"\/documentation\/deepar\/deepar"},"doc://ai.deepar.DeepAR/documentation/DeepAR/TouchInfo":{"role":"symbol","title":"TouchInfo","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"TouchInfo"}],"abstract":[{"type":"text","text":"Contains information about the current location and status of the started touch."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/TouchInfo","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TouchInfo"}],"url":"\/documentation\/deepar\/touchinfo"},"doc://ai.deepar.DeepAR/documentation/DeepAR/FaceTrackingInitParameters":{"role":"symbol","title":"FaceTrackingInitParameters","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceTrackingInitParameters"}],"abstract":[{"type":"text","text":"Properties related to face tracking initialization."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/FaceTrackingInitParameters","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FaceTrackingInitParameters"}],"url":"\/documentation\/deepar\/facetrackinginitparameters"},"doc://ai.deepar.DeepAR/documentation/DeepAR/Vector4":{"role":"symbol","title":"Vector4","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Vector4"}],"abstract":[{"type":"text","text":"A four-dimensional float vector."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/Vector4","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Vector4"}],"url":"\/documentation\/deepar\/vector4"},"doc://ai.deepar.DeepAR/documentation/DeepAR/VarType":{"role":"symbol","title":"VarType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"VarType"}],"abstract":[{"type":"text","text":"Possible variable types."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/VarType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"VarType"}],"url":"\/documentation\/deepar\/vartype"},"doc://ai.deepar.DeepAR/documentation/DeepAR/MultiFaceData":{"role":"symbol","title":"MultiFaceData","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"MultiFaceData"}],"abstract":[{"type":"text","text":"Structure containing face data for up to 4 detected faces."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/MultiFaceData","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MultiFaceData"}],"url":"\/documentation\/deepar\/multifacedata"},"doc://ai.deepar.DeepAR/documentation/DeepAR/RecordingConfig":{"role":"symbol","title":"RecordingConfig","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"RecordingConfig"}],"abstract":[{"type":"text","text":"The video (and audio) recording configuration."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/RecordingConfig","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RecordingConfig"}],"url":"\/documentation\/deepar\/recordingconfig"},"https://github.com/DeepARSDK/quickstart-ios-swift":{"title":"here","titleInlineContent":[{"type":"text","text":"here"}],"type":"link","identifier":"https:\/\/github.com\/DeepARSDK\/quickstart-ios-swift","url":"https:\/\/github.com\/DeepARSDK\/quickstart-ios-swift"},"doc://ai.deepar.DeepAR/documentation/DeepAR/Vector3":{"role":"symbol","title":"Vector3","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Vector3"}],"abstract":[{"type":"text","text":"A three-dimensional float vector."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/Vector3","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Vector3"}],"url":"\/documentation\/deepar\/vector3"},"https://docs.deepar.ai/category/deepar-sdk-for-ios":{"title":"here","titleInlineContent":[{"type":"text","text":"here"}],"type":"link","identifier":"https:\/\/docs.deepar.ai\/category\/deepar-sdk-for-ios","url":"https:\/\/docs.deepar.ai\/category\/deepar-sdk-for-ios"},"doc://ai.deepar.DeepAR/documentation/DeepAR/ARErrorType":{"role":"symbol","title":"ARErrorType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ARErrorType"}],"abstract":[{"type":"text","text":"DeepAR error types."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/ARErrorType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ARErrorType"}],"url":"\/documentation\/deepar\/arerrortype"},"doc://ai.deepar.DeepAR/documentation/DeepAR/OutputFormat":{"role":"symbol","title":"OutputFormat","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"OutputFormat"}],"abstract":[{"type":"text","text":"Output color format."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/OutputFormat","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OutputFormat"}],"url":"\/documentation\/deepar\/outputformat"},"doc://ai.deepar.DeepAR/documentation/DeepAR/DeepARDelegate":{"role":"symbol","title":"DeepARDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"DeepARDelegate"}],"abstract":[{"type":"text","text":"A delegate that is used to notify events from DeepAR to the consumer of the DeepAR SDK."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepARDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DeepARDelegate"}],"url":"\/documentation\/deepar\/deepardelegate"},"doc://ai.deepar.DeepAR/documentation/DeepAR/CameraController":{"role":"symbol","title":"CameraController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CameraController"}],"abstract":[{"type":"text","text":"Helper class that wraps "},{"type":"reference","isActive":true,"identifier":"https:\/\/developer.apple.com\/documentation\/avfoundation"},{"type":"text","text":" "},{"type":"text","text":"to handle camera-related logic like starting camera preview, choosing resolution, front or back camera, and video orientation for DeepAR."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/CameraController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CameraController"}],"url":"\/documentation\/deepar\/cameracontroller"},"https://developer.apple.com/documentation/avfoundation":{"title":"AVFoundation","titleInlineContent":[{"type":"text","text":"AVFoundation"}],"type":"link","identifier":"https:\/\/developer.apple.com\/documentation\/avfoundation","url":"https:\/\/developer.apple.com\/documentation\/avfoundation"},"doc://ai.deepar.DeepAR/documentation/DeepAR/TouchType":{"role":"symbol","title":"TouchType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"TouchType"}],"abstract":[{"type":"text","text":"Possible types of an occurred touch."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/TouchType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TouchType"}],"url":"\/documentation\/deepar\/touchtype"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Classes","identifiers":["doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/CameraController","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR"]},{"title":"Protocols","identifiers":["doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepARDelegate"]},{"title":"Structures","identifiers":["doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/FaceData","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/FaceTrackingInitParameters","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/MultiFaceData","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/RecordingConfig","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/TouchInfo","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/Vector3","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/Vector4"]},{"title":"Enumerations","identifiers":["doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/ARErrorType","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/OutputFormat","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/TouchType","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/VarType"]}]},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1FaceData\/title","value":"FaceData"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR\/title","value":"DeepAR"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR\/fragments","value":[{"kind":"identifier","text":"DeepAR"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1TouchInfo\/title","value":"TouchInfo"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1FaceTrackingInitParameters\/title","value":"FaceTrackingInitParameters"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1Vector4\/title","value":"Vector4"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1VarType\/title","value":"VarType"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1VarType\/fragments","value":[{"kind":"identifier","text":"VarType"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1MultiFaceData\/title","value":"MultiFaceData"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1RecordingConfig\/title","value":"RecordingConfig"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1Vector3\/title","value":"Vector3"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1ARErrorType\/title","value":"ARErrorType"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1ARErrorType\/fragments","value":[{"kind":"identifier","text":"ARErrorType"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1OutputFormat\/title","value":"OutputFormat"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1OutputFormat\/fragments","value":[{"kind":"identifier","text":"OutputFormat"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepARDelegate\/title","value":"DeepARDelegate"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepARDelegate\/fragments","value":[{"kind":"identifier","text":"DeepARDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1CameraController\/title","value":"CameraController"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1CameraController\/fragments","value":[{"kind":"identifier","text":"CameraController"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1TouchType\/title","value":"TouchType"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1TouchType\/fragments","value":[{"kind":"identifier","text":"TouchType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}