{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"outputWidth"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/deepar\/recordingconfig\/outputwidth"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/deepar\/recordingconfig\/outputwidth"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/RecordingConfig\/outputWidth","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The output video width."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"outputWidth"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"title":"outputWidth","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@SA@RecordingConfig@FI@outputWidth","modules":[{"name":"DeepAR"}],"navigatorTitle":[{"kind":"identifier","text":"outputWidth"}]},"hierarchy":{"paths":[["doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/RecordingConfig"]]},"seeAlsoSections":[{"title":"Instance Properties","identifiers":["doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/RecordingConfig\/outputHeight","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/RecordingConfig\/subframe","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/RecordingConfig\/recordAudio","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/RecordingConfig\/videoCompressionProperties"],"generated":true}],"references":{"doc://ai.deepar.DeepAR/documentation/DeepAR/RecordingConfig/videoCompressionProperties":{"role":"symbol","title":"videoCompressionProperties","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"videoCompressionProperties"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Unmanaged","preciseIdentifier":"s:s9UnmanagedV"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"CFDictionary","preciseIdentifier":"c:@T@CFDictionaryRef"},{"kind":"text","text":">!"}],"abstract":[{"type":"text","text":"Video compression properties."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/RecordingConfig\/videoCompressionProperties","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"videoCompressionProperties"}],"url":"\/documentation\/deepar\/recordingconfig\/videocompressionproperties"},"doc://ai.deepar.DeepAR/documentation/DeepAR/RecordingConfig/subframe":{"role":"symbol","title":"subframe","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"subframe"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"}],"abstract":[{"type":"text","text":"The sub rectangle of the view  that you want to record in normalized coordinates (0.0 - 1.0)."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/RecordingConfig\/subframe","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"subframe"}],"url":"\/documentation\/deepar\/recordingconfig\/subframe"},"doc://ai.deepar.DeepAR/documentation/DeepAR":{"role":"collection","title":"DeepAR","abstract":[{"type":"text","text":"Build rich Augmented Reality experiences for iPhone, iPad and Mac."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR","kind":"symbol","type":"topic","url":"\/documentation\/deepar"},"doc://ai.deepar.DeepAR/documentation/DeepAR/RecordingConfig/outputWidth":{"role":"symbol","title":"outputWidth","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"outputWidth"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[{"type":"text","text":"The output video width."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/RecordingConfig\/outputWidth","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"outputWidth"}],"url":"\/documentation\/deepar\/recordingconfig\/outputwidth"},"doc://ai.deepar.DeepAR/documentation/DeepAR/RecordingConfig":{"role":"symbol","title":"RecordingConfig","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"RecordingConfig"}],"abstract":[{"type":"text","text":"The video (and audio) recording configuration."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/RecordingConfig","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RecordingConfig"}],"url":"\/documentation\/deepar\/recordingconfig"},"doc://ai.deepar.DeepAR/documentation/DeepAR/RecordingConfig/outputHeight":{"role":"symbol","title":"outputHeight","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"outputHeight"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[{"type":"text","text":"The output video height."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/RecordingConfig\/outputHeight","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"outputHeight"}],"url":"\/documentation\/deepar\/recordingconfig\/outputheight"},"doc://ai.deepar.DeepAR/documentation/DeepAR/RecordingConfig/recordAudio":{"role":"symbol","title":"recordAudio","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"recordAudio"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ObjCBool","preciseIdentifier":"s:10ObjectiveC8ObjCBoolV"}],"abstract":[{"type":"text","text":"Determine whether audio is recorded or not."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/RecordingConfig\/recordAudio","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"recordAudio"}],"url":"\/documentation\/deepar\/recordingconfig\/recordaudio"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"outputWidth"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"outputWidth"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/RecordingConfig\/outputHeight","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/RecordingConfig\/subframe","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/RecordingConfig\/recordAudio","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/RecordingConfig\/videoCompressionProperties"],"generated":true}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":" "},{"kind":"identifier","text":"outputWidth"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1RecordingConfig~1videoCompressionProperties\/title","value":"videoCompressionProperties"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1RecordingConfig~1videoCompressionProperties\/fragments","value":[{"kind":"identifier","text":"videoCompressionProperties"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1RecordingConfig~1subframe\/title","value":"subframe"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1RecordingConfig~1subframe\/fragments","value":[{"kind":"identifier","text":"subframe"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1RecordingConfig~1outputWidth\/title","value":"outputWidth"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1RecordingConfig~1outputWidth\/fragments","value":[{"kind":"identifier","text":"outputWidth"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1RecordingConfig\/title","value":"RecordingConfig"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1RecordingConfig~1outputHeight\/title","value":"outputHeight"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1RecordingConfig~1outputHeight\/fragments","value":[{"kind":"identifier","text":"outputHeight"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1RecordingConfig~1recordAudio\/title","value":"recordAudio"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1RecordingConfig~1recordAudio\/fragments","value":[{"kind":"identifier","text":"recordAudio"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}