{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"ABGR"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/deepar\/outputformat\/abgr"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/deepar\/outputformat\/abgr"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/OutputFormat\/ABGR","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Alpha, blue, green and red format."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"ABGR"}],"title":"OutputFormat.ABGR","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@OutputFormat@ABGR","modules":[{"name":"DeepAR"}],"navigatorTitle":[{"kind":"identifier","text":"ABGR"}]},"hierarchy":{"paths":[["doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/OutputFormat"]]},"seeAlsoSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/OutputFormat\/Undefined","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/OutputFormat\/RGBA","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/OutputFormat\/BGRA","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/OutputFormat\/ARGB","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/OutputFormat\/COUNT"],"generated":true}],"references":{"doc://ai.deepar.DeepAR/documentation/DeepAR":{"role":"collection","title":"DeepAR","abstract":[{"type":"text","text":"Build rich Augmented Reality experiences for iPhone, iPad and Mac."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR","kind":"symbol","type":"topic","url":"\/documentation\/deepar"},"doc://ai.deepar.DeepAR/documentation/DeepAR/OutputFormat/BGRA":{"role":"symbol","title":"OutputFormat.BGRA","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"BGRA"}],"abstract":[{"type":"text","text":"Blue, green, red and alpha format."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/OutputFormat\/BGRA","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BGRA"}],"url":"\/documentation\/deepar\/outputformat\/bgra"},"doc://ai.deepar.DeepAR/documentation/DeepAR/OutputFormat/COUNT":{"role":"symbol","title":"OutputFormat.COUNT","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"COUNT"}],"abstract":[{"type":"text","text":"Number of formats."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/OutputFormat\/COUNT","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"COUNT"}],"url":"\/documentation\/deepar\/outputformat\/count"},"doc://ai.deepar.DeepAR/documentation/DeepAR/OutputFormat":{"role":"symbol","title":"OutputFormat","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"OutputFormat"}],"abstract":[{"type":"text","text":"Output color format."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/OutputFormat","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OutputFormat"}],"url":"\/documentation\/deepar\/outputformat"},"doc://ai.deepar.DeepAR/documentation/DeepAR/OutputFormat/ARGB":{"role":"symbol","title":"OutputFormat.ARGB","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"ARGB"}],"abstract":[{"type":"text","text":"Alpha, red, green and blue format."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/OutputFormat\/ARGB","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ARGB"}],"url":"\/documentation\/deepar\/outputformat\/argb"},"doc://ai.deepar.DeepAR/documentation/DeepAR/OutputFormat/Undefined":{"role":"symbol","title":"OutputFormat.Undefined","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"Undefined"}],"abstract":[{"type":"text","text":"Undefined format."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/OutputFormat\/Undefined","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Undefined"}],"url":"\/documentation\/deepar\/outputformat\/undefined"},"doc://ai.deepar.DeepAR/documentation/DeepAR/OutputFormat/ABGR":{"role":"symbol","title":"OutputFormat.ABGR","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"ABGR"}],"abstract":[{"type":"text","text":"Alpha, blue, green and red format."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/OutputFormat\/ABGR","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ABGR"}],"url":"\/documentation\/deepar\/outputformat\/abgr"},"doc://ai.deepar.DeepAR/documentation/DeepAR/OutputFormat/RGBA":{"role":"symbol","title":"OutputFormat.RGBA","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"RGBA"}],"abstract":[{"type":"text","text":"Red, green, blue and alpha format."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/OutputFormat\/RGBA","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RGBA"}],"url":"\/documentation\/deepar\/outputformat\/rgba"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"ABGR"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ABGR"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/OutputFormat\/Undefined","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/OutputFormat\/RGBA","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/OutputFormat\/BGRA","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/OutputFormat\/ARGB","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/OutputFormat\/COUNT"],"generated":true}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"ABGR"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1OutputFormat~1BGRA\/title","value":"BGRA"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1OutputFormat~1BGRA\/fragments","value":[{"kind":"identifier","text":"BGRA"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1OutputFormat~1COUNT\/title","value":"COUNT"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1OutputFormat~1COUNT\/fragments","value":[{"kind":"identifier","text":"COUNT"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1OutputFormat\/title","value":"OutputFormat"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1OutputFormat\/fragments","value":[{"kind":"identifier","text":"OutputFormat"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1OutputFormat~1ARGB\/title","value":"ARGB"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1OutputFormat~1ARGB\/fragments","value":[{"kind":"identifier","text":"ARGB"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1OutputFormat~1Undefined\/title","value":"Undefined"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1OutputFormat~1Undefined\/fragments","value":[{"kind":"identifier","text":"Undefined"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1OutputFormat~1ABGR\/title","value":"ABGR"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1OutputFormat~1ABGR\/fragments","value":[{"kind":"identifier","text":"ABGR"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1OutputFormat~1RGBA\/title","value":"RGBA"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1OutputFormat~1RGBA\/fragments","value":[{"kind":"identifier","text":"RGBA"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}