{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"STRING"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/deepar\/vartype\/string"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/deepar\/vartype\/string"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/VarType\/STRING","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"String variable type."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"STRING"}],"title":"VarType.STRING","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@VarType@STRING","modules":[{"name":"DeepAR"}],"navigatorTitle":[{"kind":"identifier","text":"STRING"}]},"hierarchy":{"paths":[["doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/VarType"]]},"seeAlsoSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/VarType\/BOOLEAN","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/VarType\/INT","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/VarType\/DOUBLE"],"generated":true}],"references":{"doc://ai.deepar.DeepAR/documentation/DeepAR/VarType/STRING":{"role":"symbol","title":"VarType.STRING","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"STRING"}],"abstract":[{"type":"text","text":"String variable type."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/VarType\/STRING","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STRING"}],"url":"\/documentation\/deepar\/vartype\/string"},"doc://ai.deepar.DeepAR/documentation/DeepAR/VarType":{"role":"symbol","title":"VarType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"VarType"}],"abstract":[{"type":"text","text":"Possible variable types."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/VarType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"VarType"}],"url":"\/documentation\/deepar\/vartype"},"doc://ai.deepar.DeepAR/documentation/DeepAR":{"role":"collection","title":"DeepAR","abstract":[{"type":"text","text":"Build rich Augmented Reality experiences for iPhone, iPad and Mac."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR","kind":"symbol","type":"topic","url":"\/documentation\/deepar"},"doc://ai.deepar.DeepAR/documentation/DeepAR/VarType/BOOLEAN":{"role":"symbol","title":"VarType.BOOLEAN","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"BOOLEAN"}],"abstract":[{"type":"text","text":"Bool variable type."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/VarType\/BOOLEAN","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BOOLEAN"}],"url":"\/documentation\/deepar\/vartype\/boolean"},"doc://ai.deepar.DeepAR/documentation/DeepAR/VarType/INT":{"role":"symbol","title":"VarType.INT","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"INT"}],"abstract":[{"type":"text","text":"Integer variable type."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/VarType\/INT","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"INT"}],"url":"\/documentation\/deepar\/vartype\/int"},"doc://ai.deepar.DeepAR/documentation/DeepAR/VarType/DOUBLE":{"role":"symbol","title":"VarType.DOUBLE","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOUBLE"}],"abstract":[{"type":"text","text":"Double variable type."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/VarType\/DOUBLE","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DOUBLE"}],"url":"\/documentation\/deepar\/vartype\/double"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"STRING"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"STRING"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/VarType\/BOOLEAN","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/VarType\/INT","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/VarType\/DOUBLE"],"generated":true}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"STRING"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1VarType~1STRING\/title","value":"STRING"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1VarType~1STRING\/fragments","value":[{"kind":"identifier","text":"STRING"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1VarType\/title","value":"VarType"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1VarType\/fragments","value":[{"kind":"identifier","text":"VarType"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1VarType~1BOOLEAN\/title","value":"BOOLEAN"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1VarType~1BOOLEAN\/fragments","value":[{"kind":"identifier","text":"BOOLEAN"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1VarType~1INT\/title","value":"INT"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1VarType~1INT\/fragments","value":[{"kind":"identifier","text":"INT"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1VarType~1DOUBLE\/title","value":"DOUBLE"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1VarType~1DOUBLE\/fragments","value":[{"kind":"identifier","text":"DOUBLE"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}