{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"initializeEngineWithFaceTracking"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/deepar\/facetrackinginitparameters\/initializeenginewithfacetracking"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/deepar\/facetrackinginitparameters\/initializeenginewithfacetracking"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/FaceTrackingInitParameters\/initializeEngineWithFaceTracking","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Engine will initialize face tracking as soon as possible if true."},{"type":"text","text":" "},{"type":"text","text":"Else it will initialize when face tracking when it is needed. Eg. when loading effect that uses face tracking."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"initializeEngineWithFaceTracking"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"title":"initializeEngineWithFaceTracking","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@SA@FaceTrackingInitParameters@FI@initializeEngineWithFaceTracking","modules":[{"name":"DeepAR"}],"navigatorTitle":[{"kind":"identifier","text":"initializeEngineWithFaceTracking"}]},"hierarchy":{"paths":[["doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/FaceTrackingInitParameters"]]},"references":{"doc://ai.deepar.DeepAR/documentation/DeepAR/FaceTrackingInitParameters":{"role":"symbol","title":"FaceTrackingInitParameters","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceTrackingInitParameters"}],"abstract":[{"type":"text","text":"Properties related to face tracking initialization."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/FaceTrackingInitParameters","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FaceTrackingInitParameters"}],"url":"\/documentation\/deepar\/facetrackinginitparameters"},"doc://ai.deepar.DeepAR/documentation/DeepAR":{"role":"collection","title":"DeepAR","abstract":[{"type":"text","text":"Build rich Augmented Reality experiences for iPhone, iPad and Mac."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR","kind":"symbol","type":"topic","url":"\/documentation\/deepar"},"doc://ai.deepar.DeepAR/documentation/DeepAR/FaceTrackingInitParameters/initializeEngineWithFaceTracking":{"role":"symbol","title":"initializeEngineWithFaceTracking","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"initializeEngineWithFaceTracking"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Engine will initialize face tracking as soon as possible if true."},{"type":"text","text":" "},{"type":"text","text":"Else it will initialize when face tracking when it is needed. Eg. when loading effect that uses face tracking."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/FaceTrackingInitParameters\/initializeEngineWithFaceTracking","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initializeEngineWithFaceTracking"}],"url":"\/documentation\/deepar\/facetrackinginitparameters\/initializeenginewithfacetracking"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"initializeEngineWithFaceTracking"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"initializeEngineWithFaceTracking"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"typeIdentifier","text":"_Bool","preciseIdentifier":"c:b"},{"kind":"text","text":" "},{"kind":"identifier","text":"initializeEngineWithFaceTracking"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1FaceTrackingInitParameters\/title","value":"FaceTrackingInitParameters"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1FaceTrackingInitParameters~1initializeEngineWithFaceTracking\/title","value":"initializeEngineWithFaceTracking"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1FaceTrackingInitParameters~1initializeEngineWithFaceTracking\/fragments","value":[{"kind":"identifier","text":"initializeEngineWithFaceTracking"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}