{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"initializeFaceTrackingSynchronously"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/deepar\/facetrackinginitparameters\/initializefacetrackingsynchronously"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/deepar\/facetrackinginitparameters\/initializefacetrackingsynchronously"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/FaceTrackingInitParameters\/initializeFaceTrackingSynchronously","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"If true, face tracking will be initialized synchronously and will be blocking DeepAR rendering."},{"type":"text","text":" "},{"type":"text","text":"Else it will initialize in background thread and not block rendering."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"initializeFaceTrackingSynchronously"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"title":"initializeFaceTrackingSynchronously","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@SA@FaceTrackingInitParameters@FI@initializeFaceTrackingSynchronously","modules":[{"name":"DeepAR"}],"navigatorTitle":[{"kind":"identifier","text":"initializeFaceTrackingSynchronously"}]},"hierarchy":{"paths":[["doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/FaceTrackingInitParameters"]]},"references":{"doc://ai.deepar.DeepAR/documentation/DeepAR/FaceTrackingInitParameters/initializeFaceTrackingSynchronously":{"role":"symbol","title":"initializeFaceTrackingSynchronously","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"initializeFaceTrackingSynchronously"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"If true, face tracking will be initialized synchronously and will be blocking DeepAR rendering."},{"type":"text","text":" "},{"type":"text","text":"Else it will initialize in background thread and not block rendering."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/FaceTrackingInitParameters\/initializeFaceTrackingSynchronously","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initializeFaceTrackingSynchronously"}],"url":"\/documentation\/deepar\/facetrackinginitparameters\/initializefacetrackingsynchronously"},"doc://ai.deepar.DeepAR/documentation/DeepAR":{"role":"collection","title":"DeepAR","abstract":[{"type":"text","text":"Build rich Augmented Reality experiences for iPhone, iPad and Mac."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR","kind":"symbol","type":"topic","url":"\/documentation\/deepar"},"doc://ai.deepar.DeepAR/documentation/DeepAR/FaceTrackingInitParameters":{"role":"symbol","title":"FaceTrackingInitParameters","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceTrackingInitParameters"}],"abstract":[{"type":"text","text":"Properties related to face tracking initialization."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/FaceTrackingInitParameters","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FaceTrackingInitParameters"}],"url":"\/documentation\/deepar\/facetrackinginitparameters"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"initializeFaceTrackingSynchronously"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"initializeFaceTrackingSynchronously"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"typeIdentifier","text":"_Bool","preciseIdentifier":"c:b"},{"kind":"text","text":" "},{"kind":"identifier","text":"initializeFaceTrackingSynchronously"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1FaceTrackingInitParameters~1initializeFaceTrackingSynchronously\/title","value":"initializeFaceTrackingSynchronously"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1FaceTrackingInitParameters~1initializeFaceTrackingSynchronously\/fragments","value":[{"kind":"identifier","text":"initializeFaceTrackingSynchronously"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1FaceTrackingInitParameters\/title","value":"FaceTrackingInitParameters"}],"traits":[{"interfaceLanguage":"occ"}]}]}