{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"START"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/deepar\/touchtype\/start"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/deepar\/touchtype\/start"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/TouchType\/START","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Touch type that implies that a touch was started."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"START"}],"title":"TouchType.START","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@TouchType@START","modules":[{"name":"DeepAR"}],"navigatorTitle":[{"kind":"identifier","text":"START"}]},"hierarchy":{"paths":[["doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/TouchType"]]},"seeAlsoSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/TouchType\/MOVE","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/TouchType\/END"],"generated":true}],"references":{"doc://ai.deepar.DeepAR/documentation/DeepAR/TouchType":{"role":"symbol","title":"TouchType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"TouchType"}],"abstract":[{"type":"text","text":"Possible types of an occurred touch."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/TouchType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TouchType"}],"url":"\/documentation\/deepar\/touchtype"},"doc://ai.deepar.DeepAR/documentation/DeepAR/TouchType/MOVE":{"role":"symbol","title":"TouchType.MOVE","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"MOVE"}],"abstract":[{"type":"text","text":"Touch type that implies that a previously started touch changed."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/TouchType\/MOVE","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MOVE"}],"url":"\/documentation\/deepar\/touchtype\/move"},"doc://ai.deepar.DeepAR/documentation/DeepAR/TouchType/END":{"role":"symbol","title":"TouchType.END","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"END"}],"abstract":[{"type":"text","text":"Touch type that implies that a previously started touch ended."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/TouchType\/END","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"END"}],"url":"\/documentation\/deepar\/touchtype\/end"},"doc://ai.deepar.DeepAR/documentation/DeepAR":{"role":"collection","title":"DeepAR","abstract":[{"type":"text","text":"Build rich Augmented Reality experiences for iPhone, iPad and Mac."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR","kind":"symbol","type":"topic","url":"\/documentation\/deepar"},"doc://ai.deepar.DeepAR/documentation/DeepAR/TouchType/START":{"role":"symbol","title":"TouchType.START","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"START"}],"abstract":[{"type":"text","text":"Touch type that implies that a touch was started."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/TouchType\/START","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"START"}],"url":"\/documentation\/deepar\/touchtype\/start"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"START"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"START"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/TouchType\/MOVE","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/TouchType\/END"],"generated":true}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"START"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1TouchType\/title","value":"TouchType"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1TouchType\/fragments","value":[{"kind":"identifier","text":"TouchType"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1TouchType~1MOVE\/title","value":"MOVE"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1TouchType~1MOVE\/fragments","value":[{"kind":"identifier","text":"MOVE"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1TouchType~1END\/title","value":"END"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1TouchType~1END\/fragments","value":[{"kind":"identifier","text":"END"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1TouchType~1START\/title","value":"START"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1TouchType~1START\/fragments","value":[{"kind":"identifier","text":"START"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}