{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"checkMicrophonePermission"},{"kind":"text","text":"()"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"This will promt the user to give the microphone permission if the app does not have it."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/deepar\/cameracontroller\/checkmicrophonepermission()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/deepar\/cameracontroller\/checkmicrophonepermission()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/CameraController\/checkMicrophonePermission()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Checks microphone permissions."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"checkMicrophonePermission"},{"kind":"text","text":"()"}],"title":"checkMicrophonePermission()","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)CameraController(im)checkMicrophonePermission","modules":[{"name":"DeepAR"}],"navigatorTitle":[{"kind":"identifier","text":"checkMicrophonePermission"}]},"hierarchy":{"paths":[["doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/CameraController"]]},"seeAlsoSections":[{"title":"Check permissions","identifiers":["doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/CameraController\/checkCameraPermission()"],"generated":true}],"references":{"doc://ai.deepar.DeepAR/documentation/DeepAR/CameraController/checkCameraPermission()":{"role":"symbol","title":"checkCameraPermission()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"checkCameraPermission"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Checks camera permissions."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/CameraController\/checkCameraPermission()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"checkCameraPermission"}],"url":"\/documentation\/deepar\/cameracontroller\/checkcamerapermission()"},"doc://ai.deepar.DeepAR/documentation/DeepAR":{"role":"collection","title":"DeepAR","abstract":[{"type":"text","text":"Build rich Augmented Reality experiences for iPhone, iPad and Mac."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR","kind":"symbol","type":"topic","url":"\/documentation\/deepar"},"https://developer.apple.com/documentation/avfoundation":{"title":"AVFoundation","titleInlineContent":[{"type":"text","text":"AVFoundation"}],"type":"link","identifier":"https:\/\/developer.apple.com\/documentation\/avfoundation","url":"https:\/\/developer.apple.com\/documentation\/avfoundation"},"doc://ai.deepar.DeepAR/documentation/DeepAR/CameraController/checkMicrophonePermission()":{"role":"symbol","title":"checkMicrophonePermission()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"checkMicrophonePermission"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Checks microphone permissions."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/CameraController\/checkMicrophonePermission()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"checkMicrophonePermission"}],"url":"\/documentation\/deepar\/cameracontroller\/checkmicrophonepermission()"},"doc://ai.deepar.DeepAR/documentation/DeepAR/CameraController":{"role":"symbol","title":"CameraController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CameraController"}],"abstract":[{"type":"text","text":"Helper class that wraps "},{"type":"reference","isActive":true,"identifier":"https:\/\/developer.apple.com\/documentation\/avfoundation"},{"type":"text","text":" "},{"type":"text","text":"to handle camera-related logic like starting camera preview, choosing resolution, front or back camera, and video orientation for DeepAR."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/CameraController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CameraController"}],"url":"\/documentation\/deepar\/cameracontroller"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"checkMicrophonePermission"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"checkMicrophonePermission"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"Check permissions","identifiers":["doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/CameraController\/checkCameraPermission()"],"generated":true}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"checkMicrophonePermission"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1CameraController~1checkCameraPermission()\/title","value":"checkCameraPermission"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1CameraController~1checkCameraPermission()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"checkCameraPermission"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1CameraController~1checkMicrophonePermission()\/title","value":"checkMicrophonePermission"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1CameraController~1checkMicrophonePermission()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"checkMicrophonePermission"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1CameraController\/title","value":"CameraController"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1CameraController\/fragments","value":[{"kind":"identifier","text":"CameraController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}