{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"weak"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"deepAR"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR","preciseIdentifier":"c:objc(cs)DeepAR","text":"DeepAR"},{"kind":"text","text":"! { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"style":"important","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"This property should be set only once after the "},{"type":"codeVoice","code":"CameraController"},{"type":"text","text":" instance is created. See "},{"type":"reference","isActive":true,"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/CameraController\/init()"},{"type":"text","text":"."}]}],"type":"aside","name":"Important"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/deepar\/cameracontroller\/deepar"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/deepar\/cameracontroller\/deepar"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/CameraController\/deepAR","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The "},{"type":"reference","isActive":true,"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR"},{"type":"text","text":" instance."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"deepAR"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DeepAR","preciseIdentifier":"c:objc(cs)DeepAR"},{"kind":"text","text":"!"}],"title":"deepAR","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)CameraController(py)deepAR","modules":[{"name":"DeepAR"}],"navigatorTitle":[{"kind":"identifier","text":"deepAR"}]},"hierarchy":{"paths":[["doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/CameraController"]]},"references":{"doc://ai.deepar.DeepAR/documentation/DeepAR":{"role":"collection","title":"DeepAR","abstract":[{"type":"text","text":"Build rich Augmented Reality experiences for iPhone, iPad and Mac."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR","kind":"symbol","type":"topic","url":"\/documentation\/deepar"},"doc://ai.deepar.DeepAR/documentation/DeepAR/CameraController/init()":{"role":"symbol","title":"init()","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"!()"}],"abstract":[{"type":"text","text":"Initializes a new "},{"type":"codeVoice","code":"CameraController"},{"type":"text","text":" instance."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/CameraController\/init()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/deepar\/cameracontroller\/init()"},"https://developer.apple.com/documentation/avfoundation":{"title":"AVFoundation","titleInlineContent":[{"type":"text","text":"AVFoundation"}],"type":"link","identifier":"https:\/\/developer.apple.com\/documentation\/avfoundation","url":"https:\/\/developer.apple.com\/documentation\/avfoundation"},"doc://ai.deepar.DeepAR/documentation/DeepAR/DeepAR":{"role":"symbol","title":"DeepAR","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DeepAR"}],"abstract":[{"type":"text","text":"Main class for interacting with DeepAR engine."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DeepAR"}],"url":"\/documentation\/deepar\/deepar"},"doc://ai.deepar.DeepAR/documentation/DeepAR/CameraController":{"role":"symbol","title":"CameraController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CameraController"}],"abstract":[{"type":"text","text":"Helper class that wraps "},{"type":"reference","isActive":true,"identifier":"https:\/\/developer.apple.com\/documentation\/avfoundation"},{"type":"text","text":" "},{"type":"text","text":"to handle camera-related logic like starting camera preview, choosing resolution, front or back camera, and video orientation for DeepAR."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/CameraController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CameraController"}],"url":"\/documentation\/deepar\/cameracontroller"},"doc://ai.deepar.DeepAR/documentation/DeepAR/CameraController/deepAR":{"role":"symbol","title":"deepAR","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"deepAR"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DeepAR","preciseIdentifier":"c:objc(cs)DeepAR"},{"kind":"text","text":"!"}],"abstract":[{"type":"text","text":"The "},{"type":"reference","isActive":true,"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR"},{"type":"text","text":" instance."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/CameraController\/deepAR","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"deepAR"}],"url":"\/documentation\/deepar\/cameracontroller\/deepar"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"deepAR"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"deepAR"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"weak"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR","preciseIdentifier":"c:objc(cs)DeepAR","text":"DeepAR"},{"kind":"text","text":" * "},{"kind":"identifier","text":"deepAR"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1CameraController~1init()\/title","value":"init"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1CameraController~1init()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR\/title","value":"DeepAR"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR\/fragments","value":[{"kind":"identifier","text":"DeepAR"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1CameraController\/title","value":"CameraController"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1CameraController\/fragments","value":[{"kind":"identifier","text":"CameraController"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1CameraController~1deepAR\/title","value":"deepAR"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1CameraController~1deepAR\/fragments","value":[{"kind":"identifier","text":"deepAR"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}