{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startCamera"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withAudio"},{"kind":"text","text":" "},{"kind":"internalParam","text":"audio"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"audio","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"If set to true, camera won’t need to reinitialize when starting video recording."}]}]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Checks camera permissions and asks if none has been given. Additionally, checks for microphone permissions if specified."}]},{"style":"important","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Must be called if "},{"type":"reference","isActive":true,"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/startVideoRecording(withOutputWidth:outputHeight:subframe:videoCompressionProperties:recordAudio:)"},{"type":"text","text":" has been called with "},{"type":"codeVoice","code":"recordAudio"},{"type":"text","text":" parameter set to "},{"type":"codeVoice","code":"true"},{"type":"text","text":"."}]}],"type":"aside","name":"Important"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/deepar\/cameracontroller\/startcamera(withaudio:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/deepar\/cameracontroller\/startcamera(withaudio:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/CameraController\/startCamera(withAudio:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Starts camera preview. Allows to start microphone as well."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startCamera"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withAudio"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"title":"startCamera(withAudio:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)CameraController(im)startCameraWithAudio:","modules":[{"name":"DeepAR"}],"navigatorTitle":[{"kind":"identifier","text":"startCameraWithAudio:"}]},"hierarchy":{"paths":[["doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/CameraController"]]},"seeAlsoSections":[{"title":"Camera","identifiers":["doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/CameraController\/startCamera()","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/CameraController\/stopCamera()"],"generated":true}],"references":{"doc://ai.deepar.DeepAR/documentation/DeepAR":{"role":"collection","title":"DeepAR","abstract":[{"type":"text","text":"Build rich Augmented Reality experiences for iPhone, iPad and Mac."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR","kind":"symbol","type":"topic","url":"\/documentation\/deepar"},"https://developer.apple.com/documentation/avfoundation":{"title":"AVFoundation","titleInlineContent":[{"type":"text","text":"AVFoundation"}],"type":"link","identifier":"https:\/\/developer.apple.com\/documentation\/avfoundation","url":"https:\/\/developer.apple.com\/documentation\/avfoundation"},"doc://ai.deepar.DeepAR/documentation/DeepAR/DeepAR/startVideoRecording(withOutputWidth:outputHeight:subframe:videoCompressionProperties:recordAudio:)":{"role":"symbol","title":"startVideoRecording(withOutputWidth:outputHeight:subframe:videoCompressionProperties:recordAudio:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startVideoRecording"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withOutputWidth"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"outputHeight"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"subframe"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":", "},{"kind":"externalParam","text":"videoCompressionProperties"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]!, "},{"kind":"externalParam","text":"recordAudio"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Starts video recording of the AR preview with given resolution."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/startVideoRecording(withOutputWidth:outputHeight:subframe:videoCompressionProperties:recordAudio:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"startVideoRecordingWithOutputWidth:outputHeight:subframe:videoCompressionProperties:recordAudio:"}],"url":"\/documentation\/deepar\/deepar\/startvideorecording(withoutputwidth:outputheight:subframe:videocompressionproperties:recordaudio:)"},"doc://ai.deepar.DeepAR/documentation/DeepAR/CameraController/startCamera()":{"role":"symbol","title":"startCamera()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startCamera"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Starts camera preview."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/CameraController\/startCamera()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"startCamera"}],"url":"\/documentation\/deepar\/cameracontroller\/startcamera()"},"doc://ai.deepar.DeepAR/documentation/DeepAR/CameraController":{"role":"symbol","title":"CameraController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CameraController"}],"abstract":[{"type":"text","text":"Helper class that wraps "},{"type":"reference","isActive":true,"identifier":"https:\/\/developer.apple.com\/documentation\/avfoundation"},{"type":"text","text":" "},{"type":"text","text":"to handle camera-related logic like starting camera preview, choosing resolution, front or back camera, and video orientation for DeepAR."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/CameraController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CameraController"}],"url":"\/documentation\/deepar\/cameracontroller"},"doc://ai.deepar.DeepAR/documentation/DeepAR/CameraController/startCamera(withAudio:)":{"role":"symbol","title":"startCamera(withAudio:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startCamera"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withAudio"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Starts camera preview. Allows to start microphone as well."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/CameraController\/startCamera(withAudio:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"startCameraWithAudio:"}],"url":"\/documentation\/deepar\/cameracontroller\/startcamera(withaudio:)"},"doc://ai.deepar.DeepAR/documentation/DeepAR/CameraController/stopCamera()":{"role":"symbol","title":"stopCamera()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"stopCamera"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Stops camera preview."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/CameraController\/stopCamera()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"stopCamera"}],"url":"\/documentation\/deepar\/cameracontroller\/stopcamera()"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"startCameraWithAudio:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"startCameraWithAudio:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"Camera","identifiers":["doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/CameraController\/startCamera()","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/CameraController\/stopCamera()"],"generated":true}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"startCameraWithAudio:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":")"},{"kind":"internalParam","text":"audio"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR~1startVideoRecording(withOutputWidth:outputHeight:subframe:videoCompressionProperties:recordAudio:)\/title","value":"startVideoRecordingWithOutputWidth:outputHeight:subframe:videoCompressionProperties:recordAudio:"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR~1startVideoRecording(withOutputWidth:outputHeight:subframe:videoCompressionProperties:recordAudio:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"startVideoRecordingWithOutputWidth:outputHeight:subframe:videoCompressionProperties:recordAudio:"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1CameraController~1startCamera()\/title","value":"startCamera"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1CameraController~1startCamera()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"startCamera"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1CameraController\/title","value":"CameraController"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1CameraController\/fragments","value":[{"kind":"identifier","text":"CameraController"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1CameraController~1startCamera(withAudio:)\/title","value":"startCameraWithAudio:"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1CameraController~1startCamera(withAudio:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"startCameraWithAudio:"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1CameraController~1stopCamera()\/title","value":"stopCamera"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1CameraController~1stopCamera()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"stopCamera"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}