{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startCamera"},{"kind":"text","text":"()"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Checks camera permissions and asks if none has been given."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/deepar\/cameracontroller\/startcamera()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/deepar\/cameracontroller\/startcamera()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/CameraController\/startCamera()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Starts camera preview."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startCamera"},{"kind":"text","text":"()"}],"title":"startCamera()","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)CameraController(im)startCamera","modules":[{"name":"DeepAR"}],"navigatorTitle":[{"kind":"identifier","text":"startCamera"}]},"hierarchy":{"paths":[["doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/CameraController"]]},"seeAlsoSections":[{"title":"Camera","identifiers":["doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/CameraController\/startCamera(withAudio:)","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/CameraController\/stopCamera()"],"generated":true}],"references":{"doc://ai.deepar.DeepAR/documentation/DeepAR/CameraController/startCamera(withAudio:)":{"role":"symbol","title":"startCamera(withAudio:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startCamera"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withAudio"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Starts camera preview. Allows to start microphone as well."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/CameraController\/startCamera(withAudio:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"startCameraWithAudio:"}],"url":"\/documentation\/deepar\/cameracontroller\/startcamera(withaudio:)"},"doc://ai.deepar.DeepAR/documentation/DeepAR":{"role":"collection","title":"DeepAR","abstract":[{"type":"text","text":"Build rich Augmented Reality experiences for iPhone, iPad and Mac."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR","kind":"symbol","type":"topic","url":"\/documentation\/deepar"},"doc://ai.deepar.DeepAR/documentation/DeepAR/CameraController/startCamera()":{"role":"symbol","title":"startCamera()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startCamera"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Starts camera preview."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/CameraController\/startCamera()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"startCamera"}],"url":"\/documentation\/deepar\/cameracontroller\/startcamera()"},"doc://ai.deepar.DeepAR/documentation/DeepAR/CameraController/stopCamera()":{"role":"symbol","title":"stopCamera()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"stopCamera"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Stops camera preview."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/CameraController\/stopCamera()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"stopCamera"}],"url":"\/documentation\/deepar\/cameracontroller\/stopcamera()"},"https://developer.apple.com/documentation/avfoundation":{"title":"AVFoundation","titleInlineContent":[{"type":"text","text":"AVFoundation"}],"type":"link","identifier":"https:\/\/developer.apple.com\/documentation\/avfoundation","url":"https:\/\/developer.apple.com\/documentation\/avfoundation"},"doc://ai.deepar.DeepAR/documentation/DeepAR/CameraController":{"role":"symbol","title":"CameraController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CameraController"}],"abstract":[{"type":"text","text":"Helper class that wraps "},{"type":"reference","isActive":true,"identifier":"https:\/\/developer.apple.com\/documentation\/avfoundation"},{"type":"text","text":" "},{"type":"text","text":"to handle camera-related logic like starting camera preview, choosing resolution, front or back camera, and video orientation for DeepAR."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/CameraController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CameraController"}],"url":"\/documentation\/deepar\/cameracontroller"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"startCamera"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"startCamera"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"Camera","identifiers":["doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/CameraController\/startCamera(withAudio:)","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/CameraController\/stopCamera()"],"generated":true}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"startCamera"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1CameraController~1startCamera(withAudio:)\/title","value":"startCameraWithAudio:"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1CameraController~1startCamera(withAudio:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"startCameraWithAudio:"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1CameraController~1startCamera()\/title","value":"startCamera"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1CameraController~1startCamera()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"startCamera"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1CameraController~1stopCamera()\/title","value":"stopCamera"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1CameraController~1stopCamera()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"stopCamera"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1CameraController\/title","value":"CameraController"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1CameraController\/fragments","value":[{"kind":"identifier","text":"CameraController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}