{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startAudio"},{"kind":"text","text":"()"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Checks permissions and asks if none has been given."}]},{"style":"important","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Must be called if "},{"type":"reference","isActive":true,"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/startVideoRecording(withOutputWidth:outputHeight:subframe:videoCompressionProperties:recordAudio:)"},{"type":"text","text":" has been called with "},{"type":"codeVoice","code":"recordAudio"},{"type":"text","text":" parameter set to "},{"type":"codeVoice","code":"true"},{"type":"text","text":"."}]}],"type":"aside","name":"Important"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/deepar\/cameracontroller\/startaudio()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/deepar\/cameracontroller\/startaudio()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/CameraController\/startAudio()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Starts capturing audio samples."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startAudio"},{"kind":"text","text":"()"}],"title":"startAudio()","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)CameraController(im)startAudio","modules":[{"name":"DeepAR"}],"navigatorTitle":[{"kind":"identifier","text":"startAudio"}]},"hierarchy":{"paths":[["doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/CameraController"]]},"seeAlsoSections":[{"title":"Audio","identifiers":["doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/CameraController\/stopAudio()"],"generated":true}],"references":{"doc://ai.deepar.DeepAR/documentation/DeepAR":{"role":"collection","title":"DeepAR","abstract":[{"type":"text","text":"Build rich Augmented Reality experiences for iPhone, iPad and Mac."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR","kind":"symbol","type":"topic","url":"\/documentation\/deepar"},"doc://ai.deepar.DeepAR/documentation/DeepAR/CameraController/stopAudio()":{"role":"symbol","title":"stopAudio()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"stopAudio"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Stops capturing audio samples."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/CameraController\/stopAudio()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"stopAudio"}],"url":"\/documentation\/deepar\/cameracontroller\/stopaudio()"},"doc://ai.deepar.DeepAR/documentation/DeepAR/DeepAR/startVideoRecording(withOutputWidth:outputHeight:subframe:videoCompressionProperties:recordAudio:)":{"role":"symbol","title":"startVideoRecording(withOutputWidth:outputHeight:subframe:videoCompressionProperties:recordAudio:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startVideoRecording"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withOutputWidth"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"outputHeight"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"subframe"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":", "},{"kind":"externalParam","text":"videoCompressionProperties"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]!, "},{"kind":"externalParam","text":"recordAudio"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Starts video recording of the AR preview with given resolution."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/startVideoRecording(withOutputWidth:outputHeight:subframe:videoCompressionProperties:recordAudio:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"startVideoRecordingWithOutputWidth:outputHeight:subframe:videoCompressionProperties:recordAudio:"}],"url":"\/documentation\/deepar\/deepar\/startvideorecording(withoutputwidth:outputheight:subframe:videocompressionproperties:recordaudio:)"},"https://developer.apple.com/documentation/avfoundation":{"title":"AVFoundation","titleInlineContent":[{"type":"text","text":"AVFoundation"}],"type":"link","identifier":"https:\/\/developer.apple.com\/documentation\/avfoundation","url":"https:\/\/developer.apple.com\/documentation\/avfoundation"},"doc://ai.deepar.DeepAR/documentation/DeepAR/CameraController/startAudio()":{"role":"symbol","title":"startAudio()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startAudio"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Starts capturing audio samples."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/CameraController\/startAudio()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"startAudio"}],"url":"\/documentation\/deepar\/cameracontroller\/startaudio()"},"doc://ai.deepar.DeepAR/documentation/DeepAR/CameraController":{"role":"symbol","title":"CameraController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CameraController"}],"abstract":[{"type":"text","text":"Helper class that wraps "},{"type":"reference","isActive":true,"identifier":"https:\/\/developer.apple.com\/documentation\/avfoundation"},{"type":"text","text":" "},{"type":"text","text":"to handle camera-related logic like starting camera preview, choosing resolution, front or back camera, and video orientation for DeepAR."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/CameraController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CameraController"}],"url":"\/documentation\/deepar\/cameracontroller"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"startAudio"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"startAudio"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"Audio","identifiers":["doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/CameraController\/stopAudio()"],"generated":true}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"startAudio"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1CameraController~1stopAudio()\/title","value":"stopAudio"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1CameraController~1stopAudio()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"stopAudio"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR~1startVideoRecording(withOutputWidth:outputHeight:subframe:videoCompressionProperties:recordAudio:)\/title","value":"startVideoRecordingWithOutputWidth:outputHeight:subframe:videoCompressionProperties:recordAudio:"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR~1startVideoRecording(withOutputWidth:outputHeight:subframe:videoCompressionProperties:recordAudio:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"startVideoRecordingWithOutputWidth:outputHeight:subframe:videoCompressionProperties:recordAudio:"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1CameraController~1startAudio()\/title","value":"startAudio"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1CameraController~1startAudio()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"startAudio"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1CameraController\/title","value":"CameraController"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1CameraController\/fragments","value":[{"kind":"identifier","text":"CameraController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}