{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"changeLiveMode"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"liveMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"liveMode","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Enable or disable live mode."}]}]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"If called with true value, DeepAR will expect a continuous flow of new frames and it will optimize its inner processes for such workload."},{"type":"text","text":" "},{"type":"text","text":"An example of this is the typical use case of processing the frames from the camera stream."},{"type":"text","text":" "},{"type":"text","text":"If called with false it will optimize for preserving resources and memory by pausing the rendering after each processed frame."},{"type":"text","text":" "},{"type":"text","text":"A typical use case for this is when the user needs to process just one image. In that case, the user will feed the image to DeepAR by calling "},{"type":"reference","isActive":true,"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/processFrame(_:mirror:)"},{"type":"text","text":" "},{"type":"text","text":"or similar method, and DeepAR would process it and stop rendering until a new frame is received. If we did so when the DeepAR is in live mode,"},{"type":"text","text":" "},{"type":"text","text":"it would process the same frame over and over again without ever stopping the rendering process, thus wasting processing time."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/deepar\/deepar\/changelivemode(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/deepar\/deepar\/changelivemode(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/changeLiveMode(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"An optimization method and it allows the user to indicate the DeepAR in which mode it should operate."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"changeLiveMode"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"title":"changeLiveMode(_:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)DeepAR(im)changeLiveMode:","modules":[{"name":"DeepAR"}],"navigatorTitle":[{"kind":"identifier","text":"changeLiveMode:"}]},"hierarchy":{"paths":[["doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR"]]},"seeAlsoSections":[{"title":"Rendering","identifiers":["doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/setRenderingResolutionWithWidth(_:height:)","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/resume()","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/pause()","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/switchToRenderingToView(withFrame:)","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/switchToRenderingOffscreen(withWidth:height:)"],"generated":true}],"references":{"doc://ai.deepar.DeepAR/documentation/DeepAR/DeepAR/switchToRenderingOffscreen(withWidth:height:)":{"role":"symbol","title":"switchToRenderingOffscreen(withWidth:height:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"switchToRenderingOffscreen"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withWidth"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"height"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Starts rendering in the off-screen buffer."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/switchToRenderingOffscreen(withWidth:height:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"switchToRenderingOffscreenWithWidth:height:"}],"url":"\/documentation\/deepar\/deepar\/switchtorenderingoffscreen(withwidth:height:)"},"doc://ai.deepar.DeepAR/documentation/DeepAR/DeepAR/setRenderingResolutionWithWidth(_:height:)":{"role":"symbol","title":"setRenderingResolutionWithWidth(_:height:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setRenderingResolutionWithWidth"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"height"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Changes the output resolution of the processed frames."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/setRenderingResolutionWithWidth(_:height:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setRenderingResolutionWithWidth:height:"}],"url":"\/documentation\/deepar\/deepar\/setrenderingresolutionwithwidth(_:height:)"},"doc://ai.deepar.DeepAR/documentation/DeepAR/DeepAR/processFrame(_:mirror:)":{"role":"symbol","title":"processFrame(_:mirror:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"processFrame"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CVPixelBuffer","preciseIdentifier":"c:@T@CVPixelBufferRef"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"mirror"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Feed frame to DeepAR for processing."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/processFrame(_:mirror:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"processFrame:mirror:"}],"url":"\/documentation\/deepar\/deepar\/processframe(_:mirror:)"},"doc://ai.deepar.DeepAR/documentation/DeepAR/DeepAR/resume()":{"role":"symbol","title":"resume()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"resume"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Resumes the rendering if it was previously paused, otherwise doesn’t do anything."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/resume()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"resume"}],"url":"\/documentation\/deepar\/deepar\/resume()"},"doc://ai.deepar.DeepAR/documentation/DeepAR":{"role":"collection","title":"DeepAR","abstract":[{"type":"text","text":"Build rich Augmented Reality experiences for iPhone, iPad and Mac."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR","kind":"symbol","type":"topic","url":"\/documentation\/deepar"},"doc://ai.deepar.DeepAR/documentation/DeepAR/DeepAR/changeLiveMode(_:)":{"role":"symbol","title":"changeLiveMode(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"changeLiveMode"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"An optimization method and it allows the user to indicate the DeepAR in which mode it should operate."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/changeLiveMode(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"changeLiveMode:"}],"url":"\/documentation\/deepar\/deepar\/changelivemode(_:)"},"doc://ai.deepar.DeepAR/documentation/DeepAR/DeepAR/switchToRenderingToView(withFrame:)":{"role":"symbol","title":"switchToRenderingToView(withFrame:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"switchToRenderingToView"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withFrame"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":"!"}],"abstract":[{"type":"text","text":"Switch DeepAR rendering to "},{"type":"codeVoice","code":"UIView"},{"type":"text","text":"."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/switchToRenderingToView(withFrame:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"switchToRenderingToViewWithFrame:"}],"url":"\/documentation\/deepar\/deepar\/switchtorenderingtoview(withframe:)"},"doc://ai.deepar.DeepAR/documentation/DeepAR/DeepAR/pause()":{"role":"symbol","title":"pause()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"pause"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Pauses the rendering."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/pause()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"pause"}],"url":"\/documentation\/deepar\/deepar\/pause()"},"doc://ai.deepar.DeepAR/documentation/DeepAR/DeepAR":{"role":"symbol","title":"DeepAR","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DeepAR"}],"abstract":[{"type":"text","text":"Main class for interacting with DeepAR engine."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DeepAR"}],"url":"\/documentation\/deepar\/deepar"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"changeLiveMode:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"changeLiveMode:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"Rendering","identifiers":["doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/setRenderingResolutionWithWidth(_:height:)","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/resume()","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/pause()","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/switchToRenderingToView(withFrame:)","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/switchToRenderingOffscreen(withWidth:height:)"],"generated":true}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"changeLiveMode:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":")"},{"kind":"internalParam","text":"liveMode"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR~1switchToRenderingOffscreen(withWidth:height:)\/title","value":"switchToRenderingOffscreenWithWidth:height:"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR~1switchToRenderingOffscreen(withWidth:height:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"switchToRenderingOffscreenWithWidth:height:"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR~1setRenderingResolutionWithWidth(_:height:)\/title","value":"setRenderingResolutionWithWidth:height:"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR~1setRenderingResolutionWithWidth(_:height:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setRenderingResolutionWithWidth:height:"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR~1processFrame(_:mirror:)\/title","value":"processFrame:mirror:"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR~1processFrame(_:mirror:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"processFrame:mirror:"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR~1resume()\/title","value":"resume"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR~1resume()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"resume"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR~1changeLiveMode(_:)\/title","value":"changeLiveMode:"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR~1changeLiveMode(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"changeLiveMode:"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR~1switchToRenderingToView(withFrame:)\/title","value":"switchToRenderingToViewWithFrame:"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR~1switchToRenderingToView(withFrame:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"switchToRenderingToViewWithFrame:"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR~1pause()\/title","value":"pause"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR~1pause()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"pause"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR\/title","value":"DeepAR"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR\/fragments","value":[{"kind":"identifier","text":"DeepAR"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}