{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"changeParameter"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"gameObject"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"component"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"parameter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"vector3Value"},{"kind":"text","text":" "},{"kind":"internalParam","text":"value"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/Vector3","preciseIdentifier":"c:@SA@Vector3","text":"Vector3"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"gameObject","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The name of the node. If multiple nodes share the same name, only the first one will be affected."}]}]},{"name":"component","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The name of the component. If the name of the component is null or an empty string, the node itself will be affected."}]}]},{"name":"parameter","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The name of the parameter."}]}]},{"name":"value","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"New parameter value."}]}]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"For more details about changeParameter API read our article "},{"type":"reference","isActive":true,"identifier":"https:\/\/docs.deepar.ai\/deepar-sdk\/tutorials\/change-parameter"},{"type":"text","text":"."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/deepar\/deepar\/changeparameter(_:component:parameter:vector3value:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/deepar\/deepar\/changeparameter(_:component:parameter:vector3value:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/changeParameter(_:component:parameter:vector3Value:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Changes a node or component 3D vector parameter."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"changeParameter"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"component"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"parameter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"vector3Value"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Vector3","preciseIdentifier":"c:@SA@Vector3"},{"kind":"text","text":")"}],"title":"changeParameter(_:component:parameter:vector3Value:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)DeepAR(im)changeParameter:component:parameter:vector3Value:","modules":[{"name":"DeepAR"}],"navigatorTitle":[{"kind":"identifier","text":"changeParameter:component:parameter:vector3Value:"}]},"hierarchy":{"paths":[["doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR"]]},"seeAlsoSections":[{"title":"Change AR effect parameters in runtime","identifiers":["doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/changeParameter(_:component:parameter:boolValue:)","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/changeParameter(_:component:parameter:floatValue:)","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/changeParameter(_:component:parameter:stringValue:)","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/changeParameter(_:component:parameter:vectorValue:)","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/changeParameter(_:component:parameter:image:)"],"generated":true}],"references":{"doc://ai.deepar.DeepAR/documentation/DeepAR/DeepAR/changeParameter(_:component:parameter:vectorValue:)":{"role":"symbol","title":"changeParameter(_:component:parameter:vectorValue:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"changeParameter"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"component"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"parameter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"vectorValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Vector4","preciseIdentifier":"c:@SA@Vector4"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Changes a node or component 4D vector parameter."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/changeParameter(_:component:parameter:vectorValue:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"changeParameter:component:parameter:vectorValue:"}],"url":"\/documentation\/deepar\/deepar\/changeparameter(_:component:parameter:vectorvalue:)"},"doc://ai.deepar.DeepAR/documentation/DeepAR":{"role":"collection","title":"DeepAR","abstract":[{"type":"text","text":"Build rich Augmented Reality experiences for iPhone, iPad and Mac."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR","kind":"symbol","type":"topic","url":"\/documentation\/deepar"},"https://docs.deepar.ai/deepar-sdk/tutorials/change-parameter":{"title":"here","titleInlineContent":[{"type":"text","text":"here"}],"type":"link","identifier":"https:\/\/docs.deepar.ai\/deepar-sdk\/tutorials\/change-parameter","url":"https:\/\/docs.deepar.ai\/deepar-sdk\/tutorials\/change-parameter"},"doc://ai.deepar.DeepAR/documentation/DeepAR/DeepAR/changeParameter(_:component:parameter:boolValue:)":{"role":"symbol","title":"changeParameter(_:component:parameter:boolValue:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"changeParameter"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"component"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"parameter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"boolValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Changes a node or component boolean parameter."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/changeParameter(_:component:parameter:boolValue:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"changeParameter:component:parameter:boolValue:"}],"url":"\/documentation\/deepar\/deepar\/changeparameter(_:component:parameter:boolvalue:)"},"doc://ai.deepar.DeepAR/documentation/DeepAR/DeepAR/changeParameter(_:component:parameter:image:)":{"role":"symbol","title":"changeParameter(_:component:parameter:image:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"changeParameter"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"component"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"parameter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"image"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":"!)"}],"abstract":[{"type":"text","text":"Changes a node or component image parameter."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/changeParameter(_:component:parameter:image:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"changeParameter:component:parameter:image:"}],"url":"\/documentation\/deepar\/deepar\/changeparameter(_:component:parameter:image:)"},"doc://ai.deepar.DeepAR/documentation/DeepAR/DeepAR/changeParameter(_:component:parameter:stringValue:)":{"role":"symbol","title":"changeParameter(_:component:parameter:stringValue:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"changeParameter"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"component"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"parameter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"stringValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!)"}],"abstract":[{"type":"text","text":"Changes a node or component string parameter."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/changeParameter(_:component:parameter:stringValue:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"changeParameter:component:parameter:stringValue:"}],"url":"\/documentation\/deepar\/deepar\/changeparameter(_:component:parameter:stringvalue:)"},"doc://ai.deepar.DeepAR/documentation/DeepAR/DeepAR/changeParameter(_:component:parameter:floatValue:)":{"role":"symbol","title":"changeParameter(_:component:parameter:floatValue:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"changeParameter"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"component"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"parameter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"floatValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Changes a node or component float parameter."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/changeParameter(_:component:parameter:floatValue:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"changeParameter:component:parameter:floatValue:"}],"url":"\/documentation\/deepar\/deepar\/changeparameter(_:component:parameter:floatvalue:)"},"doc://ai.deepar.DeepAR/documentation/DeepAR/DeepAR":{"role":"symbol","title":"DeepAR","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DeepAR"}],"abstract":[{"type":"text","text":"Main class for interacting with DeepAR engine."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DeepAR"}],"url":"\/documentation\/deepar\/deepar"},"doc://ai.deepar.DeepAR/documentation/DeepAR/Vector3":{"role":"symbol","title":"Vector3","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Vector3"}],"abstract":[{"type":"text","text":"A three-dimensional float vector."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/Vector3","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Vector3"}],"url":"\/documentation\/deepar\/vector3"},"doc://ai.deepar.DeepAR/documentation/DeepAR/DeepAR/changeParameter(_:component:parameter:vector3Value:)":{"role":"symbol","title":"changeParameter(_:component:parameter:vector3Value:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"changeParameter"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"component"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"parameter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"vector3Value"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Vector3","preciseIdentifier":"c:@SA@Vector3"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Changes a node or component 3D vector parameter."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/changeParameter(_:component:parameter:vector3Value:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"changeParameter:component:parameter:vector3Value:"}],"url":"\/documentation\/deepar\/deepar\/changeparameter(_:component:parameter:vector3value:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"changeParameter:component:parameter:vector3Value:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"changeParameter:component:parameter:vector3Value:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"Change AR effect parameters in runtime","identifiers":["doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/changeParameter(_:component:parameter:boolValue:)","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/changeParameter(_:component:parameter:floatValue:)","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/changeParameter(_:component:parameter:stringValue:)","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/changeParameter(_:component:parameter:vectorValue:)","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/changeParameter(_:component:parameter:image:)"],"generated":true}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"changeParameter:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"gameObject"},{"kind":"text","text":" "},{"kind":"identifier","text":"component:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"component"},{"kind":"text","text":" "},{"kind":"identifier","text":"parameter:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"parameter"},{"kind":"text","text":" "},{"kind":"identifier","text":"vector3Value:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/Vector3","preciseIdentifier":"c:@SA@Vector3","text":"Vector3"},{"kind":"text","text":")"},{"kind":"internalParam","text":"value"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR~1changeParameter(_:component:parameter:vectorValue:)\/title","value":"changeParameter:component:parameter:vectorValue:"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR~1changeParameter(_:component:parameter:vectorValue:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"changeParameter:component:parameter:vectorValue:"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR~1changeParameter(_:component:parameter:boolValue:)\/title","value":"changeParameter:component:parameter:boolValue:"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR~1changeParameter(_:component:parameter:boolValue:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"changeParameter:component:parameter:boolValue:"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR~1changeParameter(_:component:parameter:image:)\/title","value":"changeParameter:component:parameter:image:"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR~1changeParameter(_:component:parameter:image:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"changeParameter:component:parameter:image:"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR~1changeParameter(_:component:parameter:stringValue:)\/title","value":"changeParameter:component:parameter:stringValue:"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR~1changeParameter(_:component:parameter:stringValue:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"changeParameter:component:parameter:stringValue:"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR~1changeParameter(_:component:parameter:floatValue:)\/title","value":"changeParameter:component:parameter:floatValue:"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR~1changeParameter(_:component:parameter:floatValue:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"changeParameter:component:parameter:floatValue:"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR\/title","value":"DeepAR"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR\/fragments","value":[{"kind":"identifier","text":"DeepAR"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1Vector3\/title","value":"Vector3"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR~1changeParameter(_:component:parameter:vector3Value:)\/title","value":"changeParameter:component:parameter:vector3Value:"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR~1changeParameter(_:component:parameter:vector3Value:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"changeParameter:component:parameter:vector3Value:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}