{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"enqueueAudioSample"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"sampleBuffer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CMSampleBuffer","preciseIdentifier":"c:@T@CMSampleBufferRef"},{"kind":"text","text":"!)"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"sampleBuffer","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The sample buffer."}]}]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Used in video recording when user wants to record audio too. Audio samples will be processed only"},{"type":"text","text":" "},{"type":"text","text":"if the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/startVideoRecording(withOutputWidth:outputHeight:subframe:videoCompressionProperties:recordAudio:)"},{"type":"text","text":" "},{"type":"text","text":"method has been called with "},{"type":"codeVoice","code":"recordAudio"},{"type":"text","text":" parameter set to true."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/deepar\/deepar\/enqueueaudiosample(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/deepar\/deepar\/enqueueaudiosample(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/enqueueAudioSample(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Enqueue an audio sample to the DeepAR engine."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"enqueueAudioSample"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CMSampleBuffer","preciseIdentifier":"c:@T@CMSampleBufferRef"},{"kind":"text","text":"!)"}],"title":"enqueueAudioSample(_:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)DeepAR(im)enqueueAudioSample:","modules":[{"name":"DeepAR"}],"navigatorTitle":[{"kind":"identifier","text":"enqueueAudioSample:"}]},"hierarchy":{"paths":[["doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR"]]},"seeAlsoSections":[{"title":"Process camera, image, video or audio for AR preview","identifiers":["doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/enqueueCameraFrame(_:mirror:)","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/processFrame(_:mirror:)","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/processFrame(_:mirror:timestamp:)","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/processFrameAndReturn(_:outputBuffer:mirror:)"],"generated":true}],"references":{"doc://ai.deepar.DeepAR/documentation/DeepAR":{"role":"collection","title":"DeepAR","abstract":[{"type":"text","text":"Build rich Augmented Reality experiences for iPhone, iPad and Mac."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR","kind":"symbol","type":"topic","url":"\/documentation\/deepar"},"doc://ai.deepar.DeepAR/documentation/DeepAR/DeepAR/processFrameAndReturn(_:outputBuffer:mirror:)":{"role":"symbol","title":"processFrameAndReturn(_:outputBuffer:mirror:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"processFrameAndReturn"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CVPixelBuffer","preciseIdentifier":"c:@T@CVPixelBufferRef"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"outputBuffer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CVPixelBuffer","preciseIdentifier":"c:@T@CVPixelBufferRef"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"mirror"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Feed frame to DeepAR for processing."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/processFrameAndReturn(_:outputBuffer:mirror:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"processFrameAndReturn:outputBuffer:mirror:"}],"url":"\/documentation\/deepar\/deepar\/processframeandreturn(_:outputbuffer:mirror:)"},"doc://ai.deepar.DeepAR/documentation/DeepAR/DeepAR/enqueueCameraFrame(_:mirror:)":{"role":"symbol","title":"enqueueCameraFrame(_:mirror:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"enqueueCameraFrame"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CMSampleBuffer","preciseIdentifier":"c:@T@CMSampleBufferRef"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"mirror"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Enqueue camera frame for processing by DeepAR."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/enqueueCameraFrame(_:mirror:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"enqueueCameraFrame:mirror:"}],"url":"\/documentation\/deepar\/deepar\/enqueuecameraframe(_:mirror:)"},"doc://ai.deepar.DeepAR/documentation/DeepAR/DeepAR/enqueueAudioSample(_:)":{"role":"symbol","title":"enqueueAudioSample(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"enqueueAudioSample"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CMSampleBuffer","preciseIdentifier":"c:@T@CMSampleBufferRef"},{"kind":"text","text":"!)"}],"abstract":[{"type":"text","text":"Enqueue an audio sample to the DeepAR engine."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/enqueueAudioSample(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"enqueueAudioSample:"}],"url":"\/documentation\/deepar\/deepar\/enqueueaudiosample(_:)"},"doc://ai.deepar.DeepAR/documentation/DeepAR/DeepAR/startVideoRecording(withOutputWidth:outputHeight:subframe:videoCompressionProperties:recordAudio:)":{"role":"symbol","title":"startVideoRecording(withOutputWidth:outputHeight:subframe:videoCompressionProperties:recordAudio:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startVideoRecording"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withOutputWidth"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"outputHeight"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"subframe"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":", "},{"kind":"externalParam","text":"videoCompressionProperties"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]!, "},{"kind":"externalParam","text":"recordAudio"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Starts video recording of the AR preview with given resolution."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/startVideoRecording(withOutputWidth:outputHeight:subframe:videoCompressionProperties:recordAudio:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"startVideoRecordingWithOutputWidth:outputHeight:subframe:videoCompressionProperties:recordAudio:"}],"url":"\/documentation\/deepar\/deepar\/startvideorecording(withoutputwidth:outputheight:subframe:videocompressionproperties:recordaudio:)"},"doc://ai.deepar.DeepAR/documentation/DeepAR/DeepAR/processFrame(_:mirror:timestamp:)":{"role":"symbol","title":"processFrame(_:mirror:timestamp:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"processFrame"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CVPixelBuffer","preciseIdentifier":"c:@T@CVPixelBufferRef"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"mirror"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"timestamp"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CMTimeValue","preciseIdentifier":"c:@T@CMTimeValue"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Feed frame to DeepAR for processing."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/processFrame(_:mirror:timestamp:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"processFrame:mirror:timestamp:"}],"url":"\/documentation\/deepar\/deepar\/processframe(_:mirror:timestamp:)"},"doc://ai.deepar.DeepAR/documentation/DeepAR/DeepAR/processFrame(_:mirror:)":{"role":"symbol","title":"processFrame(_:mirror:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"processFrame"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CVPixelBuffer","preciseIdentifier":"c:@T@CVPixelBufferRef"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"mirror"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Feed frame to DeepAR for processing."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/processFrame(_:mirror:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"processFrame:mirror:"}],"url":"\/documentation\/deepar\/deepar\/processframe(_:mirror:)"},"doc://ai.deepar.DeepAR/documentation/DeepAR/DeepAR":{"role":"symbol","title":"DeepAR","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DeepAR"}],"abstract":[{"type":"text","text":"Main class for interacting with DeepAR engine."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DeepAR"}],"url":"\/documentation\/deepar\/deepar"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"enqueueAudioSample:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"enqueueAudioSample:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"Process camera, image, video or audio for AR preview","identifiers":["doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/enqueueCameraFrame(_:mirror:)","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/processFrame(_:mirror:)","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/processFrame(_:mirror:timestamp:)","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/processFrameAndReturn(_:outputBuffer:mirror:)"],"generated":true}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"enqueueAudioSample:"},{"kind":"text","text":"("},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"opaqueCMSampleBuffer","preciseIdentifier":"c:@S@opaqueCMSampleBuffer"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"sampleBuffer"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR~1processFrameAndReturn(_:outputBuffer:mirror:)\/title","value":"processFrameAndReturn:outputBuffer:mirror:"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR~1processFrameAndReturn(_:outputBuffer:mirror:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"processFrameAndReturn:outputBuffer:mirror:"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR~1enqueueCameraFrame(_:mirror:)\/title","value":"enqueueCameraFrame:mirror:"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR~1enqueueCameraFrame(_:mirror:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"enqueueCameraFrame:mirror:"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR~1enqueueAudioSample(_:)\/title","value":"enqueueAudioSample:"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR~1enqueueAudioSample(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"enqueueAudioSample:"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR~1startVideoRecording(withOutputWidth:outputHeight:subframe:videoCompressionProperties:recordAudio:)\/title","value":"startVideoRecordingWithOutputWidth:outputHeight:subframe:videoCompressionProperties:recordAudio:"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR~1startVideoRecording(withOutputWidth:outputHeight:subframe:videoCompressionProperties:recordAudio:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"startVideoRecordingWithOutputWidth:outputHeight:subframe:videoCompressionProperties:recordAudio:"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR~1processFrame(_:mirror:timestamp:)\/title","value":"processFrame:mirror:timestamp:"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR~1processFrame(_:mirror:timestamp:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"processFrame:mirror:timestamp:"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR~1processFrame(_:mirror:)\/title","value":"processFrame:mirror:"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR~1processFrame(_:mirror:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"processFrame:mirror:"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR\/title","value":"DeepAR"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR\/fragments","value":[{"kind":"identifier","text":"DeepAR"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}