{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getDoubleVar"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"name"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!) -> "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Double value of the variable with the specified name."}]}]},{"kind":"parameters","parameters":[{"name":"name","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The variable name."}]}]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The variable is searched in all effects."}]},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"codeVoice","code":"NSException"},{"type":"text","text":" if the variable with the specified name does not exist or is not of the double type."}]}],"type":"aside","name":"Throws"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/deepar\/deepar\/getdoublevar(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/deepar\/deepar\/getdoublevar(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/getDoubleVar(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Get double variable with the given name."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getDoubleVar"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!) -> "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"title":"getDoubleVar(_:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)DeepAR(im)getDoubleVar:","modules":[{"name":"DeepAR"}],"navigatorTitle":[{"kind":"identifier","text":"getDoubleVar:"}]},"hierarchy":{"paths":[["doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR"]]},"seeAlsoSections":[{"title":"Interact with scripting variables","identifiers":["doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/hasVar(_:)","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/hasVar(_:slot:)","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/getVarType(_:)","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/getVarType(_:slot:)","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/getBoolVar(_:)","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/getBoolVar(_:slot:)","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/getIntVar(_:)","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/getIntVar(_:slot:)","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/getDoubleVar(_:slot:)","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/getStringVar(_:)","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/getStringVar(_:slot:)","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/setBoolVar(_:value:)","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/setBoolVar(_:value:slot:)","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/setIntVar(_:value:)","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/setIntVar(_:value:slot:)","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/setDoubleVar(_:value:)","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/setDoubleVar(_:value:slot:)","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/setStringVar(_:value:)","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/setStringVar(_:value:slot:)","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/deleteVar(_:)","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/deleteVar(_:slot:)","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/clearVars()","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/clearVars(_:)"],"generated":true}],"references":{"doc://ai.deepar.DeepAR/documentation/DeepAR":{"role":"collection","title":"DeepAR","abstract":[{"type":"text","text":"Build rich Augmented Reality experiences for iPhone, iPad and Mac."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR","kind":"symbol","type":"topic","url":"\/documentation\/deepar"},"doc://ai.deepar.DeepAR/documentation/DeepAR/DeepAR/getIntVar(_:)":{"role":"symbol","title":"getIntVar(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getIntVar"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!) -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"Get integer variable with the given name."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/getIntVar(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getIntVar:"}],"url":"\/documentation\/deepar\/deepar\/getintvar(_:)"},"doc://ai.deepar.DeepAR/documentation/DeepAR/DeepAR/getIntVar(_:slot:)":{"role":"symbol","title":"getIntVar(_:slot:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getIntVar"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"slot"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!) -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"Get integer variable with the given name."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/getIntVar(_:slot:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getIntVar:slot:"}],"url":"\/documentation\/deepar\/deepar\/getintvar(_:slot:)"},"doc://ai.deepar.DeepAR/documentation/DeepAR/DeepAR/hasVar(_:)":{"role":"symbol","title":"hasVar(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"hasVar"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Check if variable with the given name is already created in at least one effect."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/hasVar(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"hasVar:"}],"url":"\/documentation\/deepar\/deepar\/hasvar(_:)"},"doc://ai.deepar.DeepAR/documentation/DeepAR/DeepAR":{"role":"symbol","title":"DeepAR","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DeepAR"}],"abstract":[{"type":"text","text":"Main class for interacting with DeepAR engine."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DeepAR"}],"url":"\/documentation\/deepar\/deepar"},"doc://ai.deepar.DeepAR/documentation/DeepAR/DeepAR/getVarType(_:)":{"role":"symbol","title":"getVarType(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getVarType"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!) -> "},{"kind":"typeIdentifier","text":"VarType","preciseIdentifier":"c:@E@VarType"}],"abstract":[{"type":"text","text":"Get the type of the variable with the given name."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/getVarType(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getVarType:"}],"url":"\/documentation\/deepar\/deepar\/getvartype(_:)"},"doc://ai.deepar.DeepAR/documentation/DeepAR/DeepAR/getStringVar(_:)":{"role":"symbol","title":"getStringVar(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getStringVar"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!) -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"abstract":[{"type":"text","text":"Get string variable with the given name."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/getStringVar(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getStringVar:"}],"url":"\/documentation\/deepar\/deepar\/getstringvar(_:)"},"doc://ai.deepar.DeepAR/documentation/DeepAR/DeepAR/deleteVar(_:slot:)":{"role":"symbol","title":"deleteVar(_:slot:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"deleteVar"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"slot"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Delete the variable with the given name."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/deleteVar(_:slot:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"deleteVar:slot:"}],"url":"\/documentation\/deepar\/deepar\/deletevar(_:slot:)"},"doc://ai.deepar.DeepAR/documentation/DeepAR/DeepAR/setIntVar(_:value:slot:)":{"role":"symbol","title":"setIntVar(_:value:slot:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setIntVar"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"value"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"slot"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Set the int variable wih the given name."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/setIntVar(_:value:slot:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setIntVar:value:slot:"}],"url":"\/documentation\/deepar\/deepar\/setintvar(_:value:slot:)"},"doc://ai.deepar.DeepAR/documentation/DeepAR/DeepAR/getBoolVar(_:)":{"role":"symbol","title":"getBoolVar(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getBoolVar"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Get boolean variable with the given name."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/getBoolVar(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getBoolVar:"}],"url":"\/documentation\/deepar\/deepar\/getboolvar(_:)"},"doc://ai.deepar.DeepAR/documentation/DeepAR/DeepAR/setBoolVar(_:value:slot:)":{"role":"symbol","title":"setBoolVar(_:value:slot:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setBoolVar"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"value"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"slot"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Set the boolean variable wih the given name."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/setBoolVar(_:value:slot:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setBoolVar:value:slot:"}],"url":"\/documentation\/deepar\/deepar\/setboolvar(_:value:slot:)"},"doc://ai.deepar.DeepAR/documentation/DeepAR/DeepAR/getDoubleVar(_:slot:)":{"role":"symbol","title":"getDoubleVar(_:slot:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getDoubleVar"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"slot"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!) -> "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"abstract":[{"type":"text","text":"Get double variable with the given name."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/getDoubleVar(_:slot:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getDoubleVar:slot:"}],"url":"\/documentation\/deepar\/deepar\/getdoublevar(_:slot:)"},"doc://ai.deepar.DeepAR/documentation/DeepAR/DeepAR/setDoubleVar(_:value:)":{"role":"symbol","title":"setDoubleVar(_:value:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setDoubleVar"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"value"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Set the double variable with the given name."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/setDoubleVar(_:value:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setDoubleVar:value:"}],"url":"\/documentation\/deepar\/deepar\/setdoublevar(_:value:)"},"doc://ai.deepar.DeepAR/documentation/DeepAR/DeepAR/setBoolVar(_:value:)":{"role":"symbol","title":"setBoolVar(_:value:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setBoolVar"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"value"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Set the boolean variable with the given name."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/setBoolVar(_:value:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setBoolVar:value:"}],"url":"\/documentation\/deepar\/deepar\/setboolvar(_:value:)"},"doc://ai.deepar.DeepAR/documentation/DeepAR/DeepAR/getBoolVar(_:slot:)":{"role":"symbol","title":"getBoolVar(_:slot:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getBoolVar"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"slot"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Get boolean variable with the given name."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/getBoolVar(_:slot:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getBoolVar:slot:"}],"url":"\/documentation\/deepar\/deepar\/getboolvar(_:slot:)"},"doc://ai.deepar.DeepAR/documentation/DeepAR/DeepAR/setStringVar(_:value:)":{"role":"symbol","title":"setStringVar(_:value:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setStringVar"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"value"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Set the string variable with the given name."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/setStringVar(_:value:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setStringVar:value:"}],"url":"\/documentation\/deepar\/deepar\/setstringvar(_:value:)"},"doc://ai.deepar.DeepAR/documentation/DeepAR/DeepAR/clearVars()":{"role":"symbol","title":"clearVars()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"clearVars"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Clear all variables."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/clearVars()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"clearVars"}],"url":"\/documentation\/deepar\/deepar\/clearvars()"},"doc://ai.deepar.DeepAR/documentation/DeepAR/DeepAR/setStringVar(_:value:slot:)":{"role":"symbol","title":"setStringVar(_:value:slot:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setStringVar"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"value"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"slot"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Set the string variable wih the given name."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/setStringVar(_:value:slot:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setStringVar:value:slot:"}],"url":"\/documentation\/deepar\/deepar\/setstringvar(_:value:slot:)"},"doc://ai.deepar.DeepAR/documentation/DeepAR/DeepAR/getVarType(_:slot:)":{"role":"symbol","title":"getVarType(_:slot:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getVarType"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"slot"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!) -> "},{"kind":"typeIdentifier","text":"VarType","preciseIdentifier":"c:@E@VarType"}],"abstract":[{"type":"text","text":"Get the type of the variable with the given name in the specified effect."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/getVarType(_:slot:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getVarType:slot:"}],"url":"\/documentation\/deepar\/deepar\/getvartype(_:slot:)"},"doc://ai.deepar.DeepAR/documentation/DeepAR/DeepAR/setIntVar(_:value:)":{"role":"symbol","title":"setIntVar(_:value:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setIntVar"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"value"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Set the int variable with the given name."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/setIntVar(_:value:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setIntVar:value:"}],"url":"\/documentation\/deepar\/deepar\/setintvar(_:value:)"},"doc://ai.deepar.DeepAR/documentation/DeepAR/DeepAR/getStringVar(_:slot:)":{"role":"symbol","title":"getStringVar(_:slot:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getStringVar"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"slot"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!) -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"abstract":[{"type":"text","text":"Get string variable with the given name."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/getStringVar(_:slot:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getStringVar:slot:"}],"url":"\/documentation\/deepar\/deepar\/getstringvar(_:slot:)"},"doc://ai.deepar.DeepAR/documentation/DeepAR/DeepAR/setDoubleVar(_:value:slot:)":{"role":"symbol","title":"setDoubleVar(_:value:slot:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setDoubleVar"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"value"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":", "},{"kind":"externalParam","text":"slot"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Set the double variable wih the given name."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/setDoubleVar(_:value:slot:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setDoubleVar:value:slot:"}],"url":"\/documentation\/deepar\/deepar\/setdoublevar(_:value:slot:)"},"doc://ai.deepar.DeepAR/documentation/DeepAR/DeepAR/deleteVar(_:)":{"role":"symbol","title":"deleteVar(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"deleteVar"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Delete the variable with the given name."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/deleteVar(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"deleteVar:"}],"url":"\/documentation\/deepar\/deepar\/deletevar(_:)"},"doc://ai.deepar.DeepAR/documentation/DeepAR/DeepAR/clearVars(_:)":{"role":"symbol","title":"clearVars(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"clearVars"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Clear all variables or variables from the specified effect."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/clearVars(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"clearVars:"}],"url":"\/documentation\/deepar\/deepar\/clearvars(_:)"},"doc://ai.deepar.DeepAR/documentation/DeepAR/DeepAR/getDoubleVar(_:)":{"role":"symbol","title":"getDoubleVar(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getDoubleVar"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!) -> "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"abstract":[{"type":"text","text":"Get double variable with the given name."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/getDoubleVar(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getDoubleVar:"}],"url":"\/documentation\/deepar\/deepar\/getdoublevar(_:)"},"doc://ai.deepar.DeepAR/documentation/DeepAR/DeepAR/hasVar(_:slot:)":{"role":"symbol","title":"hasVar(_:slot:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"hasVar"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"slot"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Check if variable with the given name is already created in the specified effect."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/hasVar(_:slot:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"hasVar:slot:"}],"url":"\/documentation\/deepar\/deepar\/hasvar(_:slot:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"getDoubleVar:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getDoubleVar:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"Interact with scripting variables","identifiers":["doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/hasVar(_:)","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/hasVar(_:slot:)","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/getVarType(_:)","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/getVarType(_:slot:)","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/getBoolVar(_:)","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/getBoolVar(_:slot:)","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/getIntVar(_:)","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/getIntVar(_:slot:)","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/getDoubleVar(_:slot:)","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/getStringVar(_:)","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/getStringVar(_:slot:)","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/setBoolVar(_:value:)","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/setBoolVar(_:value:slot:)","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/setIntVar(_:value:)","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/setIntVar(_:value:slot:)","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/setDoubleVar(_:value:)","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/setDoubleVar(_:value:slot:)","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/setStringVar(_:value:)","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/setStringVar(_:value:slot:)","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/deleteVar(_:)","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/deleteVar(_:slot:)","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/clearVars()","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/clearVars(_:)"],"generated":true}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"double","preciseIdentifier":"c:d"},{"kind":"text","text":") "},{"kind":"identifier","text":"getDoubleVar:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"name"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR~1getIntVar(_:)\/title","value":"getIntVar:"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR~1getIntVar(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getIntVar:"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR~1getIntVar(_:slot:)\/title","value":"getIntVar:slot:"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR~1getIntVar(_:slot:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getIntVar:slot:"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR~1hasVar(_:)\/title","value":"hasVar:"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR~1hasVar(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"hasVar:"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR\/title","value":"DeepAR"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR\/fragments","value":[{"kind":"identifier","text":"DeepAR"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR~1getVarType(_:)\/title","value":"getVarType:"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR~1getVarType(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getVarType:"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR~1getStringVar(_:)\/title","value":"getStringVar:"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR~1getStringVar(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getStringVar:"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR~1deleteVar(_:slot:)\/title","value":"deleteVar:slot:"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR~1deleteVar(_:slot:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"deleteVar:slot:"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR~1setIntVar(_:value:slot:)\/title","value":"setIntVar:value:slot:"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR~1setIntVar(_:value:slot:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setIntVar:value:slot:"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR~1getBoolVar(_:)\/title","value":"getBoolVar:"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR~1getBoolVar(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getBoolVar:"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR~1setBoolVar(_:value:slot:)\/title","value":"setBoolVar:value:slot:"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR~1setBoolVar(_:value:slot:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setBoolVar:value:slot:"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR~1getDoubleVar(_:slot:)\/title","value":"getDoubleVar:slot:"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR~1getDoubleVar(_:slot:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getDoubleVar:slot:"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR~1setDoubleVar(_:value:)\/title","value":"setDoubleVar:value:"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR~1setDoubleVar(_:value:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setDoubleVar:value:"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR~1setBoolVar(_:value:)\/title","value":"setBoolVar:value:"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR~1setBoolVar(_:value:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setBoolVar:value:"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR~1getBoolVar(_:slot:)\/title","value":"getBoolVar:slot:"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR~1getBoolVar(_:slot:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getBoolVar:slot:"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR~1setStringVar(_:value:)\/title","value":"setStringVar:value:"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR~1setStringVar(_:value:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setStringVar:value:"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR~1clearVars()\/title","value":"clearVars"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR~1clearVars()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"clearVars"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR~1setStringVar(_:value:slot:)\/title","value":"setStringVar:value:slot:"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR~1setStringVar(_:value:slot:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setStringVar:value:slot:"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR~1getVarType(_:slot:)\/title","value":"getVarType:slot:"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR~1getVarType(_:slot:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getVarType:slot:"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR~1setIntVar(_:value:)\/title","value":"setIntVar:value:"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR~1setIntVar(_:value:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setIntVar:value:"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR~1getStringVar(_:slot:)\/title","value":"getStringVar:slot:"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR~1getStringVar(_:slot:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getStringVar:slot:"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR~1setDoubleVar(_:value:slot:)\/title","value":"setDoubleVar:value:slot:"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR~1setDoubleVar(_:value:slot:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setDoubleVar:value:slot:"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR~1deleteVar(_:)\/title","value":"deleteVar:"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR~1deleteVar(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"deleteVar:"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR~1clearVars(_:)\/title","value":"clearVars:"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR~1clearVars(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"clearVars:"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR~1getDoubleVar(_:)\/title","value":"getDoubleVar:"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR~1getDoubleVar(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getDoubleVar:"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR~1hasVar(_:slot:)\/title","value":"hasVar:slot:"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR~1hasVar(_:slot:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"hasVar:slot:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}