{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"initializeOffscreen"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withWidth"},{"kind":"text","text":" "},{"kind":"internalParam","text":"width"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"height"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"width","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The rendering width."}]}]},{"name":"height","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The rendering height."}]}]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Frames will be produced in "},{"type":"reference","isActive":true,"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepARDelegate\/frameAvailable(_:)"},{"type":"text","text":" delegate method."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/deepar\/deepar\/initializeoffscreen(withwidth:height:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/deepar\/deepar\/initializeoffscreen(withwidth:height:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/initializeOffscreen(withWidth:height:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Starts the engine initialization for rendering in off-screen mode."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"initializeOffscreen"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withWidth"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"height"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"title":"initializeOffscreen(withWidth:height:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)DeepAR(im)initializeOffscreenWithWidth:height:","modules":[{"name":"DeepAR"}],"navigatorTitle":[{"kind":"identifier","text":"initializeOffscreenWithWidth:height:"}]},"hierarchy":{"paths":[["doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR"]]},"seeAlsoSections":[{"title":"Capture image buffer of the AR preview","identifiers":["doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/startCapture(withOutputWidth:outputHeight:subframe:)","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/startCapture(withOutputWidthAndFormat:outputHeight:subframe:outputImageFormat:)","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/stopCapture()"],"generated":true}],"references":{"doc://ai.deepar.DeepAR/documentation/DeepAR/DeepAR/stopCapture()":{"role":"symbol","title":"stopCapture()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"stopCapture"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Stops capturing the AR preview frames in the image buffer."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/stopCapture()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"stopCapture"}],"url":"\/documentation\/deepar\/deepar\/stopcapture()"},"doc://ai.deepar.DeepAR/documentation/DeepAR/DeepAR/startCapture(withOutputWidth:outputHeight:subframe:)":{"role":"symbol","title":"startCapture(withOutputWidth:outputHeight:subframe:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startCapture"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withOutputWidth"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"outputHeight"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"subframe"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Starts capturing the AR preview frames in the image buffer."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/startCapture(withOutputWidth:outputHeight:subframe:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"startCaptureWithOutputWidth:outputHeight:subframe:"}],"url":"\/documentation\/deepar\/deepar\/startcapture(withoutputwidth:outputheight:subframe:)"},"doc://ai.deepar.DeepAR/documentation/DeepAR/DeepARDelegate/frameAvailable(_:)":{"navigatorTitle":[{"kind":"identifier","text":"frameAvailable:"}],"role":"symbol","title":"frameAvailable(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"frameAvailable"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CMSampleBuffer","preciseIdentifier":"c:@T@CMSampleBufferRef"},{"kind":"text","text":"!)"}],"abstract":[{"type":"text","text":"Called when a new processed frame is available."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepARDelegate\/frameAvailable(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/deepar\/deepardelegate\/frameavailable(_:)"},"doc://ai.deepar.DeepAR/documentation/DeepAR/DeepAR/startCapture(withOutputWidthAndFormat:outputHeight:subframe:outputImageFormat:)":{"role":"symbol","title":"startCapture(withOutputWidthAndFormat:outputHeight:subframe:outputImageFormat:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startCapture"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withOutputWidthAndFormat"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"outputHeight"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"subframe"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":", "},{"kind":"externalParam","text":"outputImageFormat"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"OutputFormat","preciseIdentifier":"c:@E@OutputFormat"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Starts capturing the AR preview frames in the image buffer."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/startCapture(withOutputWidthAndFormat:outputHeight:subframe:outputImageFormat:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"startCaptureWithOutputWidthAndFormat:outputHeight:subframe:outputImageFormat:"}],"url":"\/documentation\/deepar\/deepar\/startcapture(withoutputwidthandformat:outputheight:subframe:outputimageformat:)"},"doc://ai.deepar.DeepAR/documentation/DeepAR/DeepAR":{"role":"symbol","title":"DeepAR","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DeepAR"}],"abstract":[{"type":"text","text":"Main class for interacting with DeepAR engine."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DeepAR"}],"url":"\/documentation\/deepar\/deepar"},"doc://ai.deepar.DeepAR/documentation/DeepAR":{"role":"collection","title":"DeepAR","abstract":[{"type":"text","text":"Build rich Augmented Reality experiences for iPhone, iPad and Mac."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR","kind":"symbol","type":"topic","url":"\/documentation\/deepar"},"doc://ai.deepar.DeepAR/documentation/DeepAR/DeepAR/initializeOffscreen(withWidth:height:)":{"role":"symbol","title":"initializeOffscreen(withWidth:height:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"initializeOffscreen"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withWidth"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"height"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Starts the engine initialization for rendering in off-screen mode."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/initializeOffscreen(withWidth:height:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initializeOffscreenWithWidth:height:"}],"url":"\/documentation\/deepar\/deepar\/initializeoffscreen(withwidth:height:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initializeOffscreenWithWidth:height:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initializeOffscreenWithWidth:height:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"Capture image buffer of the AR preview","identifiers":["doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/startCapture(withOutputWidth:outputHeight:subframe:)","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/startCapture(withOutputWidthAndFormat:outputHeight:subframe:outputImageFormat:)","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/stopCapture()"],"generated":true}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"initializeOffscreenWithWidth:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":")"},{"kind":"internalParam","text":"width"},{"kind":"text","text":" "},{"kind":"identifier","text":"height:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":")"},{"kind":"internalParam","text":"height"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR~1stopCapture()\/title","value":"stopCapture"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR~1stopCapture()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"stopCapture"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR~1startCapture(withOutputWidth:outputHeight:subframe:)\/title","value":"startCaptureWithOutputWidth:outputHeight:subframe:"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR~1startCapture(withOutputWidth:outputHeight:subframe:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"startCaptureWithOutputWidth:outputHeight:subframe:"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepARDelegate~1frameAvailable(_:)\/title","value":"frameAvailable:"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepARDelegate~1frameAvailable(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"frameAvailable:"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR~1startCapture(withOutputWidthAndFormat:outputHeight:subframe:outputImageFormat:)\/title","value":"startCaptureWithOutputWidthAndFormat:outputHeight:subframe:outputImageFormat:"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR~1startCapture(withOutputWidthAndFormat:outputHeight:subframe:outputImageFormat:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"startCaptureWithOutputWidthAndFormat:outputHeight:subframe:outputImageFormat:"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR\/title","value":"DeepAR"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR\/fragments","value":[{"kind":"identifier","text":"DeepAR"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR~1initializeOffscreen(withWidth:height:)\/title","value":"initializeOffscreenWithWidth:height:"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR~1initializeOffscreen(withWidth:height:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initializeOffscreenWithWidth:height:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}