{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"initialize"},{"kind":"text","text":"()"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Vision-only mode doesn’t do any rendering and\/or camera preview. It is used just to get the ML tracking information from DeepAR.."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/deepar\/deepar\/initialize()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/deepar\/deepar\/initialize()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/initialize()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Initialize DeepAR in vision-only mode."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"initialize"},{"kind":"text","text":"()"}],"title":"initialize()","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)DeepAR(im)initialize","modules":[{"name":"DeepAR"}],"navigatorTitle":[{"kind":"identifier","text":"initialize"}]},"hierarchy":{"paths":[["doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR"]]},"seeAlsoSections":[{"title":"Advance initialization of DeepAR","identifiers":["doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/initializeOffscreen(withWidth:height:)","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/initialize(withWidth:height:window:)"],"generated":true}],"references":{"doc://ai.deepar.DeepAR/documentation/DeepAR":{"role":"collection","title":"DeepAR","abstract":[{"type":"text","text":"Build rich Augmented Reality experiences for iPhone, iPad and Mac."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR","kind":"symbol","type":"topic","url":"\/documentation\/deepar"},"doc://ai.deepar.DeepAR/documentation/DeepAR/DeepAR/initialize()":{"role":"symbol","title":"initialize()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"initialize"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Initialize DeepAR in vision-only mode."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/initialize()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initialize"}],"url":"\/documentation\/deepar\/deepar\/initialize()"},"doc://ai.deepar.DeepAR/documentation/DeepAR/DeepAR":{"role":"symbol","title":"DeepAR","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DeepAR"}],"abstract":[{"type":"text","text":"Main class for interacting with DeepAR engine."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DeepAR"}],"url":"\/documentation\/deepar\/deepar"},"doc://ai.deepar.DeepAR/documentation/DeepAR/DeepAR/initialize(withWidth:height:window:)":{"role":"symbol","title":"initialize(withWidth:height:window:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"initialize"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withWidth"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"height"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"window"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CAEAGLLayer","preciseIdentifier":"c:objc(cs)CAEAGLLayer"},{"kind":"text","text":"!)"}],"abstract":[{"type":"text","text":"Initialize DeepAR with a "},{"type":"reference","isActive":true,"identifier":"https:\/\/developer.apple.com\/documentation\/quartzcore\/caeagllayer"},{"type":"text","text":" as rendering target."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/initialize(withWidth:height:window:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initializeWithWidth:height:window:"}],"url":"\/documentation\/deepar\/deepar\/initialize(withwidth:height:window:)"},"https://developer.apple.com/documentation/quartzcore/caeagllayer":{"title":"CAEAGLLayer","titleInlineContent":[{"type":"text","text":"CAEAGLLayer"}],"type":"link","identifier":"https:\/\/developer.apple.com\/documentation\/quartzcore\/caeagllayer","url":"https:\/\/developer.apple.com\/documentation\/quartzcore\/caeagllayer"},"doc://ai.deepar.DeepAR/documentation/DeepAR/DeepAR/initializeOffscreen(withWidth:height:)":{"role":"symbol","title":"initializeOffscreen(withWidth:height:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"initializeOffscreen"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withWidth"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"height"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Starts the engine initialization for rendering in off-screen mode."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/initializeOffscreen(withWidth:height:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initializeOffscreenWithWidth:height:"}],"url":"\/documentation\/deepar\/deepar\/initializeoffscreen(withwidth:height:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initialize"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initialize"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"Advance initialization of DeepAR","identifiers":["doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/initializeOffscreen(withWidth:height:)","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/initialize(withWidth:height:window:)"],"generated":true}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"initialize"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR~1initialize()\/title","value":"initialize"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR~1initialize()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initialize"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR\/title","value":"DeepAR"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR\/fragments","value":[{"kind":"identifier","text":"DeepAR"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR~1initialize(withWidth:height:window:)\/title","value":"initializeWithWidth:height:window:"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR~1initialize(withWidth:height:window:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initializeWithWidth:height:window:"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR~1initializeOffscreen(withWidth:height:)\/title","value":"initializeOffscreenWithWidth:height:"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR~1initializeOffscreen(withWidth:height:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initializeOffscreenWithWidth:height:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}