{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setFaceTrackingInitParameters"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"params"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/FaceTrackingInitParameters","preciseIdentifier":"c:@SA@FaceTrackingInitParameters","text":"FaceTrackingInitParameters"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"params","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The parameters. See "},{"type":"reference","isActive":true,"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/FaceTrackingInitParameters"},{"type":"text","text":"."}]}]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"style":"important","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"This function must be called before DeepAR engine initializes. Call it before calling "},{"type":"reference","isActive":true,"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/createARView(withFrame:)"},{"type":"text","text":" or "},{"type":"reference","isActive":true,"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/initializeOffscreen(withWidth:height:)"},{"type":"text","text":"."}]}],"type":"aside","name":"Important"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/deepar\/deepar\/setfacetrackinginitparameters(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/deepar\/deepar\/setfacetrackinginitparameters(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/setFaceTrackingInitParameters(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Set parameters that will determine how the face tracking is initialized."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setFaceTrackingInitParameters"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"FaceTrackingInitParameters","preciseIdentifier":"c:@SA@FaceTrackingInitParameters"},{"kind":"text","text":")"}],"title":"setFaceTrackingInitParameters(_:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)DeepAR(im)setFaceTrackingInitParameters:","modules":[{"name":"DeepAR"}],"navigatorTitle":[{"kind":"identifier","text":"setFaceTrackingInitParameters:"}]},"hierarchy":{"paths":[["doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR"]]},"references":{"doc://ai.deepar.DeepAR/documentation/DeepAR":{"role":"collection","title":"DeepAR","abstract":[{"type":"text","text":"Build rich Augmented Reality experiences for iPhone, iPad and Mac."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR","kind":"symbol","type":"topic","url":"\/documentation\/deepar"},"doc://ai.deepar.DeepAR/documentation/DeepAR/FaceTrackingInitParameters":{"role":"symbol","title":"FaceTrackingInitParameters","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceTrackingInitParameters"}],"abstract":[{"type":"text","text":"Properties related to face tracking initialization."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/FaceTrackingInitParameters","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FaceTrackingInitParameters"}],"url":"\/documentation\/deepar\/facetrackinginitparameters"},"doc://ai.deepar.DeepAR/documentation/DeepAR/DeepAR":{"role":"symbol","title":"DeepAR","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DeepAR"}],"abstract":[{"type":"text","text":"Main class for interacting with DeepAR engine."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DeepAR"}],"url":"\/documentation\/deepar\/deepar"},"doc://ai.deepar.DeepAR/documentation/DeepAR/DeepAR/setFaceTrackingInitParameters(_:)":{"role":"symbol","title":"setFaceTrackingInitParameters(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setFaceTrackingInitParameters"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"FaceTrackingInitParameters","preciseIdentifier":"c:@SA@FaceTrackingInitParameters"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Set parameters that will determine how the face tracking is initialized."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/setFaceTrackingInitParameters(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setFaceTrackingInitParameters:"}],"url":"\/documentation\/deepar\/deepar\/setfacetrackinginitparameters(_:)"},"doc://ai.deepar.DeepAR/documentation/DeepAR/DeepAR/createARView(withFrame:)":{"role":"symbol","title":"createARView(withFrame:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createARView"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withFrame"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":"!"}],"abstract":[{"type":"text","text":"Initialize DeepAR and render the AR preview in the "},{"type":"codeVoice","code":"UIView"},{"type":"text","text":"."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/createARView(withFrame:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"createARViewWithFrame:"}],"url":"\/documentation\/deepar\/deepar\/createarview(withframe:)"},"doc://ai.deepar.DeepAR/documentation/DeepAR/DeepAR/initializeOffscreen(withWidth:height:)":{"role":"symbol","title":"initializeOffscreen(withWidth:height:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"initializeOffscreen"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withWidth"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"height"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Starts the engine initialization for rendering in off-screen mode."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/initializeOffscreen(withWidth:height:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initializeOffscreenWithWidth:height:"}],"url":"\/documentation\/deepar\/deepar\/initializeoffscreen(withwidth:height:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"setFaceTrackingInitParameters:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setFaceTrackingInitParameters:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"setFaceTrackingInitParameters:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/FaceTrackingInitParameters","preciseIdentifier":"c:@SA@FaceTrackingInitParameters","text":"FaceTrackingInitParameters"},{"kind":"text","text":")"},{"kind":"internalParam","text":"params"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1FaceTrackingInitParameters\/title","value":"FaceTrackingInitParameters"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR\/title","value":"DeepAR"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR\/fragments","value":[{"kind":"identifier","text":"DeepAR"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR~1setFaceTrackingInitParameters(_:)\/title","value":"setFaceTrackingInitParameters:"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR~1setFaceTrackingInitParameters(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setFaceTrackingInitParameters:"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR~1createARView(withFrame:)\/title","value":"createARViewWithFrame:"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR~1createARView(withFrame:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"createARViewWithFrame:"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR~1initializeOffscreen(withWidth:height:)\/title","value":"initializeOffscreenWithWidth:height:"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR~1initializeOffscreen(withWidth:height:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initializeOffscreenWithWidth:height:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}