{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setLicenseKey"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"key"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!)"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"key","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The license key."}]}]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The license key is generated on the DeepAR Developer portal. Here are steps on how to generate a license key:"}]},{"type":"orderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Log in\/Sign up to "},{"type":"reference","isActive":true,"identifier":"https:\/\/developer.deepar.ai\/"},{"type":"text","text":"."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Create a new project and in that project create an iOS app."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"In the create app dialog enter your app name and bundle id that your app is using. Bundle id must match the one you are using in your app, otherwise, the license check will fail. Read more about iOS bundle id "},{"type":"reference","isActive":true,"identifier":"https:\/\/developer.apple.com\/documentation\/appstoreconnectapi\/bundle_ids"},{"type":"text","text":"."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Copy the newly generated license key as a parameter in this method."}]}]}]},{"style":"important","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"You must call this method before you call the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/createARView(withFrame:)"},{"type":"text","text":" or any other initialization methods."}]}],"type":"aside","name":"Important"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/deepar\/deepar\/setlicensekey(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/deepar\/deepar\/setlicensekey(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/setLicenseKey(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Set the license key for your app."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setLicenseKey"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!)"}],"title":"setLicenseKey(_:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)DeepAR(im)setLicenseKey:","modules":[{"name":"DeepAR"}],"navigatorTitle":[{"kind":"identifier","text":"setLicenseKey:"}]},"hierarchy":{"paths":[["doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR"]]},"references":{"https://developer.deepar.ai/":{"title":"DeepAR Developer Portal","titleInlineContent":[{"type":"text","text":"DeepAR Developer Portal"}],"type":"link","identifier":"https:\/\/developer.deepar.ai\/","url":"https:\/\/developer.deepar.ai\/"},"doc://ai.deepar.DeepAR/documentation/DeepAR/DeepAR/createARView(withFrame:)":{"role":"symbol","title":"createARView(withFrame:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createARView"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withFrame"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":"!"}],"abstract":[{"type":"text","text":"Initialize DeepAR and render the AR preview in the "},{"type":"codeVoice","code":"UIView"},{"type":"text","text":"."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/createARView(withFrame:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"createARViewWithFrame:"}],"url":"\/documentation\/deepar\/deepar\/createarview(withframe:)"},"doc://ai.deepar.DeepAR/documentation/DeepAR":{"role":"collection","title":"DeepAR","abstract":[{"type":"text","text":"Build rich Augmented Reality experiences for iPhone, iPad and Mac."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR","kind":"symbol","type":"topic","url":"\/documentation\/deepar"},"doc://ai.deepar.DeepAR/documentation/DeepAR/DeepAR/setLicenseKey(_:)":{"role":"symbol","title":"setLicenseKey(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setLicenseKey"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!)"}],"abstract":[{"type":"text","text":"Set the license key for your app."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/setLicenseKey(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setLicenseKey:"}],"url":"\/documentation\/deepar\/deepar\/setlicensekey(_:)"},"doc://ai.deepar.DeepAR/documentation/DeepAR/DeepAR":{"role":"symbol","title":"DeepAR","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DeepAR"}],"abstract":[{"type":"text","text":"Main class for interacting with DeepAR engine."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DeepAR"}],"url":"\/documentation\/deepar\/deepar"},"https://developer.apple.com/documentation/appstoreconnectapi/bundle_ids":{"title":"here","titleInlineContent":[{"type":"text","text":"here"}],"type":"link","identifier":"https:\/\/developer.apple.com\/documentation\/appstoreconnectapi\/bundle_ids","url":"https:\/\/developer.apple.com\/documentation\/appstoreconnectapi\/bundle_ids"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"setLicenseKey:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setLicenseKey:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"setLicenseKey:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"key"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR~1createARView(withFrame:)\/title","value":"createARViewWithFrame:"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR~1createARView(withFrame:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"createARViewWithFrame:"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR~1setLicenseKey(_:)\/title","value":"setLicenseKey:"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR~1setLicenseKey(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setLicenseKey:"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR\/title","value":"DeepAR"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR\/fragments","value":[{"kind":"identifier","text":"DeepAR"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}