{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"simulatePhysics"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"enabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"enabled","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Enable global physics simulation."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/deepar\/deepar\/simulatephysics(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/deepar\/deepar\/simulatephysics(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/simulatePhysics(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Enable or disable global physics simulation."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"simulatePhysics"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"title":"simulatePhysics(_:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)DeepAR(im)simulatePhysics:","modules":[{"name":"DeepAR"}],"navigatorTitle":[{"kind":"identifier","text":"simulatePhysics:"}]},"hierarchy":{"paths":[["doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR"]]},"seeAlsoSections":[{"title":"Physics","identifiers":["doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/showColliders(_:)"],"generated":true}],"references":{"doc://ai.deepar.DeepAR/documentation/DeepAR/DeepAR":{"role":"symbol","title":"DeepAR","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DeepAR"}],"abstract":[{"type":"text","text":"Main class for interacting with DeepAR engine."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DeepAR"}],"url":"\/documentation\/deepar\/deepar"},"doc://ai.deepar.DeepAR/documentation/DeepAR/DeepAR/showColliders(_:)":{"role":"symbol","title":"showColliders(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"showColliders"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Display physics colliders preview on screen."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/showColliders(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"showColliders:"}],"url":"\/documentation\/deepar\/deepar\/showcolliders(_:)"},"doc://ai.deepar.DeepAR/documentation/DeepAR/DeepAR/simulatePhysics(_:)":{"role":"symbol","title":"simulatePhysics(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"simulatePhysics"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Enable or disable global physics simulation."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/simulatePhysics(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"simulatePhysics:"}],"url":"\/documentation\/deepar\/deepar\/simulatephysics(_:)"},"doc://ai.deepar.DeepAR/documentation/DeepAR":{"role":"collection","title":"DeepAR","abstract":[{"type":"text","text":"Build rich Augmented Reality experiences for iPhone, iPad and Mac."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR","kind":"symbol","type":"topic","url":"\/documentation\/deepar"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"simulatePhysics:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"simulatePhysics:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"Physics","identifiers":["doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/showColliders(_:)"],"generated":true}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"simulatePhysics:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":")"},{"kind":"internalParam","text":"enabled"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR\/title","value":"DeepAR"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR\/fragments","value":[{"kind":"identifier","text":"DeepAR"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR~1showColliders(_:)\/title","value":"showColliders:"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR~1showColliders(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"showColliders:"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR~1simulatePhysics(_:)\/title","value":"simulatePhysics:"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR~1simulatePhysics(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"simulatePhysics:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}