{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startVideoRecording"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withOutputWidth"},{"kind":"text","text":" "},{"kind":"internalParam","text":"outputWidth"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"outputHeight"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"subframe"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":", "},{"kind":"externalParam","text":"videoCompressionProperties"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]!, "},{"kind":"externalParam","text":"recordAudio"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"outputWidth","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The output width."}]}]},{"name":"outputHeight","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The output height."}]}]},{"name":"subframe","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Defines the sub rectangle of the AR preview that you want to record in normalized coordinates (0.0 - 1.0)."}]}]},{"name":"videoCompressionProperties","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A dictionary used as the value for the key "},{"type":"reference","isActive":true,"identifier":"https:\/\/developer.apple.com\/documentation\/avfoundation\/avvideocompressionpropertieskey"},{"type":"text","text":". Read more about video compression options in the official docs "},{"overridingTitleInlineContent":[{"type":"text","text":"here"}],"isActive":true,"type":"reference","identifier":"https:\/\/developer.apple.com\/documentation\/avfoundation\/avvideocompressionpropertieskey","overridingTitle":"here"},{"type":"text","text":"."}]}]},{"name":"recordAudio","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Determines weather the audio is recorded. If DeepAR preview is paired with "},{"type":"reference","isActive":true,"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/CameraController"},{"type":"text","text":" this will work out of the box. Otherwise, if set to true the recording will wait until you call "},{"type":"reference","isActive":true,"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/enqueueAudioSample(_:)"},{"type":"text","text":". When DeepAR is ready to receive audio samples it will publish "},{"type":"codeVoice","code":"NSNotification"},{"type":"text","text":" with key "},{"type":"codeVoice","code":"deepar_start_audio"},{"type":"text","text":". You can subscribe to this notification and start feeding audio samples once you receive it."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/deepar\/deepar\/startvideorecording(withoutputwidth:outputheight:subframe:videocompressionproperties:recordaudio:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/deepar\/deepar\/startvideorecording(withoutputwidth:outputheight:subframe:videocompressionproperties:recordaudio:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/startVideoRecording(withOutputWidth:outputHeight:subframe:videoCompressionProperties:recordAudio:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Starts video recording of the AR preview with given resolution."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startVideoRecording"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withOutputWidth"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"outputHeight"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"subframe"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":", "},{"kind":"externalParam","text":"videoCompressionProperties"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]!, "},{"kind":"externalParam","text":"recordAudio"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"title":"startVideoRecording(withOutputWidth:outputHeight:subframe:videoCompressionProperties:recordAudio:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)DeepAR(im)startVideoRecordingWithOutputWidth:outputHeight:subframe:videoCompressionProperties:recordAudio:","modules":[{"name":"DeepAR"}],"navigatorTitle":[{"kind":"identifier","text":"startVideoRecordingWithOutputWidth:outputHeight:subframe:videoCompressionProperties:recordAudio:"}]},"hierarchy":{"paths":[["doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR"]]},"seeAlsoSections":[{"title":"Video recording","identifiers":["doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/startVideoRecording(withOutputWidth:outputHeight:)","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/finishVideoRecording()","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/setVideoRecordingOutputName(_:)","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/setVideoRecordingOutputPath(_:)","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/pauseVideoRecording()","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/resumeVideoRecording()","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/startVideoRecording(withOutputWidth:outputHeight:subframe:)","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/startVideoRecording(withOutputWidth:outputHeight:subframe:videoCompressionProperties:)"],"generated":true}],"references":{"doc://ai.deepar.DeepAR/documentation/DeepAR/DeepAR/startVideoRecording(withOutputWidth:outputHeight:subframe:)":{"role":"symbol","title":"startVideoRecording(withOutputWidth:outputHeight:subframe:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startVideoRecording"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withOutputWidth"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"outputHeight"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"subframe"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Starts video recording of the AR preview with the given resolution."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/startVideoRecording(withOutputWidth:outputHeight:subframe:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"startVideoRecordingWithOutputWidth:outputHeight:subframe:"}],"url":"\/documentation\/deepar\/deepar\/startvideorecording(withoutputwidth:outputheight:subframe:)"},"doc://ai.deepar.DeepAR/documentation/DeepAR/DeepAR/startVideoRecording(withOutputWidth:outputHeight:subframe:videoCompressionProperties:recordAudio:)":{"role":"symbol","title":"startVideoRecording(withOutputWidth:outputHeight:subframe:videoCompressionProperties:recordAudio:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startVideoRecording"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withOutputWidth"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"outputHeight"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"subframe"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":", "},{"kind":"externalParam","text":"videoCompressionProperties"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]!, "},{"kind":"externalParam","text":"recordAudio"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Starts video recording of the AR preview with given resolution."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/startVideoRecording(withOutputWidth:outputHeight:subframe:videoCompressionProperties:recordAudio:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"startVideoRecordingWithOutputWidth:outputHeight:subframe:videoCompressionProperties:recordAudio:"}],"url":"\/documentation\/deepar\/deepar\/startvideorecording(withoutputwidth:outputheight:subframe:videocompressionproperties:recordaudio:)"},"https://developer.apple.com/documentation/avfoundation/avvideocompressionpropertieskey":{"title":"AVVideoCompressionPropertiesKey","titleInlineContent":[{"type":"codeVoice","code":"AVVideoCompressionPropertiesKey"}],"type":"link","identifier":"https:\/\/developer.apple.com\/documentation\/avfoundation\/avvideocompressionpropertieskey","url":"https:\/\/developer.apple.com\/documentation\/avfoundation\/avvideocompressionpropertieskey"},"doc://ai.deepar.DeepAR/documentation/DeepAR/DeepAR/enqueueAudioSample(_:)":{"role":"symbol","title":"enqueueAudioSample(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"enqueueAudioSample"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CMSampleBuffer","preciseIdentifier":"c:@T@CMSampleBufferRef"},{"kind":"text","text":"!)"}],"abstract":[{"type":"text","text":"Enqueue an audio sample to the DeepAR engine."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/enqueueAudioSample(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"enqueueAudioSample:"}],"url":"\/documentation\/deepar\/deepar\/enqueueaudiosample(_:)"},"doc://ai.deepar.DeepAR/documentation/DeepAR/DeepAR/finishVideoRecording()":{"role":"symbol","title":"finishVideoRecording()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"finishVideoRecording"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Finishes the video recording."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/finishVideoRecording()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"finishVideoRecording"}],"url":"\/documentation\/deepar\/deepar\/finishvideorecording()"},"doc://ai.deepar.DeepAR/documentation/DeepAR/DeepAR/setVideoRecordingOutputName(_:)":{"role":"symbol","title":"setVideoRecordingOutputName(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setVideoRecordingOutputName"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!)"}],"abstract":[{"type":"text","text":"Sets the video recording file output name."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/setVideoRecordingOutputName(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setVideoRecordingOutputName:"}],"url":"\/documentation\/deepar\/deepar\/setvideorecordingoutputname(_:)"},"doc://ai.deepar.DeepAR/documentation/DeepAR/DeepAR/resumeVideoRecording()":{"role":"symbol","title":"resumeVideoRecording()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"resumeVideoRecording"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Resumes video recording after it has been paused."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/resumeVideoRecording()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"resumeVideoRecording"}],"url":"\/documentation\/deepar\/deepar\/resumevideorecording()"},"doc://ai.deepar.DeepAR/documentation/DeepAR/DeepAR/startVideoRecording(withOutputWidth:outputHeight:subframe:videoCompressionProperties:)":{"role":"symbol","title":"startVideoRecording(withOutputWidth:outputHeight:subframe:videoCompressionProperties:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startVideoRecording"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withOutputWidth"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"outputHeight"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"subframe"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":", "},{"kind":"externalParam","text":"videoCompressionProperties"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]!)"}],"abstract":[{"type":"text","text":"Starts video recording of the AR preview with the given resolution."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/startVideoRecording(withOutputWidth:outputHeight:subframe:videoCompressionProperties:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"startVideoRecordingWithOutputWidth:outputHeight:subframe:videoCompressionProperties:"}],"url":"\/documentation\/deepar\/deepar\/startvideorecording(withoutputwidth:outputheight:subframe:videocompressionproperties:)"},"doc://ai.deepar.DeepAR/documentation/DeepAR/DeepAR":{"role":"symbol","title":"DeepAR","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DeepAR"}],"abstract":[{"type":"text","text":"Main class for interacting with DeepAR engine."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DeepAR"}],"url":"\/documentation\/deepar\/deepar"},"doc://ai.deepar.DeepAR/documentation/DeepAR/CameraController":{"role":"symbol","title":"CameraController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CameraController"}],"abstract":[{"type":"text","text":"Helper class that wraps "},{"type":"reference","isActive":true,"identifier":"https:\/\/developer.apple.com\/documentation\/avfoundation"},{"type":"text","text":" "},{"type":"text","text":"to handle camera-related logic like starting camera preview, choosing resolution, front or back camera, and video orientation for DeepAR."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/CameraController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CameraController"}],"url":"\/documentation\/deepar\/cameracontroller"},"doc://ai.deepar.DeepAR/documentation/DeepAR":{"role":"collection","title":"DeepAR","abstract":[{"type":"text","text":"Build rich Augmented Reality experiences for iPhone, iPad and Mac."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR","kind":"symbol","type":"topic","url":"\/documentation\/deepar"},"doc://ai.deepar.DeepAR/documentation/DeepAR/DeepAR/pauseVideoRecording()":{"role":"symbol","title":"pauseVideoRecording()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"pauseVideoRecording"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Pauses video recording if it has been started beforehand."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/pauseVideoRecording()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"pauseVideoRecording"}],"url":"\/documentation\/deepar\/deepar\/pausevideorecording()"},"https://developer.apple.com/documentation/avfoundation":{"title":"AVFoundation","titleInlineContent":[{"type":"text","text":"AVFoundation"}],"type":"link","identifier":"https:\/\/developer.apple.com\/documentation\/avfoundation","url":"https:\/\/developer.apple.com\/documentation\/avfoundation"},"doc://ai.deepar.DeepAR/documentation/DeepAR/DeepAR/startVideoRecording(withOutputWidth:outputHeight:)":{"role":"symbol","title":"startVideoRecording(withOutputWidth:outputHeight:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startVideoRecording"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withOutputWidth"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"outputHeight"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Starts video recording of the AR preview with the given resolution."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/startVideoRecording(withOutputWidth:outputHeight:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"startVideoRecordingWithOutputWidth:outputHeight:"}],"url":"\/documentation\/deepar\/deepar\/startvideorecording(withoutputwidth:outputheight:)"},"doc://ai.deepar.DeepAR/documentation/DeepAR/DeepAR/setVideoRecordingOutputPath(_:)":{"role":"symbol","title":"setVideoRecordingOutputPath(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setVideoRecordingOutputPath"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!)"}],"abstract":[{"type":"text","text":"Changes the output path for all video recordings during runtime after it is called."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/setVideoRecordingOutputPath(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setVideoRecordingOutputPath:"}],"url":"\/documentation\/deepar\/deepar\/setvideorecordingoutputpath(_:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"startVideoRecordingWithOutputWidth:outputHeight:subframe:videoCompressionProperties:recordAudio:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"startVideoRecordingWithOutputWidth:outputHeight:subframe:videoCompressionProperties:recordAudio:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"Video recording","identifiers":["doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/startVideoRecording(withOutputWidth:outputHeight:)","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/finishVideoRecording()","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/setVideoRecordingOutputName(_:)","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/setVideoRecordingOutputPath(_:)","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/pauseVideoRecording()","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/resumeVideoRecording()","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/startVideoRecording(withOutputWidth:outputHeight:subframe:)","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/startVideoRecording(withOutputWidth:outputHeight:subframe:videoCompressionProperties:)"],"generated":true}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"startVideoRecordingWithOutputWidth:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"int","preciseIdentifier":"c:I"},{"kind":"text","text":")"},{"kind":"internalParam","text":"outputWidth"},{"kind":"text","text":" "},{"kind":"identifier","text":"outputHeight:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"int","preciseIdentifier":"c:I"},{"kind":"text","text":")"},{"kind":"internalParam","text":"outputHeight"},{"kind":"text","text":" "},{"kind":"identifier","text":"subframe:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":")"},{"kind":"internalParam","text":"subframe"},{"kind":"text","text":" "},{"kind":"identifier","text":"videoCompressionProperties:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSDictionary","preciseIdentifier":"c:objc(cs)NSDictionary"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"videoCompressionProperties"},{"kind":"text","text":" "},{"kind":"identifier","text":"recordAudio:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":")"},{"kind":"internalParam","text":"recordAudio"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR~1startVideoRecording(withOutputWidth:outputHeight:subframe:)\/title","value":"startVideoRecordingWithOutputWidth:outputHeight:subframe:"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR~1startVideoRecording(withOutputWidth:outputHeight:subframe:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"startVideoRecordingWithOutputWidth:outputHeight:subframe:"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR~1startVideoRecording(withOutputWidth:outputHeight:subframe:videoCompressionProperties:recordAudio:)\/title","value":"startVideoRecordingWithOutputWidth:outputHeight:subframe:videoCompressionProperties:recordAudio:"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR~1startVideoRecording(withOutputWidth:outputHeight:subframe:videoCompressionProperties:recordAudio:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"startVideoRecordingWithOutputWidth:outputHeight:subframe:videoCompressionProperties:recordAudio:"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR~1enqueueAudioSample(_:)\/title","value":"enqueueAudioSample:"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR~1enqueueAudioSample(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"enqueueAudioSample:"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR~1finishVideoRecording()\/title","value":"finishVideoRecording"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR~1finishVideoRecording()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"finishVideoRecording"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR~1setVideoRecordingOutputName(_:)\/title","value":"setVideoRecordingOutputName:"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR~1setVideoRecordingOutputName(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setVideoRecordingOutputName:"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR~1resumeVideoRecording()\/title","value":"resumeVideoRecording"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR~1resumeVideoRecording()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"resumeVideoRecording"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR~1startVideoRecording(withOutputWidth:outputHeight:subframe:videoCompressionProperties:)\/title","value":"startVideoRecordingWithOutputWidth:outputHeight:subframe:videoCompressionProperties:"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR~1startVideoRecording(withOutputWidth:outputHeight:subframe:videoCompressionProperties:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"startVideoRecordingWithOutputWidth:outputHeight:subframe:videoCompressionProperties:"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR\/title","value":"DeepAR"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR\/fragments","value":[{"kind":"identifier","text":"DeepAR"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1CameraController\/title","value":"CameraController"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1CameraController\/fragments","value":[{"kind":"identifier","text":"CameraController"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR~1pauseVideoRecording()\/title","value":"pauseVideoRecording"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR~1pauseVideoRecording()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"pauseVideoRecording"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR~1startVideoRecording(withOutputWidth:outputHeight:)\/title","value":"startVideoRecordingWithOutputWidth:outputHeight:"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR~1startVideoRecording(withOutputWidth:outputHeight:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"startVideoRecordingWithOutputWidth:outputHeight:"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR~1setVideoRecordingOutputPath(_:)\/title","value":"setVideoRecordingOutputPath:"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR~1setVideoRecordingOutputPath(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setVideoRecordingOutputPath:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}