{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"stopProfiling"},{"kind":"text","text":"()"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/deepar\/deepar\/stopprofiling()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/deepar\/deepar\/stopprofiling()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/stopProfiling()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Stops recording profiling stats and sends the recorded CSV to the stat export server."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"stopProfiling"},{"kind":"text","text":"()"}],"title":"stopProfiling()","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)DeepAR(im)stopProfiling","modules":[{"name":"DeepAR"}],"navigatorTitle":[{"kind":"identifier","text":"stopProfiling"}]},"hierarchy":{"paths":[["doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR"]]},"references":{"doc://ai.deepar.DeepAR/documentation/DeepAR":{"role":"collection","title":"DeepAR","abstract":[{"type":"text","text":"Build rich Augmented Reality experiences for iPhone, iPad and Mac."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR","kind":"symbol","type":"topic","url":"\/documentation\/deepar"},"doc://ai.deepar.DeepAR/documentation/DeepAR/DeepAR":{"role":"symbol","title":"DeepAR","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DeepAR"}],"abstract":[{"type":"text","text":"Main class for interacting with DeepAR engine."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DeepAR"}],"url":"\/documentation\/deepar\/deepar"},"doc://ai.deepar.DeepAR/documentation/DeepAR/DeepAR/stopProfiling()":{"role":"symbol","title":"stopProfiling()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"stopProfiling"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Stops recording profiling stats and sends the recorded CSV to the stat export server."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/stopProfiling()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"stopProfiling"}],"url":"\/documentation\/deepar\/deepar\/stopprofiling()"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"stopProfiling"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"stopProfiling"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"stopProfiling"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR\/title","value":"DeepAR"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR\/fragments","value":[{"kind":"identifier","text":"DeepAR"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR~1stopProfiling()\/title","value":"stopProfiling"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR~1stopProfiling()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"stopProfiling"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}