{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"switchEffect"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withSlot"},{"kind":"text","text":" "},{"kind":"internalParam","text":"slot"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"path"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"face"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"targetGameObject"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!)"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"slot","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Specifies a namespace for the effect in the scene. In each slot, there can be only one effect. If you load another effect in the same slot the previous one will be removed and replaced with a new effect."}]}]},{"name":"path","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Path to a file located in the app bundle or anywhere in the filesystem where the app has access to. Value "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" will remove the effect from the scene. For example, one can download the filters from online locations and save them in the Documents directory."}]}]},{"name":"face","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Indicates on which face to apply the effect. DeepAR offers tracking up to 4 faces, so valid values for this parameter are 0, 1, 2, and 3. For example, if you call this method with face value 2, the effect will be only applied to the third detected face in the scene. If you want to set an effect on a different face make sure to also use a different value for the slot parameter to avoid removing the previously added effect."}]}]},{"name":"targetGameObject","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Indicates a node in the currently loaded scene\/effect into which the new effect will be loaded. By default, effects are loaded in the root node object."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/deepar\/deepar\/switcheffect(withslot:path:face:targetgameobject:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/deepar\/deepar\/switcheffect(withslot:path:face:targetgameobject:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/switchEffect(withSlot:path:face:targetGameObject:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Load a DeepAR effect file for AR preview."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"switchEffect"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withSlot"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"path"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"face"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"targetGameObject"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!)"}],"title":"switchEffect(withSlot:path:face:targetGameObject:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)DeepAR(im)switchEffectWithSlot:path:face:targetGameObject:","modules":[{"name":"DeepAR"}],"navigatorTitle":[{"kind":"identifier","text":"switchEffectWithSlot:path:face:targetGameObject:"}]},"hierarchy":{"paths":[["doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR"]]},"seeAlsoSections":[{"title":"Load AR filters for preview","identifiers":["doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/switchEffect(withSlot:path:)","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/switchEffect(withSlot:path:face:)","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/switchEffect(withSlot:data:)","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/switchEffect(withSlot:data:face:)"],"generated":true}],"references":{"doc://ai.deepar.DeepAR/documentation/DeepAR":{"role":"collection","title":"DeepAR","abstract":[{"type":"text","text":"Build rich Augmented Reality experiences for iPhone, iPad and Mac."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR","kind":"symbol","type":"topic","url":"\/documentation\/deepar"},"doc://ai.deepar.DeepAR/documentation/DeepAR/DeepAR/switchEffect(withSlot:data:)":{"role":"symbol","title":"switchEffect(withSlot:data:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"switchEffect"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withSlot"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"data"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"!)"}],"abstract":[{"type":"text","text":"Load a DeepAR effect file for AR preview."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/switchEffect(withSlot:data:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"switchEffectWithSlot:data:"}],"url":"\/documentation\/deepar\/deepar\/switcheffect(withslot:data:)"},"doc://ai.deepar.DeepAR/documentation/DeepAR/DeepAR/switchEffect(withSlot:path:face:targetGameObject:)":{"role":"symbol","title":"switchEffect(withSlot:path:face:targetGameObject:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"switchEffect"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withSlot"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"path"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"face"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"targetGameObject"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!)"}],"abstract":[{"type":"text","text":"Load a DeepAR effect file for AR preview."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/switchEffect(withSlot:path:face:targetGameObject:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"switchEffectWithSlot:path:face:targetGameObject:"}],"url":"\/documentation\/deepar\/deepar\/switcheffect(withslot:path:face:targetgameobject:)"},"doc://ai.deepar.DeepAR/documentation/DeepAR/DeepAR/switchEffect(withSlot:path:)":{"role":"symbol","title":"switchEffect(withSlot:path:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"switchEffect"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withSlot"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"path"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!)"}],"abstract":[{"type":"text","text":"Load a DeepAR effect file for AR preview."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/switchEffect(withSlot:path:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"switchEffectWithSlot:path:"}],"url":"\/documentation\/deepar\/deepar\/switcheffect(withslot:path:)"},"doc://ai.deepar.DeepAR/documentation/DeepAR/DeepAR":{"role":"symbol","title":"DeepAR","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DeepAR"}],"abstract":[{"type":"text","text":"Main class for interacting with DeepAR engine."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DeepAR"}],"url":"\/documentation\/deepar\/deepar"},"doc://ai.deepar.DeepAR/documentation/DeepAR/DeepAR/switchEffect(withSlot:data:face:)":{"role":"symbol","title":"switchEffect(withSlot:data:face:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"switchEffect"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withSlot"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"data"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"face"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Load a DeepAR effect file for AR preview."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/switchEffect(withSlot:data:face:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"switchEffectWithSlot:data:face:"}],"url":"\/documentation\/deepar\/deepar\/switcheffect(withslot:data:face:)"},"doc://ai.deepar.DeepAR/documentation/DeepAR/DeepAR/switchEffect(withSlot:path:face:)":{"role":"symbol","title":"switchEffect(withSlot:path:face:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"switchEffect"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withSlot"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"path"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"face"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Load a DeepAR effect file for AR preview."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/switchEffect(withSlot:path:face:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"switchEffectWithSlot:path:face:"}],"url":"\/documentation\/deepar\/deepar\/switcheffect(withslot:path:face:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"switchEffectWithSlot:path:face:targetGameObject:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"switchEffectWithSlot:path:face:targetGameObject:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"Load AR filters for preview","identifiers":["doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/switchEffect(withSlot:path:)","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/switchEffect(withSlot:path:face:)","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/switchEffect(withSlot:data:)","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/switchEffect(withSlot:data:face:)"],"generated":true}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"switchEffectWithSlot:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"slot"},{"kind":"text","text":" "},{"kind":"identifier","text":"path:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"path"},{"kind":"text","text":" "},{"kind":"identifier","text":"face:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":")"},{"kind":"internalParam","text":"face"},{"kind":"text","text":" "},{"kind":"identifier","text":"targetGameObject:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"targetGameObject"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR~1switchEffect(withSlot:data:)\/title","value":"switchEffectWithSlot:data:"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR~1switchEffect(withSlot:data:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"switchEffectWithSlot:data:"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR~1switchEffect(withSlot:path:face:targetGameObject:)\/title","value":"switchEffectWithSlot:path:face:targetGameObject:"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR~1switchEffect(withSlot:path:face:targetGameObject:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"switchEffectWithSlot:path:face:targetGameObject:"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR~1switchEffect(withSlot:path:)\/title","value":"switchEffectWithSlot:path:"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR~1switchEffect(withSlot:path:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"switchEffectWithSlot:path:"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR\/title","value":"DeepAR"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR\/fragments","value":[{"kind":"identifier","text":"DeepAR"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR~1switchEffect(withSlot:data:face:)\/title","value":"switchEffectWithSlot:data:face:"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR~1switchEffect(withSlot:data:face:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"switchEffectWithSlot:data:face:"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR~1switchEffect(withSlot:path:face:)\/title","value":"switchEffectWithSlot:path:face:"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR~1switchEffect(withSlot:path:face:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"switchEffectWithSlot:path:face:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}