{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"touchOccurred"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"touchInfo"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/TouchInfo","preciseIdentifier":"c:@SA@TouchInfo","text":"TouchInfo"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/deepar\/deepar\/touchoccurred(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/deepar\/deepar\/touchoccurred(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/touchOccurred(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Informs DeepAR that a touch occured."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"touchOccurred"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"TouchInfo","preciseIdentifier":"c:@SA@TouchInfo"},{"kind":"text","text":")"}],"title":"touchOccurred(_:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)DeepAR(im)touchOccurred:","modules":[{"name":"DeepAR"}],"navigatorTitle":[{"kind":"identifier","text":"touchOccurred:"}]},"hierarchy":{"paths":[["doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR"]]},"seeAlsoSections":[{"title":"Interactions","identifiers":["doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/fireTrigger(_:)","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/muteSound(_:)","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/moveGameObject(_:targetGameObjectname:)"],"generated":true}],"references":{"doc://ai.deepar.DeepAR/documentation/DeepAR/DeepAR/touchOccurred(_:)":{"role":"symbol","title":"touchOccurred(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"touchOccurred"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"TouchInfo","preciseIdentifier":"c:@SA@TouchInfo"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Informs DeepAR that a touch occured."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/touchOccurred(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"touchOccurred:"}],"url":"\/documentation\/deepar\/deepar\/touchoccurred(_:)"},"doc://ai.deepar.DeepAR/documentation/DeepAR/DeepAR":{"role":"symbol","title":"DeepAR","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DeepAR"}],"abstract":[{"type":"text","text":"Main class for interacting with DeepAR engine."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DeepAR"}],"url":"\/documentation\/deepar\/deepar"},"doc://ai.deepar.DeepAR/documentation/DeepAR/DeepAR/fireTrigger(_:)":{"role":"symbol","title":"fireTrigger(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"fireTrigger"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!)"}],"abstract":[{"type":"text","text":"Fire named trigger of an fbx animation set on the currently loaded effect."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/fireTrigger(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"fireTrigger:"}],"url":"\/documentation\/deepar\/deepar\/firetrigger(_:)"},"doc://ai.deepar.DeepAR/documentation/DeepAR":{"role":"collection","title":"DeepAR","abstract":[{"type":"text","text":"Build rich Augmented Reality experiences for iPhone, iPad and Mac."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR","kind":"symbol","type":"topic","url":"\/documentation\/deepar"},"doc://ai.deepar.DeepAR/documentation/DeepAR/TouchInfo":{"role":"symbol","title":"TouchInfo","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"TouchInfo"}],"abstract":[{"type":"text","text":"Contains information about the current location and status of the started touch."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/TouchInfo","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TouchInfo"}],"url":"\/documentation\/deepar\/touchinfo"},"doc://ai.deepar.DeepAR/documentation/DeepAR/DeepAR/muteSound(_:)":{"role":"symbol","title":"muteSound(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"muteSound"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Mutes or un-mutes all the sounds that are currently playing from the loaded effects."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/muteSound(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"muteSound:"}],"url":"\/documentation\/deepar\/deepar\/mutesound(_:)"},"doc://ai.deepar.DeepAR/documentation/DeepAR/DeepAR/moveGameObject(_:targetGameObjectname:)":{"role":"symbol","title":"moveGameObject(_:targetGameObjectname:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"moveGameObject"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"targetGameObjectname"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!)"}],"abstract":[{"type":"text","text":"Moves the selected game object from its current position in a tree and sets it as a direct child of a target game object."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/moveGameObject(_:targetGameObjectname:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"moveGameObject:targetGameObjectname:"}],"url":"\/documentation\/deepar\/deepar\/movegameobject(_:targetgameobjectname:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"touchOccurred:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"touchOccurred:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"Interactions","identifiers":["doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/fireTrigger(_:)","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/muteSound(_:)","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/moveGameObject(_:targetGameObjectname:)"],"generated":true}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"touchOccurred:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/TouchInfo","preciseIdentifier":"c:@SA@TouchInfo","text":"TouchInfo"},{"kind":"text","text":")"},{"kind":"internalParam","text":"touchInfo"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR~1touchOccurred(_:)\/title","value":"touchOccurred:"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR~1touchOccurred(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"touchOccurred:"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR\/title","value":"DeepAR"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR\/fragments","value":[{"kind":"identifier","text":"DeepAR"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR~1fireTrigger(_:)\/title","value":"fireTrigger:"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR~1fireTrigger(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"fireTrigger:"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1TouchInfo\/title","value":"TouchInfo"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR~1muteSound(_:)\/title","value":"muteSound:"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR~1muteSound(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"muteSound:"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR~1moveGameObject(_:targetGameObjectname:)\/title","value":"moveGameObject:targetGameObjectname:"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR~1moveGameObject(_:targetGameObjectname:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"moveGameObject:targetGameObjectname:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}