{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"videoRecordingWarmupEnabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"If set to true, "},{"type":"reference","isActive":true,"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/startVideoRecording(withOutputWidth:outputHeight:)"},{"type":"text","text":" and other video recording methods work"},{"type":"text","text":" "},{"type":"text","text":"to allow the video recording to be started immediately during runtime"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"To use video recodring warmup follow these steps"}]},{"type":"orderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Set videoRecordingWarmupEnabled = true after calling "},{"type":"codeVoice","code":"DeepAR()"}]}]}]},{"type":"codeListing","syntax":"swift","code":["override func viewDidLoad() {"," self.deepAR = DeepAR()"," self.deepAR.videoRecordingWarmupEnabled = true","}"]},{"type":"orderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"After DeepAR is initialized ("},{"type":"reference","isActive":true,"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepARDelegate\/didInitialize()"},{"type":"text","text":")"},{"type":"text","text":" "},{"type":"text","text":"call "},{"type":"reference","isActive":true,"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/startVideoRecording(withOutputWidth:outputHeight:)"},{"type":"text","text":" or any other video recording methods with desired parameters."},{"type":"text","text":" "},{"type":"text","text":"Only needs to be called once."}]}]}]},{"type":"codeListing","syntax":"swift","code":["func didInitialize {","    self.deepAR.startVideoRecording(withOutputWidth:outputWidth, outputHeight:outputHeight, subframe:screenRect)","}"]},{"type":"orderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Wait for "},{"type":"reference","isActive":true,"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepARDelegate\/didFinishPreparingForVideoRecording()"},{"type":"text","text":" delegate method to enable recording."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Call "},{"type":"reference","isActive":true,"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/resumeVideoRecording()"},{"type":"text","text":"."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Call "},{"type":"reference","isActive":true,"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/finishVideoRecording()"},{"type":"text","text":". This will automatically start preparing for the next recording session with the parameters set in "},{"type":"reference","isActive":true,"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/startVideoRecording(withOutputWidth:outputHeight:)"},{"type":"text","text":"."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Wait for "},{"type":"reference","isActive":true,"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepARDelegate\/didFinishVideoRecording(_:)"},{"type":"text","text":" delegate method and repeat the resumeVideoRecording step as needed"}]}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/deepar\/deepar\/videorecordingwarmupenabled"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/deepar\/deepar\/videorecordingwarmupenabled"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/videoRecordingWarmupEnabled","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"If enabled, this removes the lag that occures when starting to record first video with DeepAR."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"videoRecordingWarmupEnabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"title":"videoRecordingWarmupEnabled","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)DeepAR(py)videoRecordingWarmupEnabled","modules":[{"name":"DeepAR"}],"navigatorTitle":[{"kind":"identifier","text":"videoRecordingWarmupEnabled"}]},"hierarchy":{"paths":[["doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR"]]},"references":{"doc://ai.deepar.DeepAR/documentation/DeepAR/DeepARDelegate/didFinishPreparingForVideoRecording()":{"navigatorTitle":[{"kind":"identifier","text":"didFinishPreparingForVideoRecording"}],"role":"symbol","title":"didFinishPreparingForVideoRecording()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didFinishPreparingForVideoRecording"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Called when the video recording preparation is finished."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepARDelegate\/didFinishPreparingForVideoRecording()","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/deepar\/deepardelegate\/didfinishpreparingforvideorecording()"},"doc://ai.deepar.DeepAR/documentation/DeepAR/DeepAR":{"role":"symbol","title":"DeepAR","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DeepAR"}],"abstract":[{"type":"text","text":"Main class for interacting with DeepAR engine."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DeepAR"}],"url":"\/documentation\/deepar\/deepar"},"doc://ai.deepar.DeepAR/documentation/DeepAR/DeepARDelegate/didInitialize()":{"role":"symbol","title":"didInitialize()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didInitialize"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Called when the DeepAR engine initialization is complete."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepARDelegate\/didInitialize()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"didInitialize"}],"url":"\/documentation\/deepar\/deepardelegate\/didinitialize()"},"doc://ai.deepar.DeepAR/documentation/DeepAR/DeepAR/startVideoRecording(withOutputWidth:outputHeight:)":{"role":"symbol","title":"startVideoRecording(withOutputWidth:outputHeight:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startVideoRecording"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withOutputWidth"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"outputHeight"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Starts video recording of the AR preview with the given resolution."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/startVideoRecording(withOutputWidth:outputHeight:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"startVideoRecordingWithOutputWidth:outputHeight:"}],"url":"\/documentation\/deepar\/deepar\/startvideorecording(withoutputwidth:outputheight:)"},"doc://ai.deepar.DeepAR/documentation/DeepAR/DeepAR/resumeVideoRecording()":{"role":"symbol","title":"resumeVideoRecording()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"resumeVideoRecording"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Resumes video recording after it has been paused."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/resumeVideoRecording()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"resumeVideoRecording"}],"url":"\/documentation\/deepar\/deepar\/resumevideorecording()"},"doc://ai.deepar.DeepAR/documentation/DeepAR/DeepAR/finishVideoRecording()":{"role":"symbol","title":"finishVideoRecording()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"finishVideoRecording"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Finishes the video recording."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/finishVideoRecording()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"finishVideoRecording"}],"url":"\/documentation\/deepar\/deepar\/finishvideorecording()"},"doc://ai.deepar.DeepAR/documentation/DeepAR/DeepARDelegate/didFinishVideoRecording(_:)":{"role":"symbol","title":"didFinishVideoRecording(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didFinishVideoRecording"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!)"}],"abstract":[{"type":"text","text":"Called when the video recording is finished."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepARDelegate\/didFinishVideoRecording(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"didFinishVideoRecording:"}],"url":"\/documentation\/deepar\/deepardelegate\/didfinishvideorecording(_:)"},"doc://ai.deepar.DeepAR/documentation/DeepAR":{"role":"collection","title":"DeepAR","abstract":[{"type":"text","text":"Build rich Augmented Reality experiences for iPhone, iPad and Mac."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR","kind":"symbol","type":"topic","url":"\/documentation\/deepar"},"doc://ai.deepar.DeepAR/documentation/DeepAR/DeepAR/videoRecordingWarmupEnabled":{"role":"symbol","title":"videoRecordingWarmupEnabled","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"videoRecordingWarmupEnabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"If enabled, this removes the lag that occures when starting to record first video with DeepAR."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/DeepAR\/videoRecordingWarmupEnabled","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"videoRecordingWarmupEnabled"}],"url":"\/documentation\/deepar\/deepar\/videorecordingwarmupenabled"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"videoRecordingWarmupEnabled"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"videoRecordingWarmupEnabled"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":" "},{"kind":"identifier","text":"videoRecordingWarmupEnabled"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepARDelegate~1didFinishPreparingForVideoRecording()\/title","value":"didFinishPreparingForVideoRecording"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepARDelegate~1didFinishPreparingForVideoRecording()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didFinishPreparingForVideoRecording"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR\/title","value":"DeepAR"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR\/fragments","value":[{"kind":"identifier","text":"DeepAR"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepARDelegate~1didInitialize()\/title","value":"didInitialize"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepARDelegate~1didInitialize()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didInitialize"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR~1startVideoRecording(withOutputWidth:outputHeight:)\/title","value":"startVideoRecordingWithOutputWidth:outputHeight:"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR~1startVideoRecording(withOutputWidth:outputHeight:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"startVideoRecordingWithOutputWidth:outputHeight:"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR~1resumeVideoRecording()\/title","value":"resumeVideoRecording"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR~1resumeVideoRecording()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"resumeVideoRecording"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR~1finishVideoRecording()\/title","value":"finishVideoRecording"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR~1finishVideoRecording()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"finishVideoRecording"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepARDelegate~1didFinishVideoRecording(_:)\/title","value":"didFinishVideoRecording:"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepARDelegate~1didFinishVideoRecording(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didFinishVideoRecording:"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR~1videoRecordingWarmupEnabled\/title","value":"videoRecordingWarmupEnabled"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1DeepAR~1videoRecordingWarmupEnabled\/fragments","value":[{"kind":"identifier","text":"videoRecordingWarmupEnabled"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}