{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"AGX"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/deepar\/tonemapping\/agx"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/deepar\/tonemapping\/agx"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/ToneMapping\/AGX","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"AGX"}],"title":"ToneMapping.AGX","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@ToneMapping@AGX","modules":[{"name":"DeepAR"}],"navigatorTitle":[{"kind":"identifier","text":"AGX"}]},"hierarchy":{"paths":[["doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR","doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/ToneMapping"]]},"references":{"doc://ai.deepar.DeepAR/documentation/DeepAR/ToneMapping/AGX":{"role":"symbol","title":"ToneMapping.AGX","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"AGX"}],"abstract":[],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/ToneMapping\/AGX","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AGX"}],"url":"\/documentation\/deepar\/tonemapping\/agx"},"doc://ai.deepar.DeepAR/documentation/DeepAR/ToneMapping":{"role":"symbol","title":"ToneMapping","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ToneMapping"}],"abstract":[{"type":"text","text":"Possible types for tone mapping"}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR\/ToneMapping","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ToneMapping"}],"url":"\/documentation\/deepar\/tonemapping"},"doc://ai.deepar.DeepAR/documentation/DeepAR":{"role":"collection","title":"DeepAR","abstract":[{"type":"text","text":"Build rich Augmented Reality experiences for iPhone, iPad and Mac."}],"identifier":"doc:\/\/ai.deepar.DeepAR\/documentation\/DeepAR","kind":"symbol","type":"topic","url":"\/documentation\/deepar"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AGX"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AGX"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AGX"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1ToneMapping~1AGX\/title","value":"AGX"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1ToneMapping~1AGX\/fragments","value":[{"kind":"identifier","text":"AGX"}]},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1ToneMapping\/title","value":"ToneMapping"},{"op":"replace","path":"\/references\/doc:~1~1ai.deepar.DeepAR~1documentation~1DeepAR~1ToneMapping\/fragments","value":[{"kind":"identifier","text":"ToneMapping"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}